### ISSUE TITLE
Is the input voltage for HTU21D 3.3V?

### ISSUE THREAD

**Issue by jaeseok-park** [rwaldron/johnny-five#1007]
The picture for HTU21D circuit shows that it can accept 5V Vcc.
https://github.com/rwaldron/johnny-five/blob/master/docs/breadboard/humidity-htu21d.png

However, as the specification for it, the max input voltage seems to be 3.6V.
https://www.adafruit.com/datasheets/1899_HTU21D.pdf

Could you fix the picture, please?

**Comment by rwaldron** [comment]
Thanks for the report!

**Comment by jaeseok-park** [comment]
The new picture uses analog pins instead of I2C SCL and SDA.
Is it ok?

**Comment by rwaldron** [comment]
A4 and A5 are SDA and SCL

**Comment by jaeseok-park** [comment]
I didn't know it. Thank you. :-)
