### ISSUE TITLE
Expander MCP23017 - faulty fritzing sketches

### ISSUE THREAD

**Issue by mwittig** [rwaldron/johnny-five#1009]
Hi, 

I am currently experimenting with the MCP23017 expander and as I am new to this, I followed the provided sketches. It took me some time to figure out the sketched are faulty:
* I2C lines are connected to the wrong pins. They need to be connected 12 & 12 instead of 11 & 12
* The hardware address pins 15 to 17 need to be grounded for default address 0x20 to achieve reliable operation. At least this was the case for my setup where the expander did not receive some commands  when the address pin were not properly grounded. This should also in line with page 8 of the datasheet as far as I understand this: "The pins must be biased externally" - see http://ww1.microchip.com/downloads/en/DeviceDoc/21952b.pdf

I'll file a PR with suggested fixture shortly.

**Comment by rwaldron** [comment]
Thanks for the fixes!
