### ISSUE TITLE
Make diagrams of each program for non-arduino platforms

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#1018]
This involves: 
- making a fritzing diagram for one or all of the relevant (non-arduino) platforms
- add "breadboards" entry to tpl/programs.json for relevant programs
- Requires confirming that the program works with the hardware

**Comment by rwaldron** [comment]
Priority order: 

- Tessel 2
- Raspberry Pi
- Edison
- BeagleBone

**Comment by Resseguie** [comment]
Which platforms have existing fritzing components available vs need new ones made?
