### ISSUE TITLE
Support for Grove Temp & Humidity I2C sensor

### ISSUE THREAD

**Issue by dougseven** [rwaldron/johnny-five#1039]
I would like to add support for the [Grove - Temperature & Humidity Sensor](http://www.seeedstudio.com/wiki/Grove_-_Tempture%26Humidity_Sensor_(High-Accuracy_%26Mini)_v1.0) that is included in the [Grove Indoor Environment Kit for Intel® Edison](http://www.seeedstudio.com/depot/Grove-Indoor-Environment-Kit-for-Intel-Edison-p-2427.html). It utilizes a TH02 sensor that can meet measurement needs of general purposes. The C driver for the TH02 is [here](https://github.com/Seeed-Studio/Grove_Temper_Humidity_TH02)

**Comment by rwaldron** [comment]
Looks pretty straight forward! 

- Start by reviewing the HTU21D (which is a similar component): 
  - https://github.com/rwaldron/johnny-five/blob/master/lib/imu.js#L24-L75
  - you'll define a similar driver entry in that same location 
- Next, declare the base controller, again here's the HTU21D:
  - https://github.com/rwaldron/johnny-five/blob/master/lib/imu.js#L1174-L1215
- Hygrometer controller:
  - https://github.com/rwaldron/johnny-five/blob/master/lib/hygrometer.js#L8-L26
- Thermometer controller: 
  - https://github.com/rwaldron/johnny-five/blob/master/lib/thermometer.js#L297-L314
- Diagram
  - fzz and png
- examples in eg/
  - we'll add the examples to tpl/programs.json and generate the markdown

**Comment by rwaldron** [comment]
@dougseven I have another user that's reporting issues with the Grove Temp & Humidity sensor; they reported it was a BMP180, but a photograph of their hardware reveals that it's actually this component. I'd like to implement the controller driver for this today.

**Comment by dougseven** [comment]
I had started looking into it, but haven't had time to work on it. I can look at it more today.

**Comment by rwaldron** [comment]
Do you mind if I just take over?

**Comment by dougseven** [comment]
Go for it - happy to help (test, etc.)

**Comment by rwaldron** [comment]
Excellent—I will call on you to do so :)

**Comment by rwaldron** [comment]
@dougseven ready for testing—update to latest version

**Comment by dougseven** [comment]
I'm going to try a different board with the official Yocto image, but using "latest" for johnny-five and edison-io with **ubiLinux** and Node v4.3.1 gets this:

NOTE: I have previously run a johnny-five app on this board in this configuration.

root@ubilinux:~/iot-labs/azure-iot# node iot-starter-kit.js 
  NOTICE
  --------------------------------
  This OS image is no longer supported.
  Please upgrade to IoTKit Image with libmraa0 support.
  https://github.com/intel-iot-devkit/mraa/#installing-on-your-board
  --------------------------------
/root/iot-labs/azure-iot/node_modules/edison-io/node_modules/galileo-io/lib/galileo.js:48
if (Pin.IO.getPlatformType() === 2) {
          ^

TypeError: Cannot read property 'getPlatformType' of undefined
    at Object.<anonymous> (/root/iot-labs/azure-iot/node_modules/edison-io/node_modules/galileo-io/lib/galileo.js:48:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/iot-labs/azure-iot/node_modules/edison-io/lib/edison.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
root@ubilinux:~/iot-labs/azure-iot# uname -a
Linux ubilinux 3.10.17-yocto-standard-r2 #7 SMP PREEMPT Thu Feb 26 09:57:06 UTC 2015 i686 GNU/Linux
root@ubilinux:~/iot-labs/azure-iot#

**Comment by rwaldron** [comment]
Weird, that should only happen if the native bindings are missing 0_o

**Comment by dougseven** [comment]
I set up a new Edison with the official Yocto image. I get some very radical readings using the sample for the TH02 - 80-degree swings (in Celsius). 

```temperature
  celsius           :  102
  fahrenheit        :  215.6
  kelvin            :  375.15
--------------------------------------
Hygrometer
  relative humidity :  52
--------------------------------------
temperature
  celsius           :  102.375
  fahrenheit        :  216.275
  kelvin            :  375.525
--------------------------------------
Hygrometer
  relative humidity :  52.1875
--------------------------------------
temperature
  celsius           :  102.375
  fahrenheit        :  216.275
  kelvin            :  375.525
--------------------------------------
Hygrometer
  relative humidity :  52.1875
--------------------------------------
temperature
  celsius           :  22
  fahrenheit        :  71.6
  kelvin            :  295.15
--------------------------------------
Hygrometer
  relative humidity :  12.375
--------------------------------------
temperature
  celsius           :  22
  fahrenheit        :  71.6
  kelvin            :  295.15
--------------------------------------
Hygrometer
  relative humidity :  12.375
--------------------------------------
```

Other times it would start, read a couple times and then stop reading/outputing to the console:

```
root@edison:~/iot-labs/basic# node th02.js 
1458718176636 Device(s) Intel Edison  
1458718176653 Connected Intel Edison  
1458718176676 Repl Initialized  
>> temperature
  celsius           :  NaN
  fahrenheit        :  NaN
  kelvin            :  NaN
--------------------------------------
Hygrometer
  relative humidity :  -24
--------------------------------------
temperature
  celsius           :  -50
  fahrenheit        :  -58
  kelvin            :  223.14999999999998
--------------------------------------
Hygrometer
  relative humidity :  -24
--------------------------------------
```

That is where it would stop and nothing more would happen. I can stop it (Ctrl+C twice) and run it again, or another simple sample. Not sure what is happening or how to debug it. I tried it with multiple Grove - Temperature&Humidity Sensor (High-Accuracy &Mini).

**Comment by rwaldron** [comment]
Interesting, I will have a closer look and double check that the initialization operations are correct.

**Comment by rwaldron** [comment]
Well, I missed the status check :\

**Comment by rwaldron** [comment]
And of course, I don't have my TH02 with me (I'm in Boston until tomorrow). I have a fix for this, but I just need to double check it against actual hardware, so I should have something by Saturday

**Comment by dougseven** [comment]
If it's in a branch I can pull then I can test it tonight. No rush though.

Sent from Outlook on iOS




On Thu, Mar 24, 2016 at 12:49 PM -0700, "Rick Waldron" <notifications@github.com> wrote:





And of course, I don't have my TH02 with me (I'm in Boston until tomorrow). I have a fix for this, but I just need to double check it against actual hardware, so I should have something by Saturday

---

**Comment by rwaldron** [comment]
@dougseven I completely forgot to ping you on this; you can pull and run the last round of work from master
