### ISSUE TITLE
Support to SHARP GP2Y0A21 (Distance Sensor)

### ISSUE THREAD

**Issue by UlisesGascon** [rwaldron/johnny-five#1042]
Hi All!

I needed to include this [sensor](http://www.dfrobot.com/index.php?route=product/product&product_id=328#.Vsy1ZpPhB0I) in one of my projects.  This sensor is not supported yet by J5, but it is possible to work with it as a *five.Sensor()*.

Here I share the code that I used in my project.

```javascript
  var sensor = new five.Sensor("A11");

  sensor.on("change", function() {

    var valorSensor = this.value;
    var valorCm =  Math.pow(3027.4/valorSensor, 1.2134).toFixed(2);
    
    if(valorCm < 10){
      console.log("Demasiado cerca");
    } else if (valorCm > 80) {
      console.log("Demasiado lejos");
    } else {
      console.log("Distancia: "+valorCm+"cm");
    }

  });
```

If you are interested I can update *lib/proximity.js* with this sensor and submit a pull request.

Have a nice day!

**Comment by rwaldron** [comment]
Hi! This sensor is supported in the `Proximity` class: http://johnny-five.io/api/proximity/, take a look at: http://johnny-five.io/api/proximity/#component-initialization
