### ISSUE TITLE
IMU in different ports

### ISSUE THREAD

**Issue by henricavalcante** [rwaldron/johnny-five#1051]
Can I run this [example](https://github.com/rwaldron/johnny-five/blob/master/docs/imu-mpu6050.md) in different ports?

eg.
A0 <--> SCL
A3 <--> SDA

**Comment by rwaldron** [comment]
No, the A4 and A5 are wired to the Arduino's I2C bus. Here's a bit more about that: http://tronixstuff.com/2010/10/20/tutorial-arduino-and-the-i2c-bus/

Alternatively, there are SDA SCL ports on the digital side, close to the reset button.
