### ISSUE TITLE
MS5611-01BA03 Altimeter support

### ISSUE THREAD

**Issue by henricavalcante** [rwaldron/johnny-five#1052]
Does Johnny-five supports MS5611-01BA03 Altimeter?

http://www.varesano.net/blog/fabio/ms5611-01ba-arduino-library-first-developments-results

**Comment by rwaldron** [comment]
Not yet? Looks like I bought one but never wrote support for it. I can work on it this week.

**Comment by henricavalcante** [comment]
Thanks.

**Comment by rwaldron** [comment]
This is now supported, here is a basic usage example: http://johnny-five.io/examples/multi-MS5611/
