### ISSUE TITLE
Higher board timeout required when using serialport over TCP to connect to a remote board

### ISSUE THREAD

**Issue by mwittig** [rwaldron/johnny-five#1053]
The timeout of 1e4 milliseconds for the board to become ready appears to be too short when using alternative transports, like serialport over TCP to connect to a remote board. See also https://github.com/firmata/arduino/issues/257#issuecomment-193424735

My suggestion is to make the timeout configurable as part of the board configuration. I have a working fork and I'll be happy to provide a PR for it.

mwittig/johnny-five@d4ced98

**Comment by mwittig** [comment]
Updated Wiki page https://github.com/rwaldron/johnny-five/wiki/Board

**Comment by rwaldron** [comment]
Nice!

**Comment by mwittig** [comment]
Landed in 0.9.31

**Comment by rwaldron** [comment]
Ah, yes. Thank you for following up with the admin :)
