### ISSUE TITLE
Generic pin state reading

### ISSUE THREAD

**Issue by alexcroox** [rwaldron/johnny-five#1055]
Sorry if this is in the documentation, I couldn't find it!

I want to do a basic digital read on a pin to know if it's high or low, even better if there's a `change` event I can listen to.

I'm using a vibration sensor, but it's one of these that convert it to digital for me, so none of the sensor libraries apply

![ss](http://cl.ly/fM55/d)

I saw in an issue somewhere about using digitalRead() but I can't find any further info on this function.

**Comment by alexcroox** [comment]
I believe the solution is

```
var sensor = new five.Pin({
        "pin": 5
 });

sensor.on("high", function() {

        console.log('Scored!');
});
```

**Comment by rwaldron** [comment]
You can you `Sensor.Digital`: 

```js
var vibration = new five.Sensor.Digital(5);
vibration.on("change", function() {
  // ...
});
```

**Comment by alexcroox** [comment]
Nice thank you!

I assume I can expand that to specify the virtual board as well as the pin

```
var sensor = new five.Sensor.Digital({
        "pin": 5,
        "board": virtual
});
```

**Comment by rwaldron** [comment]
Yessir!
