### ISSUE TITLE
Intel edison problem using sensor TSL2561

### ISSUE THREAD

**Issue by hannes93** [rwaldron/johnny-five#1060]
Hey there,
Is there somebody out who now how to get lux value of tsl2561 sensror?

I´m gong to use the intel edison with node.ja and the TSL2561 sensor from Adafruit....
Thanke you for your time.
Greetz \h

**Comment by lyzadanger** [comment]
Hi, @hannes93 ! Were you able to get the sensor to work? The TSL2561 is an I2C sensor that is supported by Johnny-Five's `Light` component class. You can find [documentation here](http://johnny-five.io/api/light/). Let me know if I can be of any further help!

**Comment by rwaldron** [comment]
FWIW, this sensor's controller is presently broken, as reported in https://github.com/rwaldron/johnny-five/issues/1196 I have work in progress towards fixing.
