### ISSUE TITLE
Issues on johnny-five/serialport - Win7 - 64 -bit 

### ISSUE THREAD

**Issue by FutureAndroidLearn** [rwaldron/johnny-five#1079]
Hi,

I've already installed johnny-five in a old PC with Windows Vista 32-bit, following this procedure:
- Installing Node.js 
- Installing Python 
- npm install -g node-gyp
- npm install johnny-five

And everything went perfect, now I'm programming my Arduino UNO with JavaScript. However, when I tried to install johnny-five in Windows 7 - 64 bit following: 

https://github.com/rwaldron/johnny-five/wiki/Getting-Started

it was not possible to make things worked perfect. It seems like there are some problem with _serialport module_. I got this:

_> serialport@2.0.6 install C:\cygwin64\home\ACUAVALLE\thingplus\openhardware\arduino\grove-starter-kit\node_modules\johnny-five\node_modules\serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp
C:\cygwin64\home\ACUAVALLE\thingplus\openhardware\arduino\grove-starter-kit\node_modules\johnny-five\node_modules\serialport>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean
 http GET https://github.com/voodootikigod/node-serialport/releases/download/2.0.6/node-v11-win32-x64.tar.gz
node-pre-gyp http Cannot find module 'is-property' (falling back to source compile with node-gyp)

C:\cygwin64\home\ACUAVALLE\thingplus\openhardware\arduino\grove-starter-kit\node_modules\johnny-five\node_modules\serialport>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\cygwin64\home\ACUAVALLE\thingplus\openhardware\arduino\grove-starter-kit\node_modules\johnny-five\node_modules\serialport\build\Release\node-v11-win32-x64\serialport.node --module_name=serialport --module_path=C:\cygwin64\home\ACUAVALLE\thingplus\openhardware\arduino\grove-starter-kit\node_modules\johnny-five\node_modules\serialport\build\Release\node-v11-win32-x64 --msvs_version=2015
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp", line 18, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 526, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 502, in gyp_main
    options.circular_check)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1713, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 366, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2015'
gypnode-pre-gypnpm WARN optional dep failed, continuing serialport@2.0.6
npmlodash@2.4.1 node_modules\lodash_

Others modules seems to be properly installed.

Thanks in advance for any help with this issue. By the way, why is it necessary to install Visual Studio?

**Comment by rwaldron** [comment]
Hi, thanks for taking the time to file an issue. This issue is coming from node-serialport, so there's nothing we can do directly. The original report is here: https://github.com/voodootikigod/node-serialport/issues/681
