### ISSUE TITLE
BMP180 conversion delays

### ISSUE THREAD

**Issue by boneskull** [rwaldron/johnny-five#1104]
Where do the numbers (ms) from [this comment](https://github.com/rwaldron/johnny-five/blob/master/lib/imu.js#L867) (and subsequent code) come from?  Reading over [the datasheet](https://cdn-shop.adafruit.com/datasheets/BST-BMP180-DS000-09.pdf), I can't match them to anything.  If the code is incorrect, the datasheet may have been updated since implementation...

**Comment by rwaldron** [comment]
Those values are rounded max column values: 

![](https://i.gyazo.com/000e0f653a3795e1f61dcf4e1ef24411.png)

Which follows the Adafruit implementation: 

https://github.com/adafruit/Adafruit_BMP085_Unified/blob/master/Adafruit_BMP085_U.cpp#L188-L203
