### ISSUE TITLE
Using a NFC shield

### ISSUE THREAD

**Issue by richwestcoast** [rwaldron/johnny-five#1108]
Is it possible to use a NFC shields on the johnny-five platform ?

**Comment by Rickgg** [comment]
NFC shields usually have a way to comunicate tl a controller, so depending on the type of communication (I2C, Serial) is the way you have to use Johnny five to communicate. Read the documentation for your shield to find our the communication type.

**Comment by henricavalcante** [comment]
@richwestcoast which shield are you using?

**Comment by dtex** [comment]
@richwestcoast 

I'm closing this since we haven't heard back, but I've added a request for RFID/NFC support on our Johnny-Five [Requested Features](../wiki/Requested-Features) page.
