### ISSUE TITLE
Using J5 and Modbus protocol?

### ISSUE THREAD

**Issue by aabm00** [rwaldron/johnny-five#1112]
Hi.

I have an Arduino Yun taking data from 10 pressure sensors through analog pins every 30 seconds , and now I want to read motor consumption but the device uses the modbus protocol to transmit the information.

I am using now J5 and sockets to transmit the sensors information through node-serialport . 

I have read that to use the modbus I have to use a rs485 port so we have to add the IC MAX485. 
There are some implementations of the modbus for node (in npm) that uses node-serialport. 

So, Can I read simultaniously data from the sensors using J5 and the data consumption using modbus? 

I suposse that there should be a sketch with the modbus protocol in the arduino to work with, so then the firmata wouldn't be there, so I suposse I can't do both things using the same arduino. Am I right? 

Thanks

**Comment by jesus-acuna** [comment]
No, you can't. You can't run J5 and Modbus protocol at the same time. At least not with the available libraries. You would have to work the reading of the analog values with a simple Arduino Sketch, then use a Master Modbus sketch to read the data from the slave (the motor in your case)

**Comment by rwaldron** [comment]
> You can't run J5 and Modbus protocol at the same time. 

Sure you can, but the modbus protocol would be handled by some other program logic. Here's a hypothetical illustration (using https://www.npmjs.com/package/modbus-serial): 


```
npm install modbus-serial
```

```js
var Modbus = require("modbus-serial");
var five = require("johnny-five");
var board = new five.Board("/dev/ttyUSB0");

board.on("ready", function() {

  var pressureSensors = five.Sensor.Collection({
    pins: ["A0", "A1", "A2"] // ...and so on...
    period: 30000 // 30 second periods
  });

  pressureSensors.on("data", function(sensors) {
    var data = sensors.map(function(sensor) {
      return sensor.value;
    });

    console.log(data);
  });


  var modbus = new Modbus();

  modbus.connectRTU("/dev/ttyUSB1", {baudrate: 9600}, function() {
    // modbus.readHoldingRegisters
    // modbus.readInputRegisters
    // See docs: https://www.npmjs.com/package/modbus-serial
  });
});
```

**Comment by dtex** [comment]
This issue appears to have been answered so I'm going to close it. Feel free to re-open if necessary.
