### ISSUE TITLE
How To Stop HTU21D Read

### ISSUE THREAD

**Issue by reza70** [rwaldron/johnny-five#1115]
I have a problem using HTU21D .
I use Multi API for read HTU21D .
this is my code  :

``` js
var five = require("johnny-five");
var board = new five.Board();

board.on("ready", function() {



var multi = new five.Multi({
    controller: "HTU21D"
  });

if($incoming == 1)
{
  multi.on("change", function() {
    console.log("temperature");
    console.log("  celsius           : ", this.temperature.celsius);
    console.log("  fahrenheit        : ", this.temperature.fahrenheit);
    console.log("  kelvin            : ", this.temperature.kelvin);

    console.log("Hygrometer");
    console.log("  relative humidity : ", this.hygrometer.relativeHumidity);


  });
}
else
{
  multi.stop();
}

});
```

I want disconnect and stop HTU21D and destroy multi variable .
Can in do this ?
thank you

**Comment by rwaldron** [comment]
I've been planning for and am currently working on the lower level pieces that are necessary for supporting this capability. I should have something concrete to try out by mid week. 

In the meantime, it would be helpful to me to understand what exactly you're trying to accomplish? In the above program, it's unclear where the `$incoming` variable comes from, or why a non-truthy value would result in "stopping" the sensor. Once this code runs, nothing else will happen. The Board instance will keep its connection open until the program itself is closed.

**Comment by reza70** [comment]
Thank you .
I want read data from HTU21D and then close traffic tx  and then run Multi again other time .
I want this run every 1 minute .
Can i disconnect board ?

**Comment by reza70** [comment]
really i want use HTU21D and DS18B20 sensor together .
When use Multi and them use Thermometer in code i get error about 1-wire sensor .
so i want create Multi object and read temp and close that and then Create Thermometer object and read data and close that .
i want this process repeat every 1 minute .

**Comment by rwaldron** [comment]
What is the error you getting?

**Comment by reza70** [comment]
Error: 1-Wire device search timeout - are you running ConfigurableFirmata?
    at Timeout._onTimeout (/usr/lib/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:1376:14)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)


i use ConfigurableFirmata on arduino 
i think conflict address or any things .....

if comment five.Multi , all thing is ok .

i need destroy object and stop communicate between arduino and sensor and call five.Multi or five.Thermometer again

**Comment by rwaldron** [comment]
No, that's not the right way to fix this—there should be no conflict at all between the two components, as they're using entirely different protocols. If you see that error it's because the board doesn't have ConfigurableFirmata uploaded, or it does and the 1-wire feature is not enabled. Please make sure that 1-wire is enabled

**Comment by rwaldron** [comment]
@briangenisio do you know why 1-Wire would timeout, if the board has ConfigurableFirmata running?

**Comment by reza70** [comment]
i sure upload ConfigurableFirmata on arduono and enable 1 wire 
because when use only DS18B20 all thing work and no problem but when use DS18B20 and HTU21D together stop script and show me error

**Comment by rwaldron** [comment]
I'm going to try and reproduce, I just need to find my DS18B20 :\

**Comment by reza70** [comment]
OK
I found my problem but why ..... ?
I use 2 DS18B20 and connect to same digital port and use address for read data .
if use Multi for HTU21D and Thermometer for DS18B20 on this mode i get error .
but if use only DS18B20 and HTU21D i don't have problem .

while 1-wire function call and Multi in running i get error .

**Comment by BrianGenisio** [comment]
IIRC, we were getting that error when we had two MAX31850K units (very similar to the DS18B20) connected simultaneously.  The chip would error out, and the read command would time out, causing the error suggesting that OneWire wasn't installed.  But it was, and everything worked fine when there was one MAX31850K unit. 

I was never able to reproduce the issue, because I only ever had one unit.  But it is what caused this exit condition on that device:
https://github.com/rwaldron/johnny-five/blob/9e06037c1004adaf8c5ec59f597cb709d47b9977/lib/thermometer.js#L102

Not sure if that will help, but perhaps it is something similar?

Just looked at the HTU21D (reminded muself).  That's I2C, not one-wire.  Is it possible that I2C is causing a timing issue with OneWire?  Isn't OneWire timing-based?  Does this error happen immediately?  Or does it happen after a while?  Are the read requests happening at the same time?  I wonder if you can read them in serial... toggle between reading the DS18B20 and HTU21D?  Just a thought.

Hmpfh.  :shrug:

I'll see if I can find my HTU21D but it might be a day or two.

**Comment by rwaldron** [comment]
I can reproduce this issue as well. 

While I think these _should_ be able to function at the same time, I suspect there is lower level issue that's unrelated to Johnny-Five specifically. I'm going to try to prove/disprove that later today. In the meantime, I've put together a solution that meets the request in your comment here: 

> I want read data from HTU21D and then close traffic tx and then run Multi again other time .
> I want this run every 1 minute .

1. Set up a project directory: 
  ```
  mkdir temperature-process && cd temperature-process;
  npm init -y && npm install johnny-five && touch index.js && touch child.js
  ```

2. Fill in the two files: 
  - index.js
    ```js
    var cp = require("child_process");
    var avg = null;
    var mode = 0;
    var interval = 1000; // Change to 60000 for a minute

    function read() {
      cp.exec("node child " + mode, function(error, response) {
        response = +response;

        if (avg === null) {
          avg = response;
        }

        avg = (avg + response) / 2;

        console.log("%d: %d", mode, response);
        console.log("Avg. %d°C", avg.toFixed(2));

        if (++mode === 2) {
          mode = 0;
        }

        setTimeout(read, interval);
      });
    }

    read();
    ```

  - child.js
    ```js
    var five = require("johnny-five");
    var board = new five.Board({
      repl: false,
      debug: false,
    });
    var mode = process.argv[2];
    var configs = [
      { controller: "DS18B20", pin: 2 },
      { controller: "HTU21D" },
    ];

    if (mode === undefined) {
      mode = 0;
    }

    board.on("ready", function() {
      var temp = new five.Thermometer(configs[mode]);
      temp.on("data", function() {
        process.stdout.write(String(this.celsius));
        process.exit();
      });
    });
    ```

3. Run it!
  ```
  $ node index.js
  0: 22.1875
  Avg. 22.19°C
  1: 22.11
  Avg. 22.15°C
  0: 22.1875
  Avg. 22.17°C
  1: 22.35
  Avg. 22.26°C
  0: 22.25
  Avg. 22.25°C
  1: 22.38
  Avg. 22.32°C
  0: 22.1875
  Avg. 22.25°C
  1: 22.35
  Avg. 22.3°C
  ```

**Comment by rwaldron** [comment]
I just tried reading both with just an Arduino sketch and it works fine. Maybe @soundanalogous can help us understand the timing constraints (if any exist)

**Comment by jackrosenhauer** [comment]
Any progress on this? I just ran into this issue as well.

**Comment by soundanalogous** [comment]
One possibility is, depending on which board you are using, there is not enough memory remaining for stable operation once you enable both OneWire and I2C in ConfigurableFirmata. What board are you using and how much flash memory and SRAM is remaining after compile the firmware (ConfigurableFirmata) for that board? This will be printed in the bottom of the Arduino IDE.

**Comment by jackrosenhauer** [comment]
Sorry deleted my comment because I thought it was off topic but after a second look I'm using the same setup as @reza70. My board is a MEGA 2560 and I'm only using 1 DS18B20 and an HTU21D-F. The output after uploading: 
Sketch uses 26,658 bytes (10%) of program storage space. Maximum is 253,952 bytes.
Global variables use 3,072 bytes (37%) of dynamic memory, leaving 5,120 bytes for local variables. Maximum is 8,192 bytes.

**Comment by soundanalogous** [comment]
Ok memory is definitely not an issue then. Have you tried attaching the DS18B20 to different pins?

**Comment by soundanalogous** [comment]
Also try changing the sampling interval. It's 19ms by default. Try setting it to 100 or even 1000ms:

```js
var board = new five.Board({
  samplingInterval: 100,
});
```

That will change the rate at which the I2C devices will report their values if continuous reporting is enabled. It could be that the default of 19ms is too frequent when attempting to read from multiple devices.

**Comment by jackrosenhauer** [comment]
Mega uses pins 20 and 21 for i2c for the HTU21D and the DS18B20 is hooked up to pin 11. I tried pin 2-12 and did not seem to make a difference.

Here is my stack trace (pretty much the same as above):


events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: 1-Wire device read timeout - are you running ConfigurableFirmata?
    at Timeout._onTimeout (C:\git\raspberrypi\node_modules\firmata\lib\firmata.js:1460:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by jackrosenhauer** [comment]
Setting the samplingInterval to 1s yields the same results.

**Comment by soundanalogous** [comment]
And if you use only the HTU21D or only the DS18B20 everything works without issue, correct?

**Comment by jackrosenhauer** [comment]
Yes, using only one of the sensors works without issue.

**Comment by jackrosenhauer** [comment]
Also, setting samplingInterval to 1000ms does not seem to change the rate at which the values are being read.

**Comment by soundanalogous** [comment]
That's pointing to an issue in the default polling rate set in johnny-five then.

**Comment by soundanalogous** [comment]
I'd need to add logging in ConfigurableFirmata and report it back over Firmata sendString in order to gain an understanding of what is happening at the firmware level. I don't have these sensors so I'd have to walk you through the process of setting up debug messages.

**Comment by jackrosenhauer** [comment]
Tell me what to do. I'm trying to look into the issue as much as I can. It seems that the samplingInterval value is being set in board.io.settings but is being ignored.

**Comment by soundanalogous** [comment]
Are you using a version of ConfigurableFirmata built from firmatabuilder.com or just the default version you get from firmata/ConfigurableFirmata/examples/ConfigurableFirmata.ino?

**Comment by jackrosenhauer** [comment]
I've tried both and get the same result. Currently using firmata/ConfigurableFirmata/examples/ConfigurableFirmata.ino.

**Comment by soundanalogous** [comment]
Did you make any modifications?

**Comment by jackrosenhauer** [comment]
Nope.

**Comment by jackrosenhauer** [comment]
Just to be thorough I do get these 2 compile warnigns http://pastebin.com/NRQnCU9K

**Comment by soundanalogous** [comment]
Copy this to a new file and compile and upload: https://gist.github.com/soundanalogous/7e7643cd8cf00a5f90de615f5d52b9ec

Also make sure you have ConfigurableFirmata v2.9.1 installed.

**Comment by jackrosenhauer** [comment]
Seems to be outputting mostly gibberish besides the sketch name.

**Comment by soundanalogous** [comment]
Probably seeing ascii text. If converted to raw bytes that may be helpful info.

**Comment by soundanalogous** [comment]
Add this to the end of the setup function:

```c++
// set sampling interval to 1000ms
reporting.setSamplingInterval(1000);
```

**Comment by jackrosenhauer** [comment]
How do I get the raw bytes being sent?

**Comment by soundanalogous** [comment]
It depends on where the stream is coming from. Where is the gibberish data showing up? Is it part of the error stream or is it from console.log, etc?

**Comment by soundanalogous** [comment]
Also please share you full javascript code.

**Comment by jackrosenhauer** [comment]
I should just be able to open the serial monitor (COM) and see the output, right? 

code: https://gist.github.com/jackrosenhauer/b4452d2ffbf09409fc4add1ebb4c34e1

**Comment by soundanalogous** [comment]
You can try, but I don't think it will work because the serial monitor will own the connection and you won't be able to communicate with your J5 application.

**Comment by soundanalogous** [comment]
So you get no output when running that script?

**Comment by jackrosenhauer** [comment]
I don't get any additional output while running the J5 app

**Comment by soundanalogous** [comment]
Strange. Can you copy and paste the gibberish data. I can probably decipher it if it's ascii.

**Comment by jackrosenhauer** [comment]
The gibberish data is not in ascii and was from the serial monitor.

**Comment by soundanalogous** [comment]
Add this to your script inside the "ready" function block:

```js
board.on("string", function (message) {
  console.log(message);
});
```

**Comment by soundanalogous** [comment]
Then update ConfigurableFirmataDebug.ino with the following: https://gist.github.com/soundanalogous/7e7643cd8cf00a5f90de615f5d52b9ec.

Compile and upload then run your sensors.js. It should hopefully print "reporting..." once a second.

**Comment by jackrosenhauer** [comment]
It does indeed print reporting... every second but nothing else.

**Comment by soundanalogous** [comment]
That's good. It indicates the firmware isn't crashing. Getting more meaningful data will be difficult as it will require modification of the ConfigurableLibrary.

**Comment by soundanalogous** [comment]
Also, just to make sure everything else is working as intended with this firmware, comment out the `thermometer` and let me know if that prints data, then uncomment `thermometer` and comment out `hygrometer` and let me know if that prints data.

**Comment by jackrosenhauer** [comment]
Any variation prints "reporting..." but J5 exits on the 1-Wire device read timeout error.

**Comment by soundanalogous** [comment]
Go to your Arduino/libraries/ directory and make a copy of ConfigurableFirmata (as a backup) and move that copy out of the libraries directory. Then in the ConfigurableFirmata that remains in Arduino/libraries/, replace the existing /ConfigurableFirmata/src/OneWireFirmata.cpp with this version: https://gist.github.com/soundanalogous/b46593e9fa90ae5846146cc7e6253e16.

If you have the Arduino IDE open, you'll need to close then reopen it after updating that file. The compile and upload ConfigurableFirmataDebug.ino again and let me know what your script prints. It should print a few numbers periodically.

**Comment by jackrosenhauer** [comment]
output sample: https://gist.github.com/jackrosenhauer/ddbe376f2212751d86e05ca8e11abd3c

**Comment by soundanalogous** [comment]
Now replace ConfigurableFirmata/src/I2CFirmata.h with this file: https://gist.github.com/soundanalogous/af3eba67c19f29dd9a0a1ef5f4d42a31

**Comment by jackrosenhauer** [comment]
output#2 sample: https://gist.github.com/jackrosenhauer/1a7b96debcac9f69f7e542c7411b7708

**Comment by soundanalogous** [comment]
strange... seeing no strings from I2C, is both thermomenter and hydrometer uncommented?

**Comment by soundanalogous** [comment]
Also, here's another update to OneWireFirmata.cpp: https://gist.github.com/soundanalogous/b46593e9fa90ae5846146cc7e6253e16

**Comment by jackrosenhauer** [comment]
I had thermometer enabled and hygrometer disabled. hygrometer is now enabled, I've also updated the OneWireFirmata.cpp. 

Output:
I2C write
I2C read
I2C read
...

**Comment by soundanalogous** [comment]
That's all you get is those 3 lines now?

**Comment by jackrosenhauer** [comment]
No, it continues to output I2C read.

**Comment by soundanalogous** [comment]
but no more subcmd values?

**Comment by soundanalogous** [comment]
and are you seeing "I2C read" more frequently that you're seeing "reporting..."?

**Comment by jackrosenhauer** [comment]
With both sensors enabled and running this is the output https://gist.github.com/jackrosenhauer/1fe822d6bec89120fb347e292dc3d4d0

**Comment by soundanalogous** [comment]
When you shared output#2 sample, was the OneWire device reporting correct data as expected?

**Comment by jackrosenhauer** [comment]
I was not outputting sensor data to reduce noise. I can redo if you need

**Comment by soundanalogous** [comment]
yeah that would be helpful

**Comment by jackrosenhauer** [comment]
yes, it was accurate
output2#2: https://gist.github.com/jackrosenhauer/1b2eba23e159bbf079afe8d239a2596b

**Comment by soundanalogous** [comment]
Here's another update to OneWireFirmata.cpp: https://gist.github.com/soundanalogous/b46593e9fa90ae5846146cc7e6253e16. Please try that and enable both sensors. Also share an output stream with just the thermometer and just the hydrometer with that firmware.

**Comment by jackrosenhauer** [comment]
output for both: https://gist.github.com/jackrosenhauer/0e7cf244f0dee039549d56a330b6182a
thermometer: https://gist.github.com/jackrosenhauer/06d6dc8181b61036e492c08efa21aacc
hygrometer:https://gist.github.com/jackrosenhauer/fbd7d0d098f499ed8d033648fd0bda50

**Comment by soundanalogous** [comment]
So it looks like the thermometer is crashing even when the hygrometer is commented out.

**Comment by soundanalogous** [comment]
Try changing the frequency of the thermometer and hygrometer readings to 1 second (default is 100ms for DS18B20 and 20ms for Multi):

```js
var thermometer = new five.Thermometer({
      controller: "DS18B20",
      pin: 4,
      freq: 1000
});
var hygrometer = new five.Multi({
    controller: "HTU21D",
    freq: 1000
});
```

**Comment by jackrosenhauer** [comment]
The thermometer is no longer reporting sensor data...

**Comment by soundanalogous** [comment]
It is probably affected by delays caused by all of those delay strings, but it's interesting in that causes a crash in the same way as when both devices are enabled simultaneously.

**Comment by soundanalogous** [comment]
Swap the original version of ConfigurableFirmata back in and run with your script with the longer frequencies. I'm curious if the 20ms default freq of the five.Multi object is what is causing the crash. That's way too frequent to read an I2C device while simultaneously reading a OneWire device, especially since on each write call to OneWire global interrupts are disabled on the board, which is going to mess with I2C behavior.

**Comment by soundanalogous** [comment]
by original version of ConfigurableFirmata, I mean the library in Arduino/libraries/ not the sketch.

**Comment by soundanalogous** [comment]
I think in order to get multi-sensor that use a mix of interfaces (I2C and OneWire) in this case, Firmata is going to need a task manager.

**Comment by soundanalogous** [comment]
or some sort of a queue

**Comment by jackrosenhauer** [comment]
same results, any idea of a temp work around?...

**Comment by soundanalogous** [comment]
so with original ConfigurableFirmata library and longer frequencies, you still get the crash?

**Comment by jackrosenhauer** [comment]
That is correct.

**Comment by soundanalogous** [comment]
Based on the data we've gathered I'm unfortunately still not sure if the error is on the firmware side, or if it's in firmata.js or in johnny-five. Based on the [samples#2 -- both](https://gist.github.com/jackrosenhauer/0e7cf244f0dee039549d56a330b6182a) data, here's what I know:

- a OneWire read request fails mid read (line 17). However "reporting..." is still printed every second so the firmware hasn't locked up.
- johnny-five is controlling the polling frequency so the Firmata `samplingInterval` is irrelevant in this case.
- even with a lower polling frequency (1000ms) there is still a conflict and no data is returned, indicating the issue isn't caused by flooding the stream.

What could be happening?

**Hypothesis A**: Somewhere shortly after "read request bit" is printed, data gets in a bad state in OneWireFirmata that somehow also puts I2C in a bad state (perhaps OneWire gets stuck with the global interrupt still in the disabled state), but the firmware application itself does not completely crash and firmata.js/johnny-five keeps processing input correctly (printing: "reporting...").

**Hypothesis B**: Expected data is not returned in firmata.js or johnny-five and one of those libraries stop requesting I2C and OneWire data.

In order to make further progress I'd need the actual hardware to repro this condition as it will require much more extensive logging both in the firmware and in firmata.js and johnny-five.js.

@rwaldron FYI. Can you look into Hypothesis B on the johnny-five side. Is there an unhandled case that would break the frequency interval in the Multi or Thermometer modules?

**Comment by soundanalogous** [comment]
@jackrosenhauer one more thing to add to your script is blink the on-board LED once a second. That will indicate if the firmware is still responsive even if the client application appears to have crashed. Of course it will stop when the error is thrown by J5.

**Comment by jackrosenhauer** [comment]
LED blinks until J5 crashes

**Comment by soundanalogous** [comment]
One more update to OneWireFirmata.cpp that adds a couple more debug statements: https://gist.github.com/soundanalogous/b46593e9fa90ae5846146cc7e6253e16. @jackrosenhauer if you could please try this and output the log with both sensors enabled. Thanks!

**Comment by jackrosenhauer** [comment]
output: https://gist.github.com/jackrosenhauer/f2b96adee530c9aea9d90c5a90b3cff0
code: https://gist.github.com/jackrosenhauer/c02cb82890ea66f595bfecfd8d0f7377
led continues to blink

**Comment by jackrosenhauer** [comment]
No change.

**Comment by soundanalogous** [comment]
Ok then I really think the issue must lie in the Multi object.

@rwaldron

**Comment by soundanalogous** [comment]
@jackrosenhauer do you have a 4.7k resistor connected to the data line of the temp sensor?

**Comment by jackrosenhauer** [comment]
Yes, there is a 4.7k resistor connected

**Comment by soundanalogous** [comment]
And when you say "no change", are you using the original ConfigurableFirmata library or the modified version?

**Comment by jackrosenhauer** [comment]
While using both versions, the 1-Wire timeout still happens.

**Comment by soundanalogous** [comment]
In firmata.js try changing the timeout on lines 1382 and 1404 to 10000 or higher

**Comment by rwaldron** [comment]
@soundanalogous I will read through this thread and follow up as soon as I can

**Comment by jackrosenhauer** [comment]
Changed timeouts on lines 1382, 1404 and 1462. Same results.

**Comment by ruswerner** [comment]
I'm also getting this same error `1-Wire device read timeout`. However I'm using 3 DS18B20's on 2 different pins (6 total sensors), with a 5 sec polling frequency. The J5 app will run happily for a random amount of time, but usually it doesn't go more than 24 hours before crashing with:

```events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: 1-Wire device read timeout - are you running ConfigurableFirmata?
    at Error (native)
    at null._onTimeout (/tmp/remote-script/node_modules/firmata/lib/firmata.js:1:12227)
    at Timer.listOnTimeout (timers.js:92:15)
```

I'm about to give up and switch over to a Particle Photon to get this project finished, I just can't get J5+ConfigurableFirmata to be stable reading temps...

Hopefully my setup will shed some light on this problem. Let me know if you need something from me.

**Comment by soundanalogous** [comment]
Sounds like a potential memory leak in ConfigurableFirmata when using multiple OneWire devices. Are you able to determine if the ConfigurableFirmata is locking up after 24 hours or so?

**Comment by ruswerner** [comment]
@soundanalogous After this above read timeout error, if I re-run the J5 program, this is what happens:

```1500926295073 Connected /dev/ttyACM0  
1500926355153 Device or Firmware Error A timeout occurred while connecting to the Board. 

Please check that you've properly flashed the board with the correct firmware.
See: https://github.com/rwaldron/johnny-five/wiki/Getting-Started#trouble-shooting

If connecting to a Leonardo or Leonardo clone, press the 'Reset' button on the board, wait approximately 11 seconds for complete reset, then run your program again.  
```

And it will keep doing this ^ until I **hard-power off** the Arduino and the host computer (a Tesssel 2 in this case). Just pressing reset on the Arduino doesn't work.

It seems to me, not having much knowledge of how firmata works, is that the delicate 1-wire protocol gets slightly behind/out-of-sync and then bails, leaving the arduino in an unrecoverable state. There's either a bug in how 1-wire is implemented or a better way to recover from errors like this.

I'm happy to help diagnose this further...

**Comment by soundanalogous** [comment]
I can't look into this with real hardware until early August so anything you can try in the meantime will be helpful. I don't have a Tessel 2 so I can't help diagnose on that end.

Which Arduino board are you running Firmata on?

**Comment by ruswerner** [comment]
No worries. I'm using an official Arduino UNO R3. I can do some more testing once I have it swapped out of active service heating my home (when it's not crashed) ;P

**Comment by soundanalogous** [comment]
Please try the following:
1. Install the [ArduinoUnit library](https://github.com/mmurdoch/arduinounit) (you need this for a dependency it includes).
2. Include ArduinoUnit in your ConfigurableFirmata file:
```c++
#include <ArduinoUnit.h>
```
3. Add these 2 lines near near the top of your ConfigurableFirmata.ino file where other variables are declared:
```c++
long memCheckCounter = 0;
char buffer[20];
```
4. Add these lines at the end of the `loop()` function:
```c++
// send memory reading approximately ever 10 seconds
// 526 * 19 (default sampling interval) = 9994 ms
// increase 526 for long running processes
if (memCheckCounter++ == 526) {
   sprintf(buffer, "%u", freeMemory());
   Firmata.sendString(buffer);
   memCheckCounter = 0;
}
```
5. Add this line in your JavaScript file:
```js
board.on("string", function (message) {
  console.log("available memory: " + message);
});
```

That will log the amount of available memory on the Arduino every 10 seconds (see comments for how to extend the reporting period) . Let me know if you see the memory value increase over time.

**Comment by ruswerner** [comment]
@soundanalogous Thanks. I'll get to this as soon as I can. I've had to decommission my hardware setup and switch to something more reliable, a Particle Photon,  for heating our home. Now that the tessel and arduino are back on the bench, I can setup a safe debug env for this.

**Comment by lfnoleto** [comment]
what it would be like to get humidity and temperature every 20 minutes? @rwaldron
