### ISSUE TITLE
Accelerometer: update fixed point values to match datasheets for fractional digit accuracy 

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#1117]
To better understand what needs to be done here, take a look at this example from the `Thermometer` class: 
- https://github.com/rwaldron/johnny-five/blob/master/lib/thermometer.js#L480-L499

And the corresponding tests: 
- https://github.com/rwaldron/johnny-five/blob/master/test/thermometer.js#L692

Use the `digits.fractional(value)` function to get the number of fractional digits in a given value.

**Comment by rwaldron** [comment]
Sorry for the confusion here, I filed this from a mobile device and I fat fingered a few incorrect labels.

**Comment by faraazahmad** [comment]
the tests should be in https://github.com/rwaldron/johnny-five/blob/master/test/accelrometer.js right?

**Comment by rwaldron** [comment]
@faraazahmad yes, this is an on going process.

**Comment by dnlup** [comment]
@rwaldron Hi, I would like to try to work on this one.
Need to ask you some things before:
*   the method in `accelerometer.js` you need to be fixed is `toGravity`
*   you want the decimals to be fixed as the resolution reported in each device datasheet
*   where should I implement test case in `test/accelerometer.js`? Looking through `test/thermometer.js` I find the `digital.fractional()` test called in different methods, you want to use a custom function or should I use a specific existing one for the accelerometer?

Sorry if the questions could be obvious.

Thanks.

**Comment by rwaldron** [comment]
- Yes, each occurrence
- Yes, exactly :)
- ~~Striken~~
- Yes, I believe that would be correct :)
