### ISSUE TITLE
J5 in Raspberry Pi 3

### ISSUE THREAD

**Issue by rudemex** [rwaldron/johnny-five#1127]
I have installed in the Raspberry Pi 3 node js v4.4.4 but I can not operate the blink on the LED .
J5 works with these versions ?

Thanks!

**Comment by rwaldron** [comment]
Are you using Raspi-io?

cc @nebrius

**Comment by nebrius** [comment]
Assuming you're using Raspi IO, AFAIK it works? Do you get an error message? Can you post some code to reproduce the issue?

**Comment by rudemex** [comment]
sorry... work! i need install another plugs. jejejeje

thanks!
