### ISSUE TITLE
Proximity HCSR04 limited to Arduino (not working on Raspberry)

### ISSUE THREAD

**Issue by hphde** [rwaldron/johnny-five#1134]
I am using Johnny-Five under Node-Red on an Raspberry Pi2. Since I love using J5 I failed using the Proximity module because it's currently limited to an Arduino.

Would be great to have this on the Pi.

**Comment by alexcroox** [comment]
I'm going to try https://github.com/clebert/r-pi-usonic and let you know if it works

**Comment by alexcroox** [comment]
No joy with the Pi2 :(

**Comment by rwaldron** [comment]
Thanks for filing an issue :)

Please follow progress for HCSR04 support here: https://github.com/nebrius/raspi-io/pull/55
