### ISSUE TITLE
Johnny five with distance sensor

### ISSUE THREAD

**Issue by sharkee89** [rwaldron/johnny-five#1143]
Hi,

Sorry to bother you this but I didn't find the contact form on johnny five site. Is there a part of johnny five library that works UV distance sensor, for example, some sensor like this http://www.amazon.com/Ultrasonic-Module-HC-SR04-Distance-Arduino/dp/B004U8TOE6?tag=thirdwish-20

Sorry for asking this type of question here if it is not appropriate please can you point me to some place where I can find the answer.

**Comment by rwaldron** [comment]
No problem! You're looking for these: 

- http://johnny-five.io/examples/proximity-hcsr04/
- http://johnny-five.io/examples/proximity-hcsr04-i2c/

Anyone is welcome to file any issues, for any reason—someone is always around to help :) you can/should also join us in https://gitter.im/rwaldron/johnny-five
