### ISSUE TITLE
Failure to fully turn off RGB Led strip on exit event

### ISSUE THREAD

**Issue by JvanderHeide** [rwaldron/johnny-five#1158]
**Board:** Arduino Uno
**Shield:** n/a
**Hardware you are having an issue with:** RGB led strip
**Version of Johnny-Five:** 0.9.56
**What your expectations are:** 
I expect that calling ``ledRGB.off()`` will turn off the entire RGB led strip when called in an `exit` event handler.
**What the actual outcome is:**
Only the red pin is switched off, green and blue are still on. 
**Steps to reproduce (including code samples):**
I'm trying to reset my board to its original state by using the following script:
```javascript
board.on('ready', function(){	 

  var ledRGB = new five.Led.RGB([ 9, 10, 11 ]);
  ledRGB.color('white'); 

  this.repl.inject({
    ledRGB: ledRGB
  });

  this.on('exit', function() {
    ledRGB.off();
  });

});
```

When I then proceed to exit via ``^C^C`` or ``.exit``, only pin 9 turns off. Leaving the strip turned on at a blue/green color. 

If I call ``ledRGB.off()`` from REPL everything works as expected.

I'm guessing that there's not enough time after the exit event is fired for Johnny Five to turn off all the pins before the connection is closed or is something else going on? 

Currently I'm restarting the script once and then quickly ``^C``-ing to reset the board, but I'd love to be able to do it automatically.

**Comment by rwaldron** [comment]
Thanks for the report! I'll try to take a look at this today

**Comment by JvanderHeide** [comment]
@rwaldron I was wondering if you've had the time to take a look at this issue. I understand if you weren't able to. If you have any pointers on resetting the board in any other way that'd be great.

Thank you very much for your work on Johnny-Five!

**Comment by rwaldron** [comment]
@JvanderHeide sorry, I've been swamped working on this: https://learn.sparkfun.com/tutorials/experiment-guide-for-the-johnny-five-inventors-kit which just launched today. 

Can you link me to the actual component you're using, described above as "RGB led strip"? Thanks!!

**Comment by JvanderHeide** [comment]
Sweet! Looks like a great kit. 

---

If I recall correctly it's [this one](http://www.ledstripkoning.nl/led-strips-rgb/losse-ledstrips-rgb/5-meter-150-leds-rgb-led-strip/). The page is in Dutch however. I'm powering it with a separate 12V transformator. Like this (although I have switched the R and B around (R=9,G=10,B=11)): 

![Image of the connections](http://i.imgur.com/dnJmBNq.png)

It works like a charm, with the exception of only the red pin turning off when calling `.off()` at an exit event.

**Comment by rwaldron** [comment]
TBH, I suspect the issue isn't a software related one, because all the rgb instance is doing in off() is zeroing the PWM signal. If the red channel is staying on it may be that some power source is causing that? I will have to locate the same or similar components and then try to reproduce

**Comment by rwaldron** [comment]
Do you think this is suitable: https://www.amazon.com/uxcell®-Package-L7812CV-Positive-Regulators/dp/B00CMQ4O8Y ?

**Comment by JvanderHeide** [comment]
@rwaldron there's no power from the Arduino going to the led strip, the MOSFETs are only controlling the ground. And Red is turning off (the first pin of the rgb configuration), hence my assumption that there's not enough time for the other two pins two be shut down in an exit event. 

.off() works perfectly fine from repl or in any code but the exit event.

**Comment by JvanderHeide** [comment]
Just tried without any components, just measuring the pins using my multimeter, and pins 10 and 11 kept giving their voltage at the moment of exit. Only pin 9 got set to zero volts.

**Comment by rwaldron** [comment]
Ok, that's very helpful. I believe you're exactly right w/r to "not enough time". Try this: 


```js
// Anywhere inside your board's ready event handler: 
this.repl.inject({
  // Make an accessor named "q"
  get q() {
    rgb.off();
    process.nextTick(() => process.exit());
  }
});
```

I didn't test this exact code, but I've used this same mechanism before. Now you can type `q` + `<enter>` to "clean up" and exit.

**Comment by JvanderHeide** [comment]
Thank you!  This works and will do 👍 

Had to rename my ledRGB in the repl, so that it didn't match the global ledRGB (thus no `ledRGB: ledRGB`) and had to add a `setTimeout` of a few ms around the `process.nextTick(() => process.exit());` (timeouts didn't work with the exit event handler).

**Comment by rwaldron** [comment]
Nice! I'm glad we could resolve this :)
