### ISSUE TITLE
pingRead() not available on IntelEdison

### ISSUE THREAD

**Issue by jerwallace** [rwaldron/johnny-five#1160]
The pingRead() method is not available when using an Intel Edison. 

`Object #<Galileo> has no method 'pingRead'`

**Comment by wicktus** [comment]
http://johnny-five.io/platform-support/#intel-edison-arduino

As you can see ping is not supported by the edison ;).

**Comment by rwaldron** [comment]
Thanks for the report! As @wicktus noted, there is no support for the `pingRead` method on Intel Edison—nor can there be, as it's timing requirements cannot be met.

**Comment by rwaldron** [comment]
If you can, I recommend using the "backpack" approach: http://johnny-five.io/examples/proximity-hcsr04-i2c/
