### ISSUE TITLE
WEBSITE: add Genuino in supported platform list ?

### ISSUE THREAD

**Issue by kosamari** [rwaldron/johnny-five#1162]
[ not sure if this is a good place to ask about... `http://johnny-five.io/` if not let me know where to move this convo :) ]

This is more of editorial suggestion!
I'd like to suggest listing Genuino in `http://johnny-five.io/platform-support/` along side Arduino.

I was just talking to people wroking on J5 workshop in Japan & noticed they do not refer the board itself as Arduino since product name outside of USA is Genuino.
Given this dual name situation is going on for a while, I think it is entirely possible that there are people who do not know board called Arduino exists, especially people who is getting started now (and have not followed entire drama.)

Proposed Change: 
![javascript_robotics_platform_support__johnny-five_](https://cloud.githubusercontent.com/assets/4581495/16324460/a54ac4d4-3982-11e6-94ce-2a2027eb688e.png)

Just a suggestion :)

**Comment by henricavalcante** [comment]
I think it's a good catch ;)

**Comment by rwaldron** [comment]
Can you make a PR: https://github.com/johnny-five-io/johnny-five.io/blob/master/src/platforms-plugins.json

Thanks!

**Comment by kosamari** [comment]
awesome will do ! thanks @rwaldron
