### ISSUE TITLE
Docs: ESC definition

### ISSUE THREAD

**Issue by lyzadanger** [rwaldron/johnny-five#1168]
Trivial, but could trip up a beginner: The ESC docs (http://johnny-five.io/api/esc/) don't ever define what ESC is (like, stands for or does). Could be accomplished in a sentence or two. Happy to help if you like!

**Comment by scottgonzalez** [comment]
Sounds like a good idea. You can just edit the wiki: https://github.com/rwaldron/johnny-five/wiki/ESC and the site will get updated from there.

**Comment by rwaldron** [comment]
^^ :D

**Comment by lyzadanger** [comment]
All righty! I added a tiny edit, basically just expanding the acronym. :)

**Comment by rwaldron** [comment]
Awesome, thanks!
