### ISSUE TITLE
Arduino simulator

### ISSUE THREAD

**Issue by lucked** [rwaldron/johnny-five#1180]
is possible make a arduino simulator with johnny five?
get state of pins  write on pin but all fake

**Comment by dtex** [comment]
So something like [Tinker](https://docs.particle.io/guide/getting-started/tinker/core/) but for Arduino. I haven't seen anything like that but it might exist. If anybody wanted to create one, I would think an io-plugin would be the way to do it and there is a starter at https://github.com/achingbrain/board-io

**Comment by soundanalogous** [comment]
If any of these will bridge system serial they may work: http://www.smashingrobotics.com/arduino-simulators-lineup-start-developing-without-real-board/
