### ISSUE TITLE
`Piezo#play` mutates input array.

### ISSUE THREAD

**Issue by rhys-vdw** [rwaldron/johnny-five#1186]
The following code will only play a song once:

```js
const tune = {
  song: [['A4', 1], ['B4', 1]],
  tempo: 120
};

board.on('ready', () => {
    var piezo = new five.Piezo(3);
    setInterval(() => piezo.play(tune), 500);
});
```

Problem is that `Piezo#play` uses the input array as a queue.

Takes array [here](https://github.com/rwaldron/johnny-five/blob/642db0416143484655f33011576a23c819e9f45d/lib/piezo.js#L454) without copy. Then it pops off values [here](https://github.com/rwaldron/johnny-five/blob/642db0416143484655f33011576a23c819e9f45d/lib/piezo.js#L468).

Happy to contribute a PR to fix or document this. It's totally unnecessary as a for loop could be used.

**Comment by rwaldron** [comment]
I'd say take crack at fixing it—I think that would be fairly straight forward, right? Be sure to update tests and add new as needed. Ping me here if you have any questions
