### ISSUE TITLE
how change Grove lcd backlight color

### ISSUE THREAD

**Issue by chaos39** [rwaldron/johnny-five#1193]
Hi Guys, I like to know how do I change the color of the lcd 
Example: if the temperature senses the temperature is more than 30 degree the lcd will display red color, cold will be blue and warm will be some other color.

This is the code that I am currently doing. Thanks !

var five = require("johnny-five");
var Edison = require("edison-io");
var board = new five.Board({
  io: new Edison()
});

board.on("ready", function() {
var lcd = new five.LCD({
    controller: "JHD1313M1"
  });
  var led = new five.Led(4);
  var led1 = new five.Led(8);
  var temperature = new five.Thermometer({
    controller: "GROVE",
    pin: "A3",
    freq: 1000
  });

   var c = 0;

  temperature.on("data", function() {
    c = Math.round(this.celsius);
    if ( c >=30 ){
    led.on();
    led1.off();
   lcd.cursor(0, 6).print("HOT");
  } else if ( c <=20){
   led.off();
   led1.on();
  lcd.cursor(0, 6).print("Cold");
  } else {
   led.off();
   led1.off();
  lcd.cursor(0, 6).print("Warm");
  }
  lcd.cursor(0,0).print(c+"*c");
  });
});

**Comment by rwaldron** [comment]
You're looking for the `bgColor` method, as shown [here](http://johnny-five.io/examples/grove-lcd-rgb-temperature-display-edison/). Looks like it was missing docs on [LCD](http://johnny-five.io/api/lcd/), but I've just added them.
