### ISSUE TITLE
Change the color of grove lcd backlight

### ISSUE THREAD

**Issue by chaos39** [rwaldron/johnny-five#1195]
Hi Guys, I would like to know how to change the color of the LCD to yellow color or even purple color. Thanks !

**Comment by rwaldron** [comment]
Here's the API docs: http://johnny-five.io/api/lcd/#bgcolorcolor but to get you started...

```js
var lcd = new five.LCD({
  controller: "JHD1313M1"
});

lcd.bgColor("yellow");
// or...
lcd.bgColor("purple");
```
