### ISSUE TITLE
Board : BeagleBone Black - Trouble : Build/Install errors

### ISSUE THREAD

**Issue by hadrien-toma** [rwaldron/johnny-five#1201]
**I have simply done the following actions, in the order given. I will explain in detail all steps because it gives an MCVE (Minimal, Complete, and Verifiable Example) :**
1. On my Linux desktop, in order to put the image (downloaded from the [official website](https://debian.beagleboard.org/images/bone-debian-8.4-lxqt-4gb-armhf-2016-05-13-4gb.img.xz)) on my SD card : 
   `xzcat bone-debian-8.4-lxqt-4gb-armhf-2016-05-13-4gb.img.xz | sudo dd of=/dev/mmcblk0`
   `sudo sync`
2. On the first boot of my BeagleBone Black, resizing partition :
   `sudo fdisk /dev/mmcblk0`
   `d`
   `2`
   `n`
   `p`
   `2`
   ` `
   ` `
   `w`
   `sudo shutdown -r now`
   `sudo resize2fs /dev/mmcblk0p2`
   `sudo shutdown -r now`
3. Updating / Upgrading
   `sudo apt-get update`
   `sudo apt-get upgrade`
4. Updating to Node.js 4.x (as proposed [here](http://johnny-five.io/#hello-world)) :
   `sudo su`
   `curl -sL https://deb.nodesource.com/setup_4.x | bash -`
   `apt-get install -y nodejs`
   `exit`
5. Installing Johnny-Five in a development directory : 
   `sudo su`
   `cd /var/lib/cloud9`
   `mkdir elec`
   `cd elec`
   `npm install johnny-five`

**Some notes on these steps :**
- On point 1 : I also tried with this image : bone-debian-7.11-lxde-4gb-armhf-2016-06-15-4gb.img.xz but it fails in the same way.
- On point 4 : I also tried with Node.js v0.12, v5.x and v6.x, but they fail in the same way.

**What I receive from point 5 :**
[npm_i_j5.txt](https://github.com/rwaldron/johnny-five/files/423640/npm_i_j5.txt)

**Moreover, when I go to node_modules, this is what `ls` gives me :**
`accepts              debug                 johnny-five        repl
after                depd                  json3              request
ansi-regex           destroy               lodash.clonedeep   send
ansi-styles          ease-component        lodash.debounce    serialport
arraybuffer.slice    ee-first              media-typer        serve-static
async                engine.io             merge-descriptors  sf
base64-arraybuffer   engine.io-client      methods            socket.io
base64id             engine.io-parser      mime               socket.io-adapter
benchmark            es6-shim              mime-db            socket.io-client
better-assert        escape-html           mime-types         socket.io-parser
bindings             escape-string-regexp  ms                 stack-trace
blob                 etag                  nanotimer          strip-ansi
browser-serialport   express               negotiator         supports-color
callsite             eyes                  object-component   systemd
chalk                finalhandler          object-keys        temporal
coffee-script        forwarded             on-finished        tinycolor
color-convert        fresh                 optimist           to-array
colors               global                options            type-is
commander            has-ansi              parsejson          ultron
component-bind       has-binary            parseqs            underscore
component-emitter    has-binary-data       parseuri           utf8
component-inherit    has-cors              parseurl           utils-merge
content-disposition  i2c                   path-to-regexp     vary
cookie               i2c-bus               pkginfo            winston
cookie-signature     indexof               proxy-addr         wordwrap
crc                  ipaddr.js             qs                 ws
cycle                isarray               range-parser       xmlhttprequest`

**That is why I am wondering... is my install correct? The fact is that after, when I try to do :**
`npm install beaglebone-io`
**It fails like described [here](https://github.com/julianduque/beaglebone-io/issues/25#issuecomment-240524997) and bring me to not be able to use Johnny-Five and that, from what I have read, is really sad because this project seems really promising and I am really enthusiastic to use it, promote it, contribute to it! Can someone help me?**

**Comment by rwaldron** [comment]
@hadrien-toma sorry for the delay in responding

> What I receive from point 5 : npm_i_j5.txt

That looks correct to me.


This, from the bug you linked to: 

> worked without error, which installs ffi 2.0.0. Seems like beaglebone-io tries to use ffi 1.2.6

Needs to be addressed in beaglebone-io, let's ping @julianduque for help on that
