### ISSUE TITLE
Add `five.fn` documentation

### ISSUE THREAD

**Issue by balda** [rwaldron/johnny-five#1214]
I can't find `five.fn` documentation. Maybe an entry in http://johnny-five.io/api/ can be added?

The only doc seems to be in some examples and from source https://github.com/rwaldron/johnny-five/blob/master/lib/fn.js

**Comment by rwaldron** [comment]
Yes, this should be written

**Comment by lyzadanger** [comment]
@rwaldron I could take this on if you like.

**Comment by rwaldron** [comment]
@lyzadanger Yes please!

**Comment by lyzadanger** [comment]
WIP! https://github.com/rwaldron/johnny-five/wiki/Fn

**Comment by rwaldron** [comment]
Nice
