### ISSUE TITLE
DHT21 Support ?

### ISSUE THREAD

**Issue by gedeagas** [rwaldron/johnny-five#1216]
Hi, i was wondering if the DHT21 Humidity sensor will be supported anytime soon?
or this is something that impossible because of firmata limitation ?

**Comment by rwaldron** [comment]
It could be supported, in the same way shown: 

- https://github.com/rwaldron/johnny-five/issues/1213#issuecomment-244423615
- http://johnny-five.io/examples/temperature-DHT11_I2C_NANO_BACKPACK/

**Comment by rwaldron** [comment]
I've just ordered one of these and will report back when it's arrived and I have a chance to work with it

**Comment by gedeagas** [comment]
Sweet. 
in meantime i will report back if my DHT21 works

**Comment by rwaldron** [comment]
Looks like my sensor was delivered, but I'm out of town until tomorrow night so I'll be able to look at this on Monday. Again, I will continue to keep you posted 😀

**Comment by rwaldron** [comment]
What's wrong issue, I confused this with the DHT22 issue

**Comment by rwaldron** [comment]
Ok, to clear this up: according to amazon I did order this sensor, but I have no idea where it actually is. I've ordered another just now

**Comment by gedeagas** [comment]
Okay, i think i can test it out in the next few days
will update soon
