### ISSUE TITLE
Multi arduino issue

### ISSUE THREAD

**Issue by drj-io** [rwaldron/johnny-five#1220]
### Board: 
2x Arduino Mega boards
### Shield:
Spark fun big easy driver
https://www.sparkfun.com/products/12859

### Hardware you are having an issue with: 
Steppers

### Version of Johnny-Five: 
Tested with 0.10.0

### What your expectations are: 
Trying to use 2 different boards with Johnny Five, but it always uses the same board.

### What the actual outcome is: 
It always uses the same board, usually the first one that was plugged in.

Steps to reproduce (including code samples):
```javascript
var serialport = require('serialport');
var five = require('johnny-five');

serialport.list(function(err,ports){
    var connected_boards = [];
    console.log(ports);
   var ii = 0;
    ports.forEach(function(port,i){
      ii++;
      if(port.manufacturer == 'Arduino (www.arduino.cc)'){
        connected_boards.push({id: "a"+ii, repl:false});
      }
    });
    var boards = new five.Boards(connected_boards);
    boards.on("ready", function() {
      this.each(function(board){
        console.log("-->",board.io.firmware.name)

        if(board.io.firmware.name=="blue.ino"){
          var stepper = new five.Stepper({
            type: five.Stepper.TYPE.DRIVER,
            stepsPerRev: 3200,
            pins: [23,22]
          });
          stepper.rpm(180).ccw().step(6200, function(){
            console.log("ok, turned the knob on ", board.io.firmware.name,"arduino")
          });
        }
      })
    });
  })
```

Using this code, I have 2 arduino's attached (firmware "blue.no" and "red.ino" respectively).  When I run it the first time "red.ino" turns the stepper attached to it.  If I change "blue.ino" to "red.ino", red.ino turns the stepper on the same port.

I can get this to flip by unplugging both devices and plugging them back in in a different order.

arduino with "blue.ino" firmware
![img_2980](https://cloud.githubusercontent.com/assets/444485/18419998/38adc0e2-7825-11e6-9465-e6f2bc4a216d.JPG)

arduino with "red.ino" firmware
![img_2976](https://cloud.githubusercontent.com/assets/444485/18420001/3f57bd9e-7825-11e6-8a7f-13734a875161.JPG)

 Output:
```
> node app2.js
[ { comName: '/dev/cu.Bluetooth-Incoming-Port',
    manufacturer: undefined,
    serialNumber: undefined,
    pnpId: undefined,
    locationId: undefined,
    vendorId: undefined,
    productId: undefined },
  { comName: '/dev/cu.DavidsiPhone-WirelessiAP',
    manufacturer: undefined,
    serialNumber: undefined,
    pnpId: undefined,
    locationId: undefined,
    vendorId: undefined,
    productId: undefined },
  { comName: '/dev/cu.usbmodem1411',
    manufacturer: 'Arduino (www.arduino.cc)',
    serialNumber: '75533343336351407141',
    pnpId: undefined,
    locationId: '0x14100000',
    vendorId: '0x2341',
    productId: '0x0042' },
  { comName: '/dev/cu.usbmodem1421',
    manufacturer: 'Arduino (www.arduino.cc)',
    serialNumber: '95335343036351304162',
    pnpId: undefined,
    locationId: '0x14200000',
    vendorId: '0x2341',
    productId: '0x0042' } ]
1473621527904 Device(s) /dev/cu.usbmodem1411,/dev/cu.usbmodem1421
1473621527915 Connected /dev/cu.usbmodem1411
1473621527916 Device(s) /dev/cu.usbmodem1421
1473621527917 Connected /dev/cu.usbmodem1421
1473621530609 Board ID:  a3
1473621530609 Board ID:  a4
--> blue.ino
--> red.ino
ok
```

**Comment by rwaldron** [comment]
All component instantistions must have the `board` property explicitly set:

```Js   
         var stepper = new five.Stepper({
            board: board, // <--- as named in your code above 
            type: five.Stepper.TYPE.DRIVER,
            stepsPerRev: 3200,
            pins: [23,22]
          });
``` 

... Otherwise J5 defaults to the first board created and stored in its internal cache. This is only necessary when using multiple boards.

**Comment by drj-io** [comment]
Easy thanks!

**Comment by rwaldron** [comment]
No problem! :)
