### ISSUE TITLE
Possible to use Proximity - HC-SR04 in intel edison using node js ?

### ISSUE THREAD

**Issue by chaos39** [rwaldron/johnny-five#1223]
Hi guys, I would like to check if it is Proximity HC-SR04 in intel Edison running node js ? I am now currently using intel Edison Arduino board. I did try it out but I keep getting error on no such method 'Ping read or pin read
Thanks '

**Comment by chaos39** [comment]
What if I used sparkfun arduino block to program Proximity - HC-SR04 will that help ?

**Comment by rwaldron** [comment]
There is a similar issue filed here: https://github.com/rwaldron/galileo-io/issues/55 Thanks!
