### ISSUE TITLE
DC Current Sensor (INA219)

### ISSUE THREAD

**Issue by andy7love** [rwaldron/johnny-five#1227]
There is something to read from INA219 ?
https://www.adafruit.com/product/904

May be another DC current sensor ? 

Otherwise I can try to create it and collaborate, but it should be great to not start from scratch.
Thanks!

**Comment by rwaldron** [comment]
For something like this, if it were me, I would make a j5 plugin. Examples:


- https://github.com/rwaldron/j5-rc-receiver
- https://github.com/rwaldron/j5-sparkfun-weather-shield
- https://github.com/rwaldron/j5-ds-touch

**Comment by andy7love** [comment]
Ok thanks! I'll give it a try!

**Comment by rwaldron** [comment]
Join us in https://gitter.im/rwaldron/johnny-five if you have any questions :)
