### ISSUE TITLE
J5 resets arduino state/output pins when it starts

### ISSUE THREAD

**Issue by drj-io** [rwaldron/johnny-five#1230]
Every time J5 starts, it resets all my relays, turns them all off then on. Is there any way to prevent this?

Can j5/firmata just leave the existing state of all outputs the way they are?  I'm using j5 on several projects and this is undesirable.  

edge case: when I come back to my car, all of my windows are rolled down if the host gets rebooted.  This creates a security concern, of sorts. ;) 

This might be a feature request, or at least a support request.  Thanks a lot for your help.

**Comment by sumarouno** [comment]
If we are using Arduino native code, we can save the last state to eeprom. Can j5 do that?
Thank

**Comment by rwaldron** [comment]
Just copying the reply I gave in the gitter channel: 

> J5 isn't doing that, it's the standard state normalizing that occurs in standard firmata https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L771 > https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L722-L725 > https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L290-L295

There isn't anything J5 can do about this at its level in the stack

**Comment by drj-io** [comment]
OK, that's what I figured, thanks.

**Comment by soundanalogous** [comment]
Some day this will be possible if I or someone else ever gets to this: https://github.com/firmata/arduino/issues/166.

**Comment by sumarouno** [comment]
I agree
