### ISSUE TITLE
motor-hbridge.js wiring diagram is wrong

### ISSUE THREAD

**Issue by dtex** [rwaldron/johnny-five#1231]
This [image](https://github.com/rwaldron/johnny-five/blob/master/docs/breadboard/motor-hbridge.png) and corresponding [Fritzing diagram](https://github.com/rwaldron/johnny-five/blob/master/docs/breadboard/motor-hbridge.fzz) show the logic voltage coming from the motor power supply. That should be coming from the Arduino.

**Comment by lyzadanger** [comment]
@dtex As the discoverer of the glitch, I could take this (I also happen to be building circuits this week using that exact H-bridge—I could add a two-motor example while I'm in there, even).

**Comment by dtex** [comment]
Awesome! Thank you 👍
