### ISSUE TITLE
autoscroll() not working

### ISSUE THREAD

**Issue by nalakawula** [rwaldron/johnny-five#1235]
I try `autoscroll()` for my mega2560 and my lcd 1602 with i2c backpack. What i got was "BleepBloop" with blinking cursor at the end.
here my code for m mega:

``` javascript
var five = require('johnny-five');

var boards = new five.Boards([
{
    id: "mega",
    port: "/dev/ttyUSB3"
},
]);

boards.on('ready', function() {
    var lcd = new five.LCD({
        controller: "PCF8574T", 
        address: 0x27, 
        bus: 2, 
        rows: 2, 
        cols: 16
    });

        lcd.cursor(0, 0);
        lcd.autoscroll().print("Bloop").print("Bleep");
});
```

thank you

**Comment by rwaldron** [comment]
Looks like autoscroll and cursor blink may have gotten mixed up!

**Comment by sumarouno** [comment]
Have you fixed that? I will happy to try. Thanks

**Comment by rwaldron** [comment]
The issue: J5's LCD wasn't setting _and_ storing the display "entry" bits

**Comment by rwaldron** [comment]
I'll push the fix out today

**Comment by sumarouno** [comment]
I will try as soon as possible, I have a job at other town right now. Thank you.

**Comment by rwaldron** [comment]
Sorry for the delay, I've been moving my office since last Friday afternoon. After testing this again today, I'm noticing that the LCD no longer reliably resets, so I need to figure that out before I can push out a release

**Comment by sumarouno** [comment]
thank you, i will waiting until you push the fix.

**Comment by tawalke** [comment]
I am having a similiar issue with autoscroll() as well on the Intel Edison Arduino with the Grove LCD JHD1313M1/JHD1313M3 sensor on I2C on Grove shield using the Edison-IO.  

The test code is as follows: 
rgbLCD.autoscroll().print("Button was pressed % times", buttonPresses.toString());
and
rgbLCD.autoscroll();
rgbLCD.print("Button was pressed " + buttonPresses.toString() + " times");
and
rgbLCD.autoscroll().print("Button was ").print("pressed " + buttonPresses.toString()).print(" times");

As you can see by the picture the LCD only writes the first 16 characters only and does not scroll showing the rest of the string.
  
![image](https://cloud.githubusercontent.com/assets/2299606/19624197/b84ac666-98b8-11e6-8ffc-415abe73b120.png)

**Comment by rwaldron** [comment]
Yes, the bug will exist on all platforms since it's the same code. 

I'm still having issues with the LCD not fully resetting.

**Comment by rwaldron** [comment]
Sorry, I _did_ push the changes and released them in v0.10.3. I will have to double check the reset issues.

**Comment by sumarouno** [comment]
Thank @rwaldron

**Comment by tawalke** [comment]
Thanks, please keep us posted on any updates.  I did verify that am running v.0.10.3.  I am manually separating the rows now, but I look forward to any feedback you have. Thanks

**Comment by tawalke** [comment]
Hi @rwaldron, I was using the Grove RGB LCD (I2C) for another project and noticed that the autoscroll() is still not working. Any thoughts?

**Comment by rwaldron** [comment]
@tawalke nothing immediately. I'll have to test the hardware and try to reproduce. Can you paste code that reproduces? Thanks

**Comment by rwaldron** [comment]
@tawalke can you try `npm install rwaldron/johnny-five#master`? I was able to reproduce the issue you had and ended up writing a special controller override method definition for `autoscroll`

**Comment by tawalke** [comment]
Excellent, let me try now!

Sent from Windows Mail

**Comment by ritesh2014** [comment]
The grove starter kit V3 LCD controller name is **JHD1313M3**. When I use this name it throws the error - 
>> ERROR: /home/root/.node_app_slot/node_modules/johnny-five/lib/lcd.js:642
        opts.pins.forEach(function(pin) {
So I revert back to the name JHD1313M1 and it works fine except - 
lcd.useChar("heart");
lcd.print(":heart:");
**does not** prints the symbol (screen is blank). 
This **works** - lcd.print("Hello"); bgcolor, blink etc works.

Also autoscroll **does not** works.

Do you have to add JHD1313M3 in the controller list (in lcd.js) and make necessary changes to make the above functions work?

**Comment by vjustov** [comment]
Hi @rwaldron, I was playing around with an arduino uno and the Sparkfun LCD with the simple example and noticed that the autoscroll() is still not working. maybe I'm doing something wrong?

**Comment by hugocruz** [comment]
Hei. 
I believe this is still an issue. @rwaldron was the fix pushed?
