### ISSUE TITLE
Active Pullup resistor for Pin

### ISSUE THREAD

**Issue by tibysko** [rwaldron/johnny-five#1237]
Hi

First, thanks for a great lib!

I have a question regarding how to enable PullUp resistor for the Pin component. According to the Arduino documentation I should be able to enable the pullUp by doing: 

```
pinMode(pin, INPUT);           // set pin to input
digitalWrite(pin, HIGH);       // turn on pullup resistors
```

I have used the same aproach as the Button component, but it does not seem to work.

```
.....
// Enable the pullup resistor after setting pin mode
this.io.digitalWrite(13, this.io.HIGH);
var pin = new five.Pin(13);

pin.read(function(error, value) {
  console.log(value); // This should write 1
});
```

Sadly I can't use the Button component since i need to read the value of the Pin. 

What am I doing wrong, any thoughts? 

Regards Ola

**Comment by soundanalogous** [comment]
Are you using and Arduino Uno or other board with the onboard LED wired to pin 13. If so you can't enable a pull-up on that pin.

**Comment by dtex** [comment]
There was no response so I'm assuming @soundanalogous identified the issue. @tibysko feel free to re-open if necessary.
