### ISSUE TITLE
Support for pull-down resistors on platforms that have them

### ISSUE THREAD

**Issue by andrewn** [rwaldron/johnny-five#1242]
On platforms such as Raspberry Pi, [some pins have both pull-up and pull-down resistors](http://wiringpi.com/pins/special-pin-functions/) but currently there's no way to enable pull-down resistors using Johnny-Five.

Enabling a pull-up resistor works by writing `HIGH` to the pin in `INPUT` mode. I'm proposing that writing `LOW` should enable the built-in pull-down resistor.

I've created an [issue](https://github.com/nebrius/raspi-io/issues/71) and [pull request](https://github.com/nebrius/raspi-io/issues/72) to support this behaviour in [Raspi-IO](https://github.com/nebrius/raspi-io).

I'm going to open a pull request with a patch enabling this but I think an issue is useful for discussing if this is the right approach and something you'd support.

**Comment by revolunet** [comment]
looks like its been merged 👍

**Comment by fivdi** [comment]
Now that #1243 has been merged I think this issue can be closed.

**Comment by rwaldron** [comment]
@fivdi thanks for the follow up
