### ISSUE TITLE
npm not available on Galileo gen 1?

### ISSUE THREAD

**Issue by grv2k8** [rwaldron/johnny-five#1248]
Hi,

I can't find or run npm from my SSH session to my board. All the tutorials I've read have instructions to run this line:
`npm install johnny-five galileo-io`

But I'm getting errors such as "npm: command not found". This is running the latest yocto image and has node installed (v4.4.3). Any help would be appreciated.

**Comment by rwaldron** [comment]
That's strange, can you link me to the yocto image that you're referring to? Thanks

**Comment by rwaldron** [comment]
Also, ssh to the board and try this: `curl https://www.npmjs.org/install.sh | sh`

**Comment by grv2k8** [comment]
Hi Rick,

Pretty sure this is where I got the OS image from:
https://software.intel.com/en-us/get-started-galileo-windows-step1

And trying that SSH command gives me this error:
![image](https://cloud.githubusercontent.com/assets/10396369/20250045/4050d72e-a9cd-11e6-86f1-73806b538336.png)

I tried pasting the contents of install.sh into a local shell file and ran it, and this is what I'm seeing:
![image](https://cloud.githubusercontent.com/assets/10396369/20250054/7f367d22-a9cd-11e6-80ca-631aa9bf4a97.png)

**Comment by rwaldron** [comment]
Oh damn, I forgot that's the BusyBox image. Galileo-IO and Johnny-Five don't support that image anymore, because Intel themselves stopped supporting it.
