### ISSUE TITLE
TSL2561 (luxmeter) - wrong scaling factor?

### ISSUE THREAD

**Issue by CzechUavGuy** [rwaldron/johnny-five#1283]
I would like to report a bug concerning computation of lux from TSL2561 sensor. In file lib/light.js on line 330 and 331 there should not be scaling by 0x10, but 10. Found this by comparing too low results from Johnny Five vs standard Arduino TSL2561 example and verified it in the datasheet (https://cdn-shop.adafruit.com/datasheets/TSL2561.pdf , page 24).

**Comment by CzechUavGuy** [comment]
See pull request #1284

**Comment by rwaldron** [comment]
Fixed and thanks for the patch! https://github.com/rwaldron/johnny-five/pull/1284
