### ISSUE TITLE
If two 74HC595 shift registers are used they need unique addresses

### ISSUE THREAD

**Issue by fivdi** [rwaldron/johnny-five#1291]
This issue was reported on the J5 gitter channel. 

If two 74HC595 shift registers are used like this:

```js
  var expander_1 = new five.Expander({
    controller: "74HC595",
    pins: {
      data: 6,
      clock: 7,
      latch: 8
    }
  });

  var expander_2 = new five.Expander({
    controller: "74HC595",
    pins: {
      data: 9,
      clock: 10,
      latch: 11
    }
  });

  var virtual_1 = new five.Board.Virtual(expander_1);
  var virtual_2 = new five.Board.Virtual(expander_2);

  var ledsGroup_1 = new five.Leds({
    pins: [0, 1, 2, 3, 4, 5, 6, 7],
    board: virtual_1
  });

  var ledsGroup_2 = new five.Leds({
    pins: [0, 1, 2, 3, 4, 5, 6, 7],
    board: virtual_2
  });
```

The following error will be thrown:

<img src="https://files.gitter.im/rwaldron/johnny-five/psfR/blob">

Although a 74HC595 shift register isn't an I2C device, the Expander class treat it as one. This only becomes visible when two or more 74HC595 shift registers are used as they all end up having the same I2C address. It's possible to work around the issue by giving each shift register a unique address:

```js
var expander_1 = new five.Expander({
    controller: "74HC595",
    pins: {
      data: 6,
      clock: 7,
      latch: 8
    },
    address: 0x01
  });

var expander_2 = new five.Expander({
    controller: "74HC595",
    pins: {
      data: 9,
      clock: 10,
      latch: 11
    },
    address: 0x02
  });
```

Perhaps this is only a documentation issue.

**Comment by rwaldron** [comment]
Yikes, that's a totally real bug. Expander controller definitions will need to include some flag that indicates that they are I2C and therefore subject to I2C address constraints, or "normalization" step that automatically adds an address for those that _shouldn't_ require an address from the user. I'll add this to my more immediate "to do" list
