### ISSUE TITLE
Documentation: Multi and Options

### ISSUE THREAD

**Issue by lyzadanger** [rwaldron/johnny-five#1294]
Hi!

[Multi API docs](http://johnny-five.io/api/multi/) don't currently document that the constructor will pass on options to the constituent components (e.g. `freq`), which is a handy feature. Probably a few other nuances that could be added to that docs page as well (distinction of individual vs. aggregate events on each component), and a vetting that docs contain what needs containing...

I'd be happy to take this on if it's something that is useful to do.

**Comment by lyzadanger** [comment]
Hi! Got a chance to update the Wiki:

https://github.com/rwaldron/johnny-five/wiki/Multi

**Comment by dtex** [comment]
This looks good to me. I know ```opts.freq``` is on the hit list for a breaking change but that seems beside the point for now.

Thank you @lyzadanger !
