### ISSUE TITLE
Joystick axes have the same value

### ISSUE THREAD

**Issue by NicolasThebaud** [rwaldron/johnny-five#1304]
Hi !

I wrote a little script to test a joystick I salvaged from an old controller.
It just reads the value from two digital pins and prints it in the console.
```
board.on('ready', function() {
	var joystick = new j5.Joystick({
		pins: ['A0', 'A2']
	})

	joystick.on('change',  function() {
		console.log('\033c')
		console.log("****** Joystick ******")
		console.log('x : ', this.x)
		console.log('y : ', this.y)
		console.log("**********************")
	})
})
```
The only problem is that the Y axis' value & X's are the same

here's how the whole thing's wired:
![](https://lh5.googleusercontent.com/nualB_l7ZCAVxPFekm0hjSHGxjqT8h57gp7LMcz960oNcFbwxjp3p99_-MDaw1JWocnznojEY_q7FqU=w1360-h638-rw)
Red jumpers : power
White : ground
Green/Blue : data

The six jumpers on the right are wired to the Joystick as follows:
![](https://lh5.googleusercontent.com/tXdo0c78cWEiTceQ0W8F2mOfx-qOjV9tiVXWbpHpOUavT9WDFaX024cKICJDLJJpyy4wFiMWF8jDbaE=w1360-h638-rw)

Is my joystick broken ? Did I do something wrong ?

**Comment by rwaldron** [comment]
The images aren't showing for me :|

**Comment by dtex** [comment]
Hi @NicolasThebaud 

It's been a while with no response so I'm going to go ahead and close this. If you are still having a problem feel free to re-open but please add images of your wiring.
