### ISSUE TITLE
Use analog output as digital in relay pins

### ISSUE THREAD

**Issue by gokhandilek** [rwaldron/johnny-five#1310]
Hi,
I am trying to use the relay module of the johnny-five.
Everyhing works fine when i use the digital pins.
For example

```js
relays.firstRelay = new five.Relay ( {
  pin:13,
  type:'NO'
});
```
I get 5V out no issue.
If I try pin 14, I will get 0V.

This is what I have tried so far.

```js
relays.firstRelay = new five.Relay( {
  pin:14,
  type: 'NO'
});
```
and 

```js
analogPinsToDigitalPins.pin14 = new five.Pin({
  pin:14,
  type: 'digital'
});

relays.firstRelay = new five.Pin({
   pin:analogPinsToDigitalPins.pin14
});
```

Cannot get 5V output regardless.
Thank you.

**Comment by rwaldron** [comment]
Thanks for the report, I will try to address this issue by tomorrow.

**Comment by rwaldron** [comment]
Move to #1277
