### ISSUE TITLE
Si7021 measurement errors with "high" values (`uint16` vs `int16` conversion error)

### ISSUE THREAD

**Issue by balda** [rwaldron/johnny-five#1315]
Above `56%`, relative humidity is not `57%` but `-68%`.

It seems it's the same bug than https://github.com/rwaldron/johnny-five/issues/1278 (`uint16()` need to be used instead of `int16()`).

I have successfully test the fix.

**Comment by rwaldron** [comment]
Awesome, we'll get this patched asap

**Comment by balda** [comment]
Thanks!

I really MUST learn to make proper J5 unit tests to help improving this awesome lib ;-)

**Comment by balda** [comment]
Thanks ;-)
