### ISSUE TITLE
Etherport board ready delay

### ISSUE THREAD

**Issue by gokhandilek** [rwaldron/johnny-five#1318]
I was just wondering why Etherport takes a little longr to initialise compared to say using USB.

This is causing issues with my whole node app when I am trying to get callbacks. They are getting delayed.

For example, I cannot initialise the connection unless I have the timeout set like below:

`var board = new five.Board({
    port: new EtherPort(3030),
    timeout: 136000
});`

I can connect via USB with a very small timeout. It works perfectly but I need it to work via TCP/IP.

Thanks.

**Comment by rwaldron** [comment]
Thanks for the report!

Issue with Etherport should be filed [here](https://github.com/rwaldron/etherport/issues), however any delay that you're experiencing is out of the control of both Etherport and Johnny-Five. Using the timeout is the correct way to account for connection latency.
