### ISSUE TITLE
johnny-five security features

### ISSUE THREAD

**Issue by github372** [rwaldron/johnny-five#1321]
I am new in  johnny-five and I search for security feature such as set password, data and communication encryption ,and... . but I can not find any things .so my question is: has johnny-five any security features?

**Comment by rwaldron** [comment]
Hi! If I understand correctly, I believe what you're looking for would be provided by the Node.js runtime itself: https://nodejs.org/api/crypto.html

**Comment by github372** [comment]
Thank you...
