### ISSUE TITLE
Fix Piezo.prototype.note (bad frequencies)

### ISSUE THREAD

**Issue by lyzadanger** [rwaldron/johnny-five#1323]
Per https://github.com/code-dot-org/code-dot-org/pull/14332

> Override johnny-five's Piezo.prototype.note because it's playing the wrong frequencies, at least in Maker Toolkit. I think this is a bug in their component and I'm working on getting it fixed upstream. In the meantime it's fairly easy to patch in a fix in our wrapper.

**Comment by lyzadanger** [comment]
I plan to work on this next week (week of Apr. 17). Someone else can grab this if that's not soon enough!

**Comment by islemaster** [comment]
Fixed in https://github.com/rwaldron/johnny-five/pull/1328, released in [v0.10.10](https://github.com/rwaldron/johnny-five/releases/tag/v0.10.10).

**Comment by dtex** [comment]
Looks like this issue should have been closed a while back. Re-open if I'm missing something. Thanks everyone.
