### ISSUE TITLE
Disable REPL with Boards

### ISSUE THREAD

**Issue by jonaslund** [rwaldron/johnny-five#1325]
Hi

How do you disable the REPL when using Boards

Trying the obvious

```js
var boards = new five.Boards(["A", "B"], {
  repl: false
});
```

but doesn't work?

**Comment by fivdi** [comment]
I haven't tried it but the code [here](https://github.com/rwaldron/johnny-five/blob/master/lib/board.js#L1095-L1152) indicates that the following may work:
```js
var boards = new five.Boards({
  ports: ["A", "B"],
  repl: false
});
```

**Comment by rwaldron** [comment]
On day I will have time to properly document all this stuff. I'm sorry this was confusing :(
