### ISSUE TITLE
Function is not a name type

### ISSUE THREAD

**Issue by Humaid-alvi** [rwaldron/johnny-five#1330]
Hi! Everyone, i have started using arduino and when i uploaded code it is showing that Function is not a name type and also I have installed Node JS but unable to install johnny-five. 
Please help

**Comment by fivdi** [comment]
Hi @Humaid-alvi,

Can you post the following information please:

 * The exact command that is being used to install Johnny-Five and complete console output of that install command
 * The version of Node.js that is being used (the command `node -v` will display this information)
 * The name and version operating system that is being uses
