### ISSUE TITLE
There is a way to burn node code on arduino.

### ISSUE THREAD

**Issue by umair-khanzada** [rwaldron/johnny-five#1331]
Is this possible to run jhony-five code directly into `arduino` , I wanna build an quadcopter using <br/> `jhony-five`.

**Comment by rwaldron** [comment]
Sorry, there is no way to run JavaScript code directly on an Arduino. If you want to run your JS programs on board, you'll need to use a single board computer that runs linux and supports Node.js: 

- Tessel 2
- Raspberry Pi
- BeagleBone Black
- Intel Edison or Joule
- piDuino
- CHIP
