### ISSUE TITLE
Arduino auto reconnect when Nodejs running?

### ISSUE THREAD

**Issue by nhimspec** [rwaldron/johnny-five#1332]
When server running, i unplug arduino and plug arduino again but i can't control Arduino anymore. Can we reconnect Arduino with Node Server?
P/s: sorry for my bad english :D

**Comment by criticalboot** [comment]
No, We can't. Once disconnected, we lost the state sync between arduino and the server. So you need to restart the server to take control over arduino again.

**Comment by nhimspec** [comment]
Is there any other solution? Can u help me? thanks :D

**Comment by scottgonzalez** [comment]
You shouldn't need to restart the server, but you will need to go through the initialization process for the arduino which will involve creating a new board instance and any other components such as buttons and resetting all of your in-memory state. The specifics of how you do this likely depends on your setup.

**Comment by nhimspec** [comment]
can u give me a simple example ~_~?

**Comment by rwaldron** [comment]
> When server running, i unplug arduino and plug arduino again but i can't control Arduino anymore. 

It's not possible to support this.
