### ISSUE TITLE
Support for Omega2+ board.

### ISSUE THREAD

**Issue by nerdyzia** [rwaldron/johnny-five#1334]
Please provide feature support for omega2+ board.

https://onion.io/store/omega2p/

**Comment by fivdi** [comment]
@gunderson implemented [Omega2-IO](https://github.com/gunderson/omega2-io) for the Onion Omega2 and Omega2+ recently. You could ask over there what the current status is.

**Comment by fivdi** [comment]
It looks like Omega2-IO development has been discontinued. See https://github.com/gunderson/omega2-io/issues/1.

@nerdyzia Typically Johnny-Five itself isn't extended to support new boards like the Omega2+. Instead, an IO plugin is implemented to support a particular board. For example [BeagleBone-IO](https://github.com/julianduque/beaglebone-io) for the BeagleBone Black, [Raspi-IO](https://github.com/nebrius/raspi-io) for the Raspberry Pi or [Omega2-IO](https://onion.io/store/omega2p/) for the Omega2+.

I don't think there are any TODOs for Johnny-Five related to this issue.

**Comment by rudacs** [comment]
https://github.com/rudacs/omega2-io-pro

**Comment by dtex** [comment]
@nerdyzia Were you able to try any of those io plugins? Can this issue be closed?
