### ISSUE TITLE
Handoff of Board between processes via file descriptor sharing

### ISSUE THREAD

**Issue by anweiss** [rwaldron/johnny-five#1344]
Not sure if I'm asking this correctly, but is there a way to perform a handover of an open board serial connection from one node process to another via file descriptor sharing over UNIX sockets? Basically, I'm trying to do something like this -> https://xathrya.id/2015/12/09/nodejs-unix-sockets/ ... but passing the fd of the open serial connection to another process.

**Comment by rwaldron** [comment]
Hello! I think you want to ask this in [node-serialport](https://github.com/EmergingTechnologyAdvisors/node-serialport) :)
