### ISSUE TITLE
Board is closing immediately.

### ISSUE THREAD

**Issue by facetime88** [rwaldron/johnny-five#1352]
Hi Johnny,

My board has been successfully connected and I use the example code below:

> var five = require("johnny-five");
var board = new five.Board();
// The board's pins will not be accessible until
// the board has reported that it is ready
board.on("ready", function() {
  console.log("Ready!");
  var led = new five.Led(13);
  led.blink(500);
});

And it responses in console:

> Arduino is ready!;	

Followed with another log immediately:

> Board Closing.

And the devtool popup a message box saying:

> Debugging connection was closed. Reason: render process is gone.

And the app is going blank and nothing I can do beside terminate the app. If I block out all johnny initialization, the app is working fine just like before using johnny-five.

Am I missing something here? Thanks

I am on Win 10 x64 with Electron 1.6.10 and node 6.10.3

Here is the full log (all deprecated warning refer to repl.js):

> 1496654178068 Connected COM3  
1496654179212 Repl Initialized  
'webkitOfflineAudioContext' is deprecated. Please use 'OfflineAudioContext' instead.
'webkitAudioContext' is deprecated. Please use 'AudioContext' instead.
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
'webkitIDBTransaction' is deprecated and will be removed in M57, around March 2017. Please use 'IDBTransaction' instead. 
'webkitIDBRequest' is deprecated and will be removed in M57, around March 2017. Please use 'IDBRequest' instead. 
'webkitIDBObjectStore' is deprecated and will be removed in M57, around March 2017. Please use 'IDBObjectStore' instead. 
'webkitIDBKeyRange' is deprecated and will be removed in M57, around March 2017. Please use 'IDBKeyRange' instead. 
'webkitIDBIndex' is deprecated and will be removed in M57, around March 2017. Please use 'IDBIndex' instead. 
'webkitIDBFactory' is deprecated and will be removed in M57, around March 2017. Please use 'IDBFactory' instead. 
'webkitIDBDatabase' is deprecated and will be removed in M57, around March 2017. Please use 'IDBDatabase' instead. 
'webkitIDBCursor' is deprecated and will be removed in M57, around March 2017. Please use 'IDBCursor' instead. 
'webkitIndexedDB' is deprecated and will be removed in M57, around March 2017. Please use 'indexedDB' instead. 
'webkitURL' is deprecated. Please use 'URL' instead.
1496654179256 Board Closing.

**Comment by facetime88** [comment]
The johnny-five init above put on a class. But when I put in directly on index.html page inside body tag, I now even get error before "Board Closing"

> Uncaught TypeError: Cannot redefine property: board
    at Function.defineProperty (<anonymous>)
    at Repl.<anonymous> (E:\client\node_modules\johnny-five\lib\repl.js:108:12)
    at Array.forEach (native)
    at Repl.inject (E:\client\node_modules\johnny-five\lib\repl.js:107:20)
    at Repl.initialize (E:\client\node_modules\johnny-five\lib\repl.js:94:8)
    at Board.finalizeAndBroadcast (E:\client\node_modules\johnny-five\lib\board.js:434:17)
    at Board.<anonymous> (E:\client\node_modules\johnny-five\lib\board.js:147:18)
    at Board.ready (E:\client\node_modules\johnny-five\node_modules\firmata\lib\firmata.js:701:7)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)

**Comment by rwaldron** [comment]
Have you recompiled node-serialport for Electron? https://github.com/electron/electron-rebuild#electron-rebuild

**Comment by facetime88** [comment]
Yes, it has been recompiled. Before recompiled it said DLL initilization failed, not working at all.
Now it's working but closing immediately.

**Comment by facetime88** [comment]
I do not know what is the cause of the problem and after frustrated for a week, today I ended up using Cylon and make it working in less then 3 minutes.

**Comment by rwaldron** [comment]
> I do not know what is the cause of the problem and after frustrated for a week

I'm sorry, I've never encountered the issue myself, so I didn't know how to help.

>  today I ended up using Cylon and make it working in less then 3 minutes.

Lol, good luck with that.

**Comment by Nishkalkashyap** [comment]
If anyone else was stuck on this issue, the answer for me was to disable repl loop. SOmething like this:

    const board = new five.Board({
        repl: false,
        port: 'COM3'
    });

**Comment by iamisti** [comment]
@Nishkalkashyap you are a godsent. Been having this issue for 3 days straight, tried everything and only this helped!
