### ISSUE TITLE
HC-SR04 Raspberry Pi - Double Pins

### ISSUE THREAD

**Issue by Akashbudhai** [rwaldron/johnny-five#1355]
How do I use Johnny-Five Proximity API as it expects a single pin configuration(trigger and echo shorted together) while with Pi we cannot have a single pin (due to the 3.3V and 5V back current).?

**Comment by fivdi** [comment]
With the addition of two resistors it's also possible to use a single pin for trigger and echo on a Raspberry Pi as can be seen [with Pi-IO here](https://github.com/fivdi/pi-io#measure-proximity-with-a-hc-sr04-connected-to-gpio25). To the best of my knowledge Raspi-IO doesn't support `Ping` which is needed for the HC-SR04.
