### ISSUE TITLE
Cannot add a new segment to an existing animation

### ISSUE THREAD

**Issue by jbdesbas** [rwaldron/johnny-five#1361]
Hello,

I don't understand how to enqueue segments of animation. When I put a new segment with animation.enqueue(), then the entire animation is replaced by the new segment.

Can you help me please ?

Here is my code, only the leg of the second segment is moving : 
```
m.tap=function(tapleg){
	anim.enqueue({
		target:s.r1f,
		duration:300,
		fps:25,
		cuePoints:[0,0.5,1],
		keyFrames:[null,{degrees: 50,easing:easeInOut},{degrees: 90,easing:easeInOut}]
	});
	anim.enqueue({
		target:s.r2f,
		duration:300,
		fps:25,
		cuePoints:[0,0.5,1],
		keyFrames:[null,{degrees: 50,easing:easeInOut},{degrees: 90,easing:easeInOut}]
	});
}
```

>Board : Arduino ProMini 5V 16Mhz (ATmega 328)
>Johnny5 : johnny-five@0.11.3
>NodeJS : v4.2.6

**Comment by dtex** [comment]
Is it your intent that these play at the same time?

**Comment by jbdesbas** [comment]
Hello,
No, i want the second one play after. Idea ?

**Comment by dtex** [comment]
I do think you've found a bug. While I track that down, I have a tip for making this work and be a little less code too...

````
s.femurs = new five.Servos([s.r1f, s.r2f]); // I'm guessing these are femurs

m.tap=function(tapleg){
	anim.enqueue({
		target:s.femurs,
		duration:600,
		fps:25,
		cuePoints:[0, 0.25, 0.5, 0.75, 1],
		keyFrames:[
                     [null,{degrees: 50,easing:easeInOut},{degrees: 90,easing:easeInOut}, null, null],
                     [null, null, null,{degrees: 50,easing:easeInOut},{degrees: 90,easing:easeInOut}]
                ]
	});
}
````
You can group any collection of Servos any way you like so creating a femurs group for an animation like this where you're just moving all the femurs makes sense. Servos can be in any number of groups.

**Comment by jbdesbas** [comment]
Ok thank you, it is working. But I really don't understand why
animation.enqueue() don't add a segment after the existing one :-/

**Comment by dtex** [comment]
> I really don't understand why animation.enqueue() don't add a segment after the existing one

It's a bug.

**Comment by jbdesbas** [comment]
OK, for information, I use "PCA9685" controller for servo

**Comment by dtex** [comment]
Cool. Just FYI, another user has had some problems with sending multiple, concurrent commands to their PCA9685. It could turn out to be an issue for you too #1340

**Comment by dtex** [comment]
We need to check and see if their is a segment already running before call next() [here](https://github.com/rwaldron/johnny-five/blob/master/lib/animation.js#L158-L160)
