### ISSUE TITLE
Board - Specify Port Example

### ISSUE THREAD

**Issue by Josh-Weston** [rwaldron/johnny-five#1369]
[Example Page](http://johnny-five.io/examples/board-with-port/)

The example code used for specifying a port with an Arduino Uno produces the following error:

```
this.digitalWrite(13, this.pins[13].value ? 0 : 1);
                                       ^
TypeError: Cannot read property '13' of undefined
```

This is caused by referencing ```this``` out of context.

A few possible solutions aside from using Johnny-Five's shorthand, such as ```led.blink(500)```:

## 1) Use the self pattern

```
board.on('ready', function() {
   
    var self = this;
    self.pinMode(13, self.MODES.OUTPUT);
    
    self.loop(500, function() {
        self.digitalWrite(13, self.pins[13].value ? 0 : 1);
    });
    
});
```

## 2) Use a closure

```
    this.pinMode(13, this.MODES.OUTPUT);
    this.loop(500, (function(board) {
        return function() {
            board.digitalWrite(13, board.pins[13].value ? 0 : 1);
        }
    })(this));

```

## 3) Ensure the ```Board``` object is passed to the callback and can be referenced through ```this```

**Comment by rwaldron** [comment]
Thanks for the bug report. I've pushed a change to the example code to address the bug
