### ISSUE TITLE
Switch defaults to NC when no options object is specified

### ISSUE THREAD

**Issue by er1x** [rwaldron/johnny-five#1388]
Just trying out [this example](http://johnny-five.io/examples/switch-magnetic-door/), using Node v8.3.0.

If no options are specified for Switch (just pin number) it defaults to "NC" instead "NO", as said in docs.

<img width="828" alt="imagen" src="https://user-images.githubusercontent.com/7016146/30511746-bf6a8e2a-9adf-11e7-9abf-d9013579aad4.png">

<img width="891" alt="imagen" src="https://user-images.githubusercontent.com/7016146/30511759-e1c3a9e8-9adf-11e7-9163-996b2f2b609a.png">

**Comment by rwaldron** [comment]
Do you want to open a PR with a fix and updated tests?

**Comment by er1x** [comment]
PR #1391
