### ISSUE TITLE
board.loop() example code throws 'TypeError: this.digitalWrite is not a function'

### ISSUE THREAD

**Issue by phillchill** [rwaldron/johnny-five#1389]
I just tried the following example code for board.loop() found at http://johnny-five.io/api/board/

```
var five = require("johnny-five");
var board = new five.Board();

board.on("ready", function() {
  var state = 0;

  this.pinMode(13, this.MODES.OUTPUT);

  this.loop(500, function() {
    this.digitalWrite(13, (state ^= 1));
  });
});
```

But it throws `TypeError: this.digitalWrite is not a function`

I think the `this` reference inside the `loop` call is the problem and it's fixed by:

```
var five = require("johnny-five");
var board = new five.Board();

board.on("ready", function() {
  var state = 0;

  this.pinMode(13, this.MODES.OUTPUT);

  this.loop(500, function() {
    board.digitalWrite(13, (state ^= 1));
  });
});
```

Board: Arduino Uno
Version of Johnny-Five: johnny-five@0.11.6
Steps to reproduce (including code samples):
1. save above example code to loop.js
2. run `node loop.js`
3. see error

**Comment by rwaldron** [comment]
Thanks for the report, issue fixed here: https://github.com/rwaldron/johnny-five/wiki/Board/_compare/ffc01ceed77a6ab8c1c323d9b9647973749a306f...a554930dee5a8aafd776317a77cd7ab37598db79

http://johnny-five.io/api/board/#loopmilliseconds-handler
