### ISSUE TITLE
Destroy component

### ISSUE THREAD

**Issue by rudacs** [rwaldron/johnny-five#1397]
I have a button (input) that I declare on a pin and in another moment it becomes a led (output) for example.

Except when creating the button there is no way to disable it or destroy it.
There is no disable or destroy feature to build another component on top of the pin.

Does anyone know any way?

**Comment by rwaldron** [comment]
> I have a button (input) that I declare on a pin and in another moment it becomes a led (output) for example.

Can you explain how this happens with the physical hardware?

**Comment by dtex** [comment]
Hi @rudacs just wanted to follow up on this. Can you tell us what is happening in the physical world? Is an end user expected to disconnect a button and wire up an LED on the same pin?

**Comment by dtex** [comment]
Hi @rudacs, 

Since we haven't heard back I'm going to close this issue. Feel free to re-open any time.
