### ISSUE TITLE
TypeError: Cannot read property 'OUTPUT' of undefined. in Arduino uno

### ISSUE THREAD

**Issue by fn-code** [rwaldron/johnny-five#1405]
Can someone point me in the right direction to resolve this?
![five](https://user-images.githubusercontent.com/20040743/31897557-588d3ebe-b849-11e7-9f65-92d6e9d2eb54.png)

**Comment by rwaldron** [comment]
The code in your example uses an arrow function, which implicitly binds the value of `this` in the scope in which it was defined. `this` is not `board` in your callback, type: `board.pinMode(13, board.MODES.OUTPUT); board.digitalWrite(13, 1);`

**Comment by fn-code** [comment]
yeah, i forget it. thank you.
