### ISSUE TITLE
Re-instanced Board does not create new Relay

### ISSUE THREAD

**Issue by mdingena** [rwaldron/johnny-five#1423]
When I create a new `five.Board` instance for the same physical board for the second time, the `ready` event triggers correctly but it does not create a new `five.Relay`.

Adding a board:

    let myboards = {};

    const board = new five.Board({
        id      : "living-room-lights",
        timeout : 1e5,
        repl    : false,
        debug   : false,
        port    : new EtherPortClient({
            host : "192.168.178.14",
            port : "3030"
        })
    });
    board.on( 'ready', function() {
        board.myrelay = new five.Relay( 5 );
        board.myrelay.close();
        console.log( board );
    });
    myboards[ "living-room-lights" ] = board;

Removing the board (triggered after I sever the board's power):

    myboards[ "living-room-lights" ].io.reset();
    delete myboards[ "living-room-lights" ];

Then I re-add the board using the code from the first snippet.

The `ready` event triggers, but the console logs a different board.  
The first instance logs this:

    Board {
    id: 'living-room-lights',
    timeout: 100000,
    repl: false,
    debug: false,
    port: 'Connecting to host:port: 192.168.178.14:3030',
    timer:
    Timeout {
        '0': null,
        _called: false,
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 5004,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(asyncId)]: 184,
        [Symbol(triggerAsyncId)]: 0 },
    isConnected: true,
    isReady: true,
    io:
    Board {
        domain: null,
        _events:
        { close: [Function: bound ],
            disconnect: [Function: bound ],
            error: [Function: bound ],
            string: [Function: bound ] },
        _eventsCount: 4,
        _maxListeners: undefined,
        isReady: true,
        MODES:
        { INPUT: 0,
            OUTPUT: 1,
            ANALOG: 2,
            PWM: 3,
            SERVO: 4,
            SHIFT: 5,
            I2C: 6,
            ONEWIRE: 7,
            STEPPER: 8,
            SERIAL: 10,
            PULLUP: 11,
            IGNORE: 127,
            PING_READ: 117,
            UNKOWN: 16 },
        I2C_MODES: { WRITE: 0, READ: 1, CONTINUOUS_READ: 2, STOP_READING: 3 },
        STEPPER: { TYPE: [Object], RUNSTATE: [Object], DIRECTION: [Object] },
        SERIAL_MODES: { CONTINUOUS_READ: 0, STOP_READING: 1 },
        SERIAL_PORT_IDs:
        { HW_SERIAL0: 0,
            HW_SERIAL1: 1,
            HW_SERIAL2: 2,
            HW_SERIAL3: 3,
            SW_SERIAL0: 8,
            SW_SERIAL1: 9,
            SW_SERIAL2: 16,
            SW_SERIAL3: 17,
            DEFAULT: 8 },
        SERIAL_PIN_TYPES:
        { RES_RX0: 0,
            RES_TX0: 1,
            RES_RX1: 2,
            RES_TX1: 3,
            RES_RX2: 4,
            RES_TX2: 5,
            RES_RX3: 6,
            RES_TX3: 7 },
        RESOLUTION: { ADC: 1023, DAC: null, PWM: 1023 },
        HIGH: 1,
        LOW: 0,
        pins:
        [ [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object] ],
        ports: [ 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
        analogPins: [ 17 ],
        version: { major: 2, minor: 5 },
        firmware: { name: 'Domus_StandardFirmataWiFi.ino', version: [Object] },
        currentBuffer:
        [ 240,
            106,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            0,
            247 ],
        versionReceived: true,
        name: 'Firmata',
        settings:
        { reportVersionTimeout: 5000,
            samplingInterval: 19,
            serialport: [Object] },
        pending: 1,
        transport:
        EtherPortClient {
            domain: null,
            _events: [Object],
            _eventsCount: 5,
            _maxListeners: undefined,
            path: 'Connecting to host:port: 192.168.178.14:3030',
            name: 'EtherPortClient',
            host: '192.168.178.14',
            port: '3030',
            _reconnectTimeoutSecs: 15,
            _queue: [],
            _socket: [Object],
            _reconnectTimer: null,
            _tcp: [Object] },
        sp:
        EtherPortClient {
            domain: null,
            _events: [Object],
            _eventsCount: 5,
            _maxListeners: undefined,
            path: 'Connecting to host:port: 192.168.178.14:3030',
            name: 'EtherPortClient',
            host: '192.168.178.14',
            port: '3030',
            _reconnectTimeoutSecs: 15,
            _queue: [],
            _socket: [Object],
            _reconnectTimer: null,
            _tcp: [Object] },
        reportVersionTimeoutId:
        Timeout {
            '0': null,
            _called: true,
            _idleTimeout: -1,
            _idlePrev: null,
            _idleNext: null,
            _idleStart: 5002,
            _onTimeout: null,
            _timerArgs: undefined,
            _repeat: null,
            _destroyed: false,
            [Symbol(asyncId)]: 183,
            [Symbol(triggerAsyncId)]: 0 },
        defaultLed: 13,
        port: 'Connecting to host:port: 192.168.178.14:3030' },
    register:
    [ Relay {
        board: [Circular],
        io: [Object],
        id: 'D862E31E-59E8-482D-B4B2-FB537C1F1035',
        custom: {},
        pin: 5 } ],
    occupied: [],
    Drivers: {},
    sigint: true,
    pins:
    Pins {
        '0':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '1':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '2':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '3':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '4':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '5':
        { supportedModes: [Array],
            mode: undefined,
            value: 1,
            report: 1,
            analogChannel: 127 },
        '6':
        { supportedModes: [],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '7':
        { supportedModes: [],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '8':
        { supportedModes: [],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '9':
        { supportedModes: [],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '10':
        { supportedModes: [],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '11':
        { supportedModes: [],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '12':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '13':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '14':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '15':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '16':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '17':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 0 } },
    _events:
    { ready: [Function],
        error: { [Function: bound onceWrapper] listener: [Function] } },
    _eventsCount: 2,
    type: 'OTHER',
    MODES:
    { INPUT: 0,
        OUTPUT: 1,
        ANALOG: 2,
        PWM: 3,
        SERVO: 4,
        SHIFT: 5,
        I2C: 6,
        ONEWIRE: 7,
        STEPPER: 8,
        SERIAL: 10,
        PULLUP: 11,
        IGNORE: 127,
        PING_READ: 117,
        UNKOWN: 16 },
    millis: [Function],
    myrelay:
    Relay {
        board: [Circular],
        io:
        Board {
            domain: null,
            _events: [Object],
            _eventsCount: 4,
            _maxListeners: undefined,
            isReady: true,
            MODES: [Object],
            I2C_MODES: [Object],
            STEPPER: [Object],
            SERIAL_MODES: [Object],
            SERIAL_PORT_IDs: [Object],
            SERIAL_PIN_TYPES: [Object],
            RESOLUTION: [Object],
            HIGH: 1,
            LOW: 0,
            pins: [Array],
            ports: [Array],
            analogPins: [Array],
            version: [Object],
            firmware: [Object],
            currentBuffer: [Array],
            versionReceived: true,
            name: 'Firmata',
            settings: [Object],
            pending: 1,
            transport: [Object],
            sp: [Object],
            reportVersionTimeoutId: [Object],
            defaultLed: 13,
            port: 'Connecting to host:port: 192.168.178.14:3030' },
        id: 'D862E31E-59E8-482D-B4B2-FB537C1F1035',
        custom: {},
        pin: 5 } }

The second board logs this:

    Board {
    id: 'living-room-lights',
    timeout: 100000,
    repl: false,
    debug: false,
    port: 'Connecting to host:port: 192.168.178.14:3030',
    timer:
    Timeout {
        '0': null,
        _called: false,
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 33787,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(asyncId)]: 712,
        [Symbol(triggerAsyncId)]: 0 },
    isConnected: true,
    isReady: true,
    io:
    Board {
        domain: null,
        _events:
        { close: [Function: bound ],
            disconnect: [Function: bound ],
            error: [Function: bound ],
            string: [Function: bound ] },
        _eventsCount: 4,
        _maxListeners: undefined,
        isReady: true,
        MODES:
        { INPUT: 0,
            OUTPUT: 1,
            ANALOG: 2,
            PWM: 3,
            SERVO: 4,
            SHIFT: 5,
            I2C: 6,
            ONEWIRE: 7,
            STEPPER: 8,
            SERIAL: 10,
            PULLUP: 11,
            IGNORE: 127,
            PING_READ: 117,
            UNKOWN: 16 },
        I2C_MODES: { WRITE: 0, READ: 1, CONTINUOUS_READ: 2, STOP_READING: 3 },
        STEPPER: { TYPE: [Object], RUNSTATE: [Object], DIRECTION: [Object] },
        SERIAL_MODES: { CONTINUOUS_READ: 0, STOP_READING: 1 },
        SERIAL_PORT_IDs:
        { HW_SERIAL0: 0,
            HW_SERIAL1: 1,
            HW_SERIAL2: 2,
            HW_SERIAL3: 3,
            SW_SERIAL0: 8,
            SW_SERIAL1: 9,
            SW_SERIAL2: 16,
            SW_SERIAL3: 17,
            DEFAULT: 8 },
        SERIAL_PIN_TYPES:
        { RES_RX0: 0,
            RES_TX0: 1,
            RES_RX1: 2,
            RES_TX1: 3,
            RES_RX2: 4,
            RES_TX2: 5,
            RES_RX3: 6,
            RES_TX3: 7 },
        RESOLUTION: { ADC: 1023, DAC: null, PWM: 1023 },
        HIGH: 1,
        LOW: 0,
        pins:
        [ [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object] ],
        ports: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
        analogPins: [ 17 ],
        version: { major: 2, minor: 5 },
        firmware: { name: 'Domus_StandardFirmataWiFi.ino', version: [Object] },
        currentBuffer:
        [ 240,
            106,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            127,
            0,
            247 ],
        versionReceived: true,
        name: 'Firmata',
        settings:
        { reportVersionTimeout: 5000,
            samplingInterval: 19,
            serialport: [Object] },
        pending: 0,
        transport:
        EtherPortClient {
            domain: null,
            _events: [Object],
            _eventsCount: 5,
            _maxListeners: undefined,
            path: 'Connecting to host:port: 192.168.178.14:3030',
            name: 'EtherPortClient',
            host: '192.168.178.14',
            port: '3030',
            _reconnectTimeoutSecs: 15,
            _queue: [],
            _socket: [Object],
            _reconnectTimer: null,
            _tcp: [Object] },
        sp:
        EtherPortClient {
            domain: null,
            _events: [Object],
            _eventsCount: 5,
            _maxListeners: undefined,
            path: 'Connecting to host:port: 192.168.178.14:3030',
            name: 'EtherPortClient',
            host: '192.168.178.14',
            port: '3030',
            _reconnectTimeoutSecs: 15,
            _queue: [],
            _socket: [Object],
            _reconnectTimer: null,
            _tcp: [Object] },
        reportVersionTimeoutId:
        Timeout {
            '0': null,
            _called: true,
            _idleTimeout: -1,
            _idlePrev: null,
            _idleNext: null,
            _idleStart: 33786,
            _onTimeout: null,
            _timerArgs: undefined,
            _repeat: null,
            _destroyed: false,
            [Symbol(asyncId)]: 711,
            [Symbol(triggerAsyncId)]: 0 },
        defaultLed: 13,
        port: 'Connecting to host:port: 192.168.178.14:3030' },
    register: [],
    occupied: [],
    Drivers: {},
    sigint: true,
    pins:
    Pins {
        '0':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '1':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '2':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '3':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '4':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '5':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '6':
        { supportedModes: [],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '7':
        { supportedModes: [],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '8':
        { supportedModes: [],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '9':
        { supportedModes: [],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '10':
        { supportedModes: [],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '11':
        { supportedModes: [],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '12':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '13':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '14':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '15':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '16':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 127 },
        '17':
        { supportedModes: [Array],
            mode: undefined,
            value: 0,
            report: 1,
            analogChannel: 0 } },
    _events:
    { ready: [Function],
        error: { [Function: bound onceWrapper] listener: [Function] } },
    _eventsCount: 2,
    type: 'OTHER',
    MODES:
    { INPUT: 0,
        OUTPUT: 1,
        ANALOG: 2,
        PWM: 3,
        SERVO: 4,
        SHIFT: 5,
        I2C: 6,
        ONEWIRE: 7,
        STEPPER: 8,
        SERIAL: 10,
        PULLUP: 11,
        IGNORE: 127,
        PING_READ: 117,
        UNKOWN: 16 },
    millis: [Function],
    myrelay:
    Relay {
        board:
        Board {
            id: 'living-room-lights',
            timeout: 100000,
            repl: false,
            debug: false,
            port: 'Connecting to host:port: 192.168.178.14:3030',
            timer: [Object],
            isConnected: true,
            isReady: true,
            io: [Object],
            register: [Array],
            occupied: [],
            Drivers: {},
            sigint: true,
            pins: [Object],
            _events: [Object],
            _eventsCount: 2,
            type: 'OTHER',
            MODES: [Object],
            millis: [Function],
            myrelay: [Object] },
        io:
        Board {
            domain: null,
            _events: [Object],
            _eventsCount: 4,
            _maxListeners: undefined,
            isReady: true,
            MODES: [Object],
            I2C_MODES: [Object],
            STEPPER: [Object],
            SERIAL_MODES: [Object],
            SERIAL_PORT_IDs: [Object],
            SERIAL_PIN_TYPES: [Object],
            RESOLUTION: [Object],
            HIGH: 1,
            LOW: 0,
            pins: [Array],
            ports: [Array],
            analogPins: [Array],
            version: [Object],
            firmware: [Object],
            currentBuffer: [],
            versionReceived: true,
            name: 'Firmata',
            settings: [Object],
            pending: 1,
            transport: [Object],
            sp: [Object],
            reportVersionTimeoutId: [Object],
            defaultLed: 13,
            port: 'Connecting to host:port: 192.168.178.14:3030' },
        id: '1EEEE607-229B-444B-9669-6B78C2334A9F',
        custom: {},
        pin: 5 } }

These lines are different:

    _idleStart: 5004,
    _idleStart: 33787,

    [Symbol(asyncId)]: 184,
    [Symbol(asyncId)]: 712,

    ports: [ 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
    ports: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],

    pending: 1,
    pending: 0,

    // First instance
    register:
        [ Relay {
            board: [Circular],
            io: [Object],
            id: 'D862E31E-59E8-482D-B4B2-FB537C1F1035',
            custom: {},
            pin: 5 } ],
    // Second instance
    register: [],

    // pins.Pins['5']
    value: 1,
    value: 0,

    // First instance
    myrelay:
        Relay {
            board: [Circular],
    // Second instance
    myrelay:
        Relay {
            board:
            Board {
                id: 'living-room-lights',
                timeout: 100000,
                repl: false,
                debug: false,
                port: 'Connecting to host:port: 192.168.178.14:3030',
                timer: [Object],
                isConnected: true,
                isReady: true,
                io: [Object],
                register: [Array],
                occupied: [],
                Drivers: {},
                sigint: true,
                pins: [Object],
                _events: [Object],
                _eventsCount: 2,
                type: 'OTHER',
                MODES: [Object],
                millis: [Function],
                myrelay: [Object] },

    currentBuffer: [Array],
    currentBuffer: [],

    id: 'D862E31E-59E8-482D-B4B2-FB537C1F1035',
    id: '1EEEE607-229B-444B-9669-6B78C2334A9F',

**Comment by dtex** [comment]
@mdingena Sorry nobody has responded before now. My guess is that it's because you are in somewhat uncharted waters and not too many people are reconnecting dropped boards. It looks like you had started a good investigation. Have you made any progress since you opened this issue?
