### ISSUE TITLE
Stepper Motor BYJ48 always spin in the same direction

### ISSUE THREAD

**Issue by EmaSuriano** [rwaldron/johnny-five#1424]
Hi everybody,
I've been using johnny-five just for turning on LED, using servo motors, and right now I'm starting to do some stuff with stepper motors.
The stepper motor that I'm using is the BYJ48, [here ](http://eeshop.unl.edu/pdf/Stepper+Driver.pdf)you can find technical information about the motor. It's a really cheap motor that works with four wires with 5V.
To accomplish this I'm using the Stepper library from J5, but I found that besides I change the direction the stepper motor always spin in the same direction. This is a snippet of my current code:

``` javascript
  const stepper = new j5.Stepper({
    type: j5.Stepper.TYPE.FOUR_WIRE,
    stepsPerRev: 96,
    pins: [14, 12, 13, 15],
  });

  moveMotor = (steps, cb) => {
    const direction =
      steps > 0 ? j5.Stepper.DIRECTION.CW : j5.Stepper.DIRECTION.CCW;

    return stepper
      .rpm(60)
      .direction(direction)
      .step(steps, cb);
  };

  moveMotor(100, () => moveMotor(-100)); //has to move in CW direction and then CCW
```

I check how is the step phase of this motor and I found that is different from the one of Johnny five.
![image](https://user-images.githubusercontent.com/3399429/33920078-c5e05e60-df9a-11e7-81ff-a9cdc29e148c.png)

Is there a way to change how the Stepper library turn on/off the pins of the driver? 
In the case that I would want to change it in the codebase? Where should I look for, inside Stepper I didn't find anything related to that.

Regards,
Emanuel Suriano

**Comment by mezzab** [comment]
+1

**Comment by EmaSuriano** [comment]
Sorry for posting this issue on J5 repository, I found out that the sequence is provided by the Firmata that you're using on your chip. In my case, I was using [ConfigurableFirmata](https://github.com/firmata/ConfigurableFirmata) and to change it you have to modify  `moveStep()` function inside `src/utility/FirmataStepper`. This is how it looks my code: 

```C
else if (this->interface == FirmataStepper::FOUR_WIRE)
  {
    switch (step_num)
    {
    case 0:
      digitalWrite(motor_pin_1, LOW);
      digitalWrite(motor_pin_2, LOW);
      digitalWrite(motor_pin_3, LOW);
      digitalWrite(motor_pin_4, HIGH);
      break;
    case 1:
      digitalWrite(motor_pin_1, LOW);
      digitalWrite(motor_pin_2, LOW);
      digitalWrite(motor_pin_3, HIGH);
      digitalWrite(motor_pin_4, HIGH);
      break;
    case 2:
      digitalWrite(motor_pin_1, LOW);
      digitalWrite(motor_pin_2, LOW);
      digitalWrite(motor_pin_3, HIGH);
      digitalWrite(motor_pin_4, LOW);
      break;
    case 3:
      digitalWrite(motor_pin_1, LOW);
      digitalWrite(motor_pin_2, HIGH);
      digitalWrite(motor_pin_3, HIGH);
      digitalWrite(motor_pin_4, LOW);
      break;
    case 4:
      digitalWrite(motor_pin_1, LOW);
      digitalWrite(motor_pin_2, HIGH);
      digitalWrite(motor_pin_3, LOW);
      digitalWrite(motor_pin_4, LOW);
      break;
    case 5:
      digitalWrite(motor_pin_1, HIGH);
      digitalWrite(motor_pin_2, HIGH);
      digitalWrite(motor_pin_3, LOW);
      digitalWrite(motor_pin_4, LOW);
      break;
    case 6:
      digitalWrite(motor_pin_1, HIGH);
      digitalWrite(motor_pin_2, LOW);
      digitalWrite(motor_pin_3, LOW);
      digitalWrite(motor_pin_4, LOW);
      break;
    case 7:
      digitalWrite(motor_pin_1, HIGH);
      digitalWrite(motor_pin_2, LOW);
      digitalWrite(motor_pin_3, LOW);
      digitalWrite(motor_pin_4, HIGH);
      break;
    }
  }
```

Also, remember to change this line of code inside `updateStepPosition()` in order to have the possibility of switching between 8 possible stepper's state.
```C
stepMotor(this->step_number % 8, this->direction);
```

I leave my FirmataStepper.cpp attached to this comment anyways.

[utility.zip](https://github.com/rwaldron/johnny-five/files/1565885/utility.zip)
