### ISSUE TITLE
--MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe"-- :Solution

### ISSUE THREAD

**Issue by prakis** [rwaldron/johnny-five#145]
I spent lot of time finding a solution for this, if you are getting the following error 
.....
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe".
 If the component is not installed, either 1) install the Microsoft Windows SDK
 for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual
 Studio 2008.  [C:\nodejs\johnny-five\node_modules\serialport\build\binding.sln]
......

SOLUTION: I guess the following solved my problem (I have Visual studio 2012)

npm install johnny-five -msvs_version=2012

Also if you trying to get the source  and install note that the following line is two commands
git clone git://github.com/rwldrn/johnny-five.git && cd johnny-five

1] git clone git://github.com/rwldrn/johnny-five.git 
2] cd johnny-five
then do 
3]npm install

**Comment by rwaldron** [comment]
I believe this is no longer a problem since node-serialport provides pre-built versions when necessary.
