### ISSUE TITLE
MT3339 GPS Receiver not logging gps data

### ISSUE THREAD

**Issue by william-inf** [rwaldron/johnny-five#1460]
I am trying to do a simple GPS readout using an Arduino UNO and a GPS module (MT3339/PA6H), it appears to connect fine (board showing ready etc), however the "change" event is never hit.  

I was following this example as a guide: [ http://johnny-five.io/examples/gps/](url)  and my code is available here:
[https://gist.github.com/william-inf/02cfe014f3c605abeb7335afb8240104](url)

It is also streaming data when i cat /dev/ttyACM2

Any assistance in debugging would be appreciated

**Comment by dtex** [comment]
I’m not at a computer where I can review the code, but I’ll take a look soon. One quick question, are you outside when you are trying this? GPS receivers need a clear line of site to multiple satellites to get a fix and J5 won’t send any output until it the receiver has a fix

**Comment by dtex** [comment]
```gps.on("sentence", sentence => console.log(sentence) );```

This should fire every time a sentence is received regardless of wether there is a fix, or even if it's a valid setence. A sentence is anything that ends with ```\r\n```.

**Comment by dtex** [comment]
I did some Googling and could not find an implementation of the firmata client for Ruby the wasn't more than a few years out of date. What are you using on the Ruby side? Just trying to identify what might be different.

**Comment by william-inf** [comment]
Its just a small library I wrote myself just using ruby-serialport, I might try the ruby-firmata and see if I can get better results as I am more familiar with Ruby

**Comment by william-inf** [comment]
I just tried this by the way, did not yield a result

`gps.on("sentence", sentence => console.log(sentence) );`

**Comment by dtex** [comment]
I will try to recreate the issue, but won't have access to my equipment until next week (travelling).

If you want to try some other stuff in the meantime, you could edit ```./node_modules/johnny-five/lib/gps.js``` and add ```console.log(new Buffer(data).toString("ascii"));``` at line 324. That should barf out everything the Arduino gets from the GPS wether it's a sentence or not.

**Comment by william-inf** [comment]
Will give this a go and report back, thank you very much for taking the time to help me.

**Comment by william-inf** [comment]
I am getting back some semi formed garbled data, could this be a baud rate issue?  

`$@1
"
"r2B.bBbbbbbbbj1bjGb""5
$PSP)1abBbBbabBbbbbbbN)
*5
DGPRS()"rJb
		j
$0M.00N
$G 1
""
rvBbbBbbbabbj1bJ	R"5
$PSP)1bBbBbabbBbbbcbbN)*5

$PGSV,10b""
G3.,V.0,4,1$T0,,0,03

$GPGGA,14gL"
rBBbbBb	bBbj	):	I	j
DG0G*P)1.bbBbBbcbabBbbbbN)*5

$GPRMC,14rb	rbb"bHe101ri
`

**Comment by dtex** [comment]
Baud rate is the first thing I thought when I saw that. It defaults to 9600.

**Comment by dtex** [comment]
When I say "it defaults to" I mean Johnny-Five assumes the MT3339 will be running at 9600.

**Comment by william-inf** [comment]
The above garbled text is from when I set the baud rate as per the manufacturer documentation to 115200 using:

`    var gps = new five.GPS({
        pins: {
            rx: 11,
            tx: 10
        },
        baud: 115200
    });
`
I have tried adding a frequency param to 10hz (manufacturer specified) to no avail. 

I think I may need to just try a different GPS module!

**Comment by dtex** [comment]
More digging... the Ladybird PA6H defaults to 9600 so I know it's something special about the breakout you are using. 

Also note that if you set the baud rate to anything other than the expected default value, J5 will send a command to change the baud rate on the chip. It may be that your chip is not even defaulting to 115200 (my suspicion), but J5 is trying to make it work at 115200. Try setting it to 57600 or 28800 instead.

**Comment by william-inf** [comment]
I tried lower baud rate, got mixed results. Ultimately, ended up going with an adafruit ultimate gps and never looked back.  

Thanks again for your assistance.
