### ISSUE TITLE
Travis and Appveyor are running a different set of tests

### ISSUE THREAD

**Issue by dtex** [rwaldron/johnny-five#1462]
In ```appveyor.yml```:
````
test_script:
  - npm test
````
and in ```.travis.yml```:
````
before_script:
  - grunt test-examples

script: npm run test-cover

after_success:
 - npm run coveralls
````

Appveyor runs jshint, jscs, and nodeunit but Travis runs nodeunit and coveralls.

I noticed this because 6402aa9d1c6108ca2476c5dd84555149dc2ee95f fails on Appveyor but not Travis.

**Comment by rwaldron** [comment]
I don't want to run the coveralls stuff on appveyor, but J5 should definitely be running `grunt jshint jscs nodeunit` for both, and you're right: it's not! I will get this fixed.

**Comment by rwaldron** [comment]
@dtex all set!
