### ISSUE TITLE
HC-SR04 with backpack and nw.js

### ISSUE THREAD

**Issue by Deathcap420** [rwaldron/johnny-five#1470]
I can successfully load my HCSR04 firmata using interchange install onto a nano, but when I run the i2c backpack hcsr04 javascript code using another arduino nano(not Uno, like in the guide) It will print out in and cm and a big fat 0(zero) repeatedly. my hand isn't being red in front of it

what I dont get is why my node-pixel worked. if I used Node-pixel back pack .  and ran the appropriate code it worked fine. had my Addressable led's flashing.

So, what am i doing wrong. I've checked and double checked the wiring.  i know its not that. if i scan for i2c addresses using an arduino sketch it finds no connections. I'm so close I can feel it!

**Comment by rwaldron** [comment]
Sorry for the delay in responding... Can you share the code you're using for `HCSR04`? Thanks!

> but when I run the i2c backpack hcsr04 javascript code using another arduino nano

Are you connecting the computer to a Nano, which is then connected to another Nano? (via I2C and 5v, Gnd)

**Comment by dtex** [comment]
Could we have an I2C bug somewhere in the stack? #1273 #1481 #1483
