### ISSUE TITLE
bluetooth + j5 on a windows machine

### ISSUE THREAD

**Issue by vettorazi** [rwaldron/johnny-five#1471]
Hey guys, i am writing a article collecting all kinds and formats of connection between machine and boards, using j5.
i already cover the wifi connection, the wired connection, dom+ j5 , etc. but the bluetooth connection is giving me headaches.... 
I configured the board according the tutorial of hm-06 - bluetooth - on j5 website.
but the part of choosing the port it's a little complicated.
how can i see the port name of the board? I am in a windows machine. I connected the board over the bluetooth, in the windows menu and i already tried these names:

> BTHENUM\DEV_98D331304312\7&297C82F3&0&BLUETOOTHDEVICE_98D331304312

and this:

> \Device\00000252

nothing happend.
my code it's like this:

```
var app = require('http').createServer(handler),
     io = require('socket.io').listen(app),
     fs = require('fs')
var EtherPortClient = require("etherport-client").EtherPortClient;
var five = require("johnny-five");

var board = new five.Board({
  port: new EtherPortClient({
    host: "\Device\00000252", 
    port: 3030
  }),
  timeout: 10000,
  repl: false
});

board.on("ready", function() {
  led = new five.Led(13);

  io.sockets.on('connection', function (socket) {
    socket.on('click', function () {
      led.toggle();
    });
  });
});

app.listen(8080);

function handler (req, res) {
  fs.readFile(__dirname + '/index.html',
  function (err, data) {
    if (err) {
      res.writeHead(500);
      return res.end('Error loading index.html');
    }

    res.writeHead(200);
    res.end(data);
  });
}


```

**Comment by developer239** [comment]
@vettorazi Could you please write some simple tutorial on how to make the blink hello world example but with a WIFI connection? 😄 

Something like where `GET server.com/blink` would make the light blink for 500ms.
