### ISSUE TITLE
Support for multiple backpacks?

### ISSUE THREAD

**Issue by jc78** [rwaldron/johnny-five#1476]
I’m looking for tutorials on how to connect multiple backpacks to my main Arduino board. 

Is this even possible? Or am I limited to running only 1 backpack at a time?

Also, can I assume all docs that refer to using a Nano for a backback would also work for a Pro Mini? Or would there be a different setup when using a Mini?

**Comment by MichaelKostin** [comment]
Hi @jc78 ,
Do you mean I2C LCD Backpack? If yes, you have to change I2C address. It works for any I2C device. 
If not, please provide more information about your backpack devices.

**Comment by jc78** [comment]
I think I2C, but I'm a little unclear myself. Is there any other type of backpack?

I was under the impression that non-supported devices like neopixels (SPI) can run off of a piggybacked Nano or Pro Mini. So the device I want to add is not I2C, but I'm assuming that the backpacked Arduino is communicating to the main Arduino through I2C? Is that how it works?

If so, then here are some follow up questions:
- If we can add multiple backpacks, are we limited to the amount of analog pins on the Arduino? I'm currently using an Uno. I'm using 3 of the 6 analog inputs for other components. Does this mean I can only use one backpack to fill the remaining pins? I'm only asking because the backpack examples I've seen show using two analog inputs to make the connection.
- If Nano and Pro Minis are supported as backpacks, can I use a Nano as my main board (to save space) and then backpack another Nano to that?
- The only constants I could find for the "controller" arg when creating a backpack is "XXXXX_I2C_NANO_BACKPACK". Is this interchangeable when using a Pro Mini as a backpack? Meaning I would just use this Nano const?
- I know I can sometimes change the address of an I2C device on the device itself, but If I'm backpacking an SPI device, how do I change the address? is that done in the JS backpack constructor? 
- If I only have room for one backpack, can I run all of my "backpack devices" off of one backpack? There will be plenty of GPIO pins leftover. it seems like a waste to not be able to use them.

Thanks again

**Comment by jc78** [comment]
@dtex, thanks again!! This was very helpful and answered all of my questions.

To answer your question on performance between two talking Nano boards, speed is not a concern of mine. My project has very simple commands and timing issues should never crop up. This is making me wonder what the difference is between an Uno and a Nano? They're both using the 328P chip, so would TX/RX performance be different between an Uno and Nano? Unless I'm misunderstanding your question?

**Comment by dtex** [comment]
I wasn't worried about the Nano. I was worried about i2c over firmata, but it sounds like it's not an issue.

**Comment by dtex** [comment]
@jc78 Is it okay to close this issue? If anything else comes up you are always welcome to open another.

**Comment by jc78** [comment]
Yes, I’m good. Thanks again.
