### ISSUE TITLE
Find correct sensor settings

### ISSUE THREAD

**Issue by nofear87** [rwaldron/johnny-five#1481]
Can you please help to find the correct sensor settings?

I have Pololu 37D Motor with enconders. See https://www.pololu.com/product/1442 -> "Using the Encoder" for detailed information.

I have connected A Output to A6 then starting with this example:

```
var sensor = new five.Sensor("A6");
sensor.on("change", function() {
   console.log(this.value);
 });
```

But getting just curious data between 0-1000. I think I haven't the correct settings now?
Is it maybe an digital signal!? Did I need hardware interupts?

Thanks!

**Comment by nofear87** [comment]
Thanks for fast answer. They spread evenly. 


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Donovan Buck <notifications@github.com> Datum: 28.06.18  20:27  (GMT+01:00) An: rwaldron/johnny-five <johnny-five@noreply.github.com> Cc: nofear87 <iphone@robert-walther.de>, Author <author@noreply.github.com> Betreff: Re: [rwaldron/johnny-five] Find correct sensor settings (#1481) 
Are the values in bunches at the far ends of the 0-1000 range, all at one end, or are the spread evenly? I would expect to see a bunch near 0, then a bunch near 1000, then a bunch near 0, and so on.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rwaldron/johnny-five","title":"rwaldron/johnny-five","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/rwaldron/johnny-five"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dtex in #1481: Are the values in bunches at the far ends of the 0-1000 range, all at one end, or are the spread evenly? I would expect to see a bunch near 0, then a bunch near 1000, then a bunch near 0, and so on."}],"action":{"name":"View Issue","url":"https://github.com/rwaldron/johnny-five/issues/1481#issuecomment-401129555"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rwaldron/johnny-five/issues/1481#issuecomment-401129555",
"url": "https://github.com/rwaldron/johnny-five/issues/1481#issuecomment-401129555",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [rwaldron/johnny-five] Find correct sensor settings (#1481)",
"sections": [
{
"text": "",
"activityTitle": "**Donovan Buck**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@dtex",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"rwaldron/johnny-five\",\n\"issueId\": 1481,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"rwaldron/johnny-five\",\n\"issueId\": 1481\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/rwaldron/johnny-five/issues/1481#issuecomment-401129555"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 351232721\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by dtex** [comment]
Then I would suspect a floating ground. Can I see how the encoders are wired to your microcontroller?

I assume the motor is turning as expected.

**Comment by nofear87** [comment]
@dtex I switch from external power source to mega 5v. And now the values are in bunches at the far ends! I used scaleTo(0,1) to get true and false values. But how can I determine direction and stepas without an interrupt? Thank you!

**Comment by ryangueraa** [comment]
nice

**Comment by joepuzzo** [comment]
I have made this PR for firmata.js https://github.com/firmata/firmata.js/pull/261

**Comment by joepuzzo** [comment]
Seems nobody has checked my PR yet.. anyone know who maintains that package ?

**Comment by joepuzzo** [comment]
In order to use the encoder stuff ( until the people that own firmata.js merge my code ) you need to run this in any new project that wants to use encoder stuff

```bash
 npm i firmata-io@npm:@joepuzzo/firmata-io
```
