### ISSUE TITLE
Support for magnetometer : QMC5883 

### ISSUE THREAD

**Issue by kanishkarj** [rwaldron/johnny-five#1486]
Hey all! I am new to arduino and I have been working with johnny-five recently. My project uses magnetometer and I found that QMC5883 is a popular sensor out in the market. Apparently, Vendors have been selling QMC5883 in the name of HMC5883L. Now, HMC5883 is a sensor supported by johnny-five but the other is not. I request that support for QMC5883 is added to johhny-five, and in fact I would be glad to work in it but ill need some guidance. [this](https://github.com/mechasolution/Mecha_QMC5883L) is the link to QMC5883L library for arduino. Hopefully, that helps.

**Comment by dtex** [comment]
@kanishkarj Of course new contributors are always welcome and it would be great if you wanted to take on the QMC5883. I'm not sure what the differences are from the HMC5883. This could be as simple as aliasing an existing device or you may need to create an entirely new device.

There is some high-level guidance in [contributing.md](https://github.com/rwaldron/johnny-five/blob/master/CONTRIBUTING.md) and of course feel free to ask any questions here on this issue.
