### ISSUE TITLE
Support for LinkIt One ?

### ISSUE THREAD

**Issue by altinselimi** [rwaldron/johnny-five#1488]
Hello everyone,

Is it possible to use johnny-five in the [LinkIt One](https://labs.mediatek.com/en/platform/linkit-one) board ?

**Comment by dtex** [comment]
As I understand it, yes this is possible. The Linkit One is Arduino compatible and can run firmata. Just install standardFirmataPlus onto the LinkitOne using the Arduino IDE.

Note, I haven't actually done this. I'm just inferring from other projects.
