### ISSUE TITLE
Add pre-commit

### ISSUE THREAD

**Issue by dtex** [rwaldron/johnny-five#1490]
This has been helpful for me in some other projects:

https://github.com/observing/pre-commit

It allows you to specify that tests should be run anytime git commit is called and before the code is actually committed. Pretty slick. I imagine we could specify the full test suite be run.

Any interest in having this added to the Johnny-Five repo?

**Comment by AlbertHambardzumyan** [comment]
Perhaps, would be nice to have a lint check script in the pre-commit list. 
Any thoughts?
