### ISSUE TITLE
original keypad of arduino

### ISSUE THREAD

**Issue by kukulako** [rwaldron/johnny-five#1492]
Greetings, why do not I see the original keypad of arduino? to program it, I'm talking about the one they always use in YouTube tutorials, I think it's called keypad 4 x 4 Matrix Array 16 Key Membrane?

**Comment by rwaldron** [comment]
Only because no one has had a chance to write a Controller object for it.

**Comment by dtex** [comment]
@kukulamo Do you have a link to the device for sale or documentation (or code from a different framework or language). That will help whomever decides to take this on.

**Comment by dtex** [comment]
> And if we need to write the controller, I can help.

Thanks for linking the specs. It would be awesome if you'd like to take this on.

**Comment by AlexKutschera** [comment]
Was the required controller added and if so how's it called?
