### ISSUE TITLE
NanoPC T-4

### ISSUE THREAD

**Issue by tarbear123** [rwaldron/johnny-five#1502]
i think that you should add the NanoPC T-4 to supported devices

**Comment by dtex** [comment]
Hi @tarbear123 This is the first request for this board that I've seen. I've added it to the [Requested Features](https://github.com/rwaldron/johnny-five/wiki/Requested-Features#new-boardsio-plug-ins) wiki page. That way we can consolidate and track all the requests.

If anyone wants to take this on I would look into using [linux-io](https://github.com/fivdi/linux-io#readme) as a starting point.
