### ISSUE TITLE
Laser Trip Wire

### ISSUE THREAD

**Issue by msi-matthew** [rwaldron/johnny-five#1519]
What hardware was used in the laser [trip wire example](https://github.com/rwaldron/johnny-five/blob/master/docs/laser-trip-wire.md)?

**Comment by HipsterBrown** [comment]
Looks like it's the Keyes KY-008 Laser Transmitter (https://smile.amazon.com/gp/product/B075T8ZWSN/ref=as_li_tl?ie=UTF8&tag=leaacicarbatf-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B075T8ZWSN&linkId=3c0ab8226ee8880edec77df09c9c1da4).

**Comment by msi-matthew** [comment]
Great. Thank you!!
