### ISSUE TITLE
Board Looking for connected device   why?

### ISSUE THREAD

**Issue by devghb** [rwaldron/johnny-five#1543]
var five = require("/home/pi/Desktop/johnny-five/lib/johnny-five.js");
var board = new five.Board();
console.log("hello world!");
board.on("ready",function(){
	console.log("ready");
	var led= new five.Led(13);
	led.blink(500);
	this.wait(5000,function(){
		led.off();
	});
});

**Comment by dtex** [comment]
@devghb Are you using an Arduino Uno connected to your computer via USB?

**Comment by dtex** [comment]
Closing since there was no response.
