### ISSUE TITLE
Addition of JSON Document of sensors

### ISSUE THREAD

**Issue by AtomicCons** [rwaldron/johnny-five#1550]
Feature Request:
JSON document of supported sensors that can be loaded into the DOM. This could be used as a list or selector for configs. 
Example: 
{
  "component": {
    "Acceleromter": [
      "ADXL335",
      "ADXL345",
      "ANALOG", 
      "LIS3DH",
      "LSM303C",
      "MMA7361",
      "MMA8452", 
      "MPU6050"
    ],
    "Altimeter": [
      "BME280",
      "BMP180",
      "BMP280",
      "MPL3115A2",
      "MS5611"
    ],
  }
}

**Comment by dtex** [comment]
I see how this could be useful, but I worry that it's a "one more thing" to remember to do when contributing. If we add a mechanism to support those tasks automatically (docs, examples, wiki updates, johnny-five.io publishing, etc) that includes or even depends on this sensor registry then I could totally see it happening. 

That means we'd have more than just a list of names. There would be a link to docs and/or an example if one exists.
