### ISSUE TITLE
expander mcp23017 wrong schema

### ISSUE THREAD

**Issue by fair-man** [rwaldron/johnny-five#1551]
![image](https://user-images.githubusercontent.com/11162127/51802471-9cd3b800-225b-11e9-9b40-0e774cf7b35e.png)

please fix this

**Comment by fair-man** [comment]
http://www.alldatasheet.com/view.jsp?Searchword=Mcp23017&gclid=CjwKCAiAyrXiBRAjEiwATI95mYXjwjKSzWBdQqTwzhMq-mvXwNO-PbqrzpH0phK4swdmLGKJ6P_3cxoCnesQAvD_BwE

**Comment by dtex** [comment]
Thanks for the catch. Would you like to submit a PR? It should just be a matter of updating the fzz and png files.

**Comment by PeterArriaza** [comment]
is this still open? If so, I'd be happy to fix this!

**Comment by dtex** [comment]
That would be great.

**Comment by shawnpetros** [comment]
Haven't seen any movement on this in a week, if no one's claimed I can take a shot at it...I'll reference in a PR if I can get it done in the next day or so...

**Comment by dtex** [comment]
Thanks for the reminder. I need to close this.
