### ISSUE TITLE
Is teesy 3.5 supported ?

### ISSUE THREAD

**Issue by Zhairgling** [rwaldron/johnny-five#1552]
Hi all,

I know that the teensy 3 is labeled as supported in the doc but are the others models too ?

Thanks,
Zhairgling

**Comment by dtex** [comment]
Hi @Zhairgling 

Maybe. 

J5 depends on firmata to talk to the teensy so if firmata works, Johnny-Five will work. The firmata team has successfully compiled for teensy 3.5 but has not tested on actual hardware.

https://github.com/firmata/arduino/issues/309

Maybe you could try it out and report back?

**Comment by Buisson** [comment]
I have tried and it works perfectly. On a tensy 3.5.

**Comment by dtex** [comment]
Awesome! Thank you @Buisson
