### ISSUE TITLE
CD4021B implementation

### ISSUE THREAD

**Issue by Buisson** [rwaldron/johnny-five#1553]
Hello everyone,

I want to use a CD4021B shift register for Inputs with Johnny five, I have seen this is a requested feature since 2014. 

I have a question, can I made my own implementation for that component in johnny five ? If yes how ? 

Someone begin to work on it ? Or there is some "hack" to make it works ?

Thanks for reading me :).

**Comment by dtex** [comment]
Hi @Buisson 

This one has come up before in #456. It is listed in the [Requested Features](https://github.com/rwaldron/johnny-five/wiki/Requested-Features) page, and I've added a pinter back here so everyone will know multiple people are looking for this. It just needs a motivated contributor.
