### ISSUE TITLE
serial communication supported or not

### ISSUE THREAD

**Issue by darkworks** [rwaldron/johnny-five#1555]
i wonder if johnny five have any api for serial communication with sensors like DHT11 ( https://www.mouser.com/ds/2/758/DHT11-Technical-Data-Sheet-Translated-Version-1143054.pdf )

i think it will be good if we have some api to get raw serial data from sensors pins then it will change the game and then we can process the data once we have raw untouched data from sensors .

**Comment by dtex** [comment]
This response assumes you are using an Arduino...

Yes, Johnny-Five has support for serial communication, but not the specific serial format that the DHT11 uses. I believe the timing constraints are too tight for it to work within firmata.

The DHT11 still works with Johnny-Five but you have to use an I2C backpack.

http://johnny-five.io/api/thermometer/#dht11i2cnanobackpack

firmata does support the more common two-wire (TX/RX) serial protocol which is not dependent on timing.
