### ISSUE TITLE
PCA9685 with raspberry pi

### ISSUE THREAD

**Issue by mkirank** [rwaldron/johnny-five#1560]
Is it possible to connect the PCA9685 expander board to Raspberry pi and use it without Arduino?
The expander examples show that the expander is attached to Arduino .

Is there some examples on how to do this , in case this is possible.

Apologies for the noob question but I was not able to figure this out.

**Comment by dtex** [comment]
@mkirank Yes, it should work. @nebrius has a few [notes](https://github.com/nebrius/raspi-io#i2c-notes) about working with I2C on the Pi that you should probably check out first.
