### ISSUE TITLE
mixed model AVR2.DLL failed to authorize

### ISSUE THREAD

**Issue by Hamza13102** [rwaldron/johnny-five#1562]
Hi, kindly assist am getting this error when running a simulation in proteous

PROSPICE 8.04.00 (Build 21720) (C) Labcenter Electronics 1993-2016.
mixed model AVR2.DLL failed to authorize - Missing or invalid Customer Key.. [ARD1]
mixed model PIC16EX.DLL failed to authorize - Missing or invalid Customer Key.. [SONAR1]
mixed model PIC16EX.DLL failed to authorize - Missing or invalid Customer Key.. [SONAR2]
Net VSS taken as alias for GND
Loaded netlist 'C:\Users\HAMZA\AppData\Local\Temp\LISA8415.SDF' for design 'arduino two_way.pdsprj'
Real Time Simulation failed to start.
Simulation FAILED due to fatal simulator errors.

**Comment by dtex** [comment]
Hi @Hamza13102 

Take a look at this closed issue comment:

https://github.com/rwaldron/johnny-five/issues/314#issuecomment-38364232

**Comment by prasenjit9862** [comment]
> Hi, kindly assist am getting this error when running a simulation in proteous
> 
> PROSPICE 8.04.00 (Build 21720) (C) Labcenter Electronics 1993-2016.
> mixed model AVR2.DLL failed to authorize - Missing or invalid Customer Key.. [ARD1]
> mixed model PIC16EX.DLL failed to authorize - Missing or invalid Customer Key.. [SONAR1]
> mixed model PIC16EX.DLL failed to authorize - Missing or invalid Customer Key.. [SONAR2]
> Net VSS taken as alias for GND
> Loaded netlist 'C:\Users\HAMZA\AppData\Local\Temp\LISA8415.SDF' for design 'arduino two_way.pdsprj'
> Real Time Simulation failed to start.
> Simulation FAILED due to fatal simulator errors.

Sir I have also same problem please help me

**Comment by prasenjit9862** [comment]
How can I'm solving this problem please help me

**Comment by dtex** [comment]
@prasenjit9862 Did you follow the advice in https://github.com/rwaldron/johnny-five/issues/314#issuecomment-38364232 ?
