### ISSUE TITLE
Johnny Five compatibility .

### ISSUE THREAD

**Issue by satyamchourey** [rwaldron/johnny-five#1563]
Hi I've been trying to play around NodeMCU esp8266. Is it compatible with Johnny five , I am hoping positive as it supports imp cards .?

**Comment by dtex** [comment]
@satyamchourey Sorry nobody responded earlier. Yes, any board that can run firmata will work with Johnny-Five so the esp8266 is good to go.

**Comment by satyamchourey** [comment]
Hello,
Thankyou for your response , better late than never .
I  have tried it already on NodeMCU , observed few bugs and would love to
report them !!!
Thankyou

**Comment by dtex** [comment]
Please do. Speaking for myself I'm really interested in the Espruino offerings so am happy to dig in.
