### ISSUE TITLE
Running on android error

### ISSUE THREAD

**Issue by VRuzhentsov** [rwaldron/johnny-five#1565]
I have modified build config of serialport, so it could compile on Android

Then run an application, and get TypeError
`Cannot read property 'filter' of undefined at ./lib/board.js:56:26`

Error in that function was from node serialport addon `spawn udevadm ENOENT`

It seems you should handle this error. I would do a PR, but you probably ask me to write tests for it.

**Comment by VRuzhentsov** [comment]
Found, that there is no such command `udevadm` in android linux

**Comment by dtex** [comment]
Have you tried asking about this over at https://github.com/node-serialport/node-serialport

Not trying to give you the brush off, but you're more likely to find someone who knows Serialport on Android over there.
