### ISSUE TITLE
SerialPort-HC05-Socket 

### ISSUE THREAD

**Issue by AlexFaru** [rwaldron/johnny-five#1571]
I am trying to make a small web page with some buttons, using, socket, serialport and an HC05 module to communicate with an arduino. But my arduino serial port does not receive anything. It's as if the button does not send the data I want.

var express = require('express');
var app =  express();
var io = require('socket.io')(app.listen(8088));
var SerialPort = require('serialport');

app.use(express.static(__dirname + '/app'));
//app.use(express.errorHandler({ dumpExceptions: true, showStack: true }));
//app.use(express.errorHandler());
app.get('/', function (req,res) { 
  res.sendFile(__dirname + '/index.html');
  var serial_port = new SerialPort("COM4", {
    baudRate: 9600,
    dataBits: 8,
    parity: 'none',
    stopBits: 1,
    flowControl: false
  });
serial_port.on('open', function () {
    console.log('Puerto Abi');
    io.on('connection', function (socket) {
      socket.on('azul', function (){
        console.log('No existe error');
        //setTimeout(function() {
          serial_port.write("B\n");
        //},1500);
      });

      socket.on('verde', function (){
          
      });

      socket.on('rojo', function (){
          
      });

      socket.on('stop', function (){

      });

      socket.on('off', function (){
        
      });

      socket.on('on', function (){
      });

      });

});

  });

/////// Arduino Code ////////

#include <SoftwareSerial.h> //Librería que permite establecer comunicación serie en otros pins
 
//Aquí conectamos los pins RXD,TDX del módulo Bluetooth.
SoftwareSerial BT(10,11); //10 RX, 11 TX.

 
void setup()
{
  BT.begin(9600);
  Serial.begin(9600);
  pinMode(13,OUTPUT);
}
 
void loop()
{
  //Cuando haya datos disponibles
  Serial.print("Hola1  \n");
  if(BT.available())
  {
    Serial.print("Hola");
    char dato=BT.read(); //Guarda los datos carácter a carácter en la variable "dato"
    Serial.print(dato);

      Serial.print(cadena); //Visualizamos el comando recibido en el Monitor Serial
      while(dato ==  'B'){
        digitalWrite(13,HIGH);
        delay(3000);
        digitalWrite(13,LOW);
        delay(3000);
        Serial.print(cadena);
        char dato=BT.read();
     }
  }
}

**Comment by dtex** [comment]
Hi @AlexFaru Sorry nobody has responded before now... It doesn't seem you are using Johnny-Five at all. Did you mean to ask this over in https://github.com/serialport/node-serialport ?
