### ISSUE TITLE
Button setting off another button event

### ISSUE THREAD

**Issue by GoogleSites** [rwaldron/johnny-five#1574]
I'm creating two buttons like this:

const enableButton = new five.Button({ pin: 3 });
const disableButton = new five.Button({ pin: 6 });

I have hold events for both of them:

    disableButton.on('hold', function() {
        motor.stop();
        isEnabled = 1;
        speed = 90;
        
        r = 0;
        g = 255;
        
        rgb.color({ red: r, green: g, blue: 0});
        
        console.log("speed reset to: " + speed);
    });    

    enableButton.on('hold', function() {
        motor.stop();
        isEnabled = 0;
        
        if (speed < 255 ) {
            speed = speed + 15;
            console.log(speed);
            sleep(100);
            
            r = speed;
            g = 255 - speed;
            
            rgb.color({ red: r, green: g, blue: 0});
        }
    });

And when I hold down the enableButton, **sometimes** it emits the disableButton event.

**Comment by dtex** [comment]
Can we see a picture of your wiring?
