### ISSUE TITLE
Update docs to include `board` param

### ISSUE THREAD

**Issue by dtex** [rwaldron/johnny-five#1575]
There is an optional ```board``` param than may be passed in the constructor opts for all device classes. Simply put, it allows the user to specify which board they want to use in projects that have multiple boards. It is currently not documented anywhere and should probably be added to all the classes.

**Comment by leonlafa** [comment]
More than happy to update the docs if this is still a requirement.

**Comment by dtex** [comment]
That would be great. Make sure you note how the docs are built. It's covered in the last paragraph of the [writing documentation section](https://github.com/rwaldron/johnny-five/blob/master/CONTRIBUTING.md#writing-documentation)

**Comment by leonlafa** [comment]
@dtex I will make sure to follow the documents.  
I do have a couple of questions before I begin:

1) What is the property name, type, value, and description of the param?
2) Is this param exclusive to the board component class?

**Comment by dtex** [comment]
The param name is "board" and it's available to all the device classes (LED, motor, GPS, whatever). Note that Animation, Board, Boards, and Fn are not device classes. 

You can only pass a board instance. 

It's only necessary when you are using multiple boards. The default value is the first board mounted.

The description would be something like "The board instance your LED* is connected to".  *Or whatever the device is.

I propose editing one class wiki page and running it by @rwaldron before updating them all. In retrospect, you may not need to worry about my warning to note how the docs are built. This will all be in the wiki.

**Comment by leonlafa** [comment]
@rwaldron I have updated the LED wiki page.  Please review before I amend any more pages.

**Comment by leonlafa** [comment]
> @rwaldron I have updated the LED wiki page. Please review before I amend any more pages.

Anyone had a chance to review yet? @dtex @rwaldron

**Comment by dtex** [comment]
I have, and it looks fine to me.

**Comment by leonlafa** [comment]
@dtex okay that's good I'll commit to going through all of the wikis this weekend and doing the same.

**Comment by ibrahim-sowunmi** [comment]
Has this been done?

**Comment by Bazel7** [comment]
Super
