### ISSUE TITLE
LCD 20x4 cursor is offset

### ISSUE THREAD

**Issue by Tim3Game** [rwaldron/johnny-five#1579]
Hello,
I wanted to create a simple arduino project for displaying things like: PC Stats, Server Stats, maybe weather, time and other stuff. I had my box with an Arduino Uno and an LCD 20x4 with an I2C for a long time and didn't used it, so I decided to create something with the help of NodeJS and Johnny Five. I found the example on the LCD I2C, and after I found the correct controller and port, it worked... but with an offset... So when you set `cursor(0,0)` it should be at the top left (0,0), but on my lcd it shows from the middle (10,2 ("box" 11,3)), and when you set `cursor(2,0)` then it's on the top row, but starts from the middle...

**Code:**
```var five = require("johnny-five");
var board = new five.Board({    
    port: 'COM5',
});

board.on("ready", function() {

  var lcd = new five.LCD({
    controller: "PCF8574T",
    rows: 4,
    cols: 20,
  });

  lcd.useChar("heart");

  lcd.cursor(0, 0).print("hello :heart:");

  lcd.blink();

  lcd.cursor(1, 0).print("Blinking? ");
});
```

**Image of LCD:**
![IMG_20190525_135314](https://user-images.githubusercontent.com/34278596/58369121-6b5fb600-7ef6-11e9-870d-faac7c7448ea.jpg)

**Comment by dtex** [comment]
> after I found the correct controller

Was this "keep trying until you find one that works" or are you definitely running a PCF8574T?

**Comment by Tim3Game** [comment]
Im definitely running a PCF8574T, but in the documentation it looks like you can only choose one of the 3 written, but a bit lower I found mine, so I used that (mine)
![image](https://user-images.githubusercontent.com/34278596/58406054-14c6b900-8069-11e9-8d85-3ee881ce693e.png)
![image](https://user-images.githubusercontent.com/34278596/58406065-1a240380-8069-11e9-89ca-cc850efe367a.png)
