### ISSUE TITLE
Add close event to board docs

### ISSUE THREAD

**Issue by gsasouza** [rwaldron/johnny-five#1587]
Official docs doesn't have close event referenced in this issue #1037. I add this event to wiki, but I didn't find where to update on docs.

**Comment by rwaldron** [comment]
Deploying the website is currently broken due to some nonsense upgrades that were done without consulting me. I don't have time to fix it 🤷🏼‍♂️

**Comment by gsasouza** [comment]
Has an issue for it? I can help :)
