### ISSUE TITLE
i want my raspi 3b+ communicate with arduino.but this Platform looks like no support?

### ISSUE THREAD

**Issue by Nathanlee2010** [rwaldron/johnny-five#1616]
Please forgive me for taking the liberty, I am a nodejs lot beginner, I did not see any communication instructions for Bluetooth, wifi, rf, ir, zigbee on this platform from the api documentation.Does this mean that I can't communicate with devices like esp8266 through this library?

**Comment by HipsterBrown** [comment]
@Nathanlee2010 There is a tutorial for controlling an ESP8266 with johnny-five here -> https://boneskull.com/how-to-use-an-esp8266-with-johnny-five/ or here -> https://www.instructables.com/id/ESP8266-Firmata-J5-NodeBot/

The ["host computer"](https://boneskull.com/how-to-use-an-esp8266-with-johnny-five/#installjohnnyfivenodejsmodules) in those tutorials would be your raspi.
