### ISSUE TITLE
Remove a listener at a button event

### ISSUE THREAD

**Issue by ciarlystreet** [rwaldron/johnny-five#1634]
Hello,
is it possible to remove a listener at a button event?

Example: 

```
const { RaspiIO } = require("raspi-io");
const five = require("johnny-five");

const board = new five.Board({
  io: new RaspiIO()
});

const ledRed = new five.Led("GPIO27");
const btnRed = new five.Button("GPIO23");

function btnRedOnePressCallback() {
  console.debug("btnRedPressCallback");
  ledRed.on();

  btnRed.off("press"); // what i would like
}

const start = () => {
  btnRed.on("press", btnRedOnePressCallback);
  // ..
};
const processExit = () => {
  ledRed.off();
};

board
  .on("ready", () => {
    start();
  })
  .on("exit", () => {
    processExit();
  });
```

Any help would be appreciated.

**Comment by dtex** [comment]
Yes you can remove a listener:

````js
btnRed.removeListener("press", btnRedOnePressCallback);
````

However, I think the easiest approach here is to use ```once``` so the listener only fires one time.

````js
const start = () => {
  btnRed.once("press", btnRedOnePressCallback);
  // ..
};
````

All Johnny-Five classes are instances of node.js event emitters which are documented [here](https://nodejs.org/api/events.html). It's not the most thorough documentation around, but at least you can see all the methods that are available to you.
