### ISSUE TITLE
Grove TH02 with Raspberry PI 4

### ISSUE THREAD

**Issue by Tsogodar** [rwaldron/johnny-five#1638]
Hey all

This sensor will work with Raspberry PI 4?

[https://botland.com.pl/pl/grove-czujniki-temperatury-wilgotnosci-i-cisnienia/4413-grove-th02-czujnik-temperatury-i-wilgotnosci-i2c.html](https://botland.com.pl/pl/grove-czujniki-temperatury-wilgotnosci-i-cisnienia/4413-grove-th02-czujnik-temperatury-i-wilgotnosci-i2c.html)

Thanks

**Comment by fivdi** [comment]
Johnny-Five supports the TH02. An example of it's usage on an Arduino Uno can be seen at http://johnny-five.io/examples/multi-TH02/. It should also work on a Raspberry Pi 4.
