### ISSUE TITLE
Wrong auto connect to port

### ISSUE THREAD

**Issue by AlexandreMouyen** [rwaldron/johnny-five#1644]
Hello,

My "new five.Board()" auto connect is not working correctly. The lib tries to connect to the COM1 instead of the COM3 where my Arduino Leonardo is.

![image](https://user-images.githubusercontent.com/27637370/70376912-7d42fc80-190e-11ea-98f7-196da007a409.png)

Where I manually set the COM3, it is working properly.

Firmata 2.5.8.
Johnny Five 1.3.1

Do you have an idea?

Thanks.

**Comment by Apoorve73** [comment]
Hello Sir! May be the baud rate isn't matching or I would prefer doing it manually.

**Comment by vilelalabs** [comment]
> Hello,
> 
> My "new five.Board()" auto connect is not working correctly. The lib tries to connect to the COM1 instead of the COM3 where my Arduino Leonardo is.
> 
> ![image](https://user-images.githubusercontent.com/27637370/70376912-7d42fc80-190e-11ea-98f7-196da007a409.png)
> 
> Where I manually set the COM3, it is working properly.
> 
> Firmata 2.5.8. Johnny Five 1.3.1
> 
> Do you have an idea?
> 
> Thanks.

did you solved? getting this error too.
