### ISSUE TITLE
Is there any chance Johnny Five projects will run without a cable in the future?

### ISSUE THREAD

**Issue by abbrechen** [rwaldron/johnny-five#1664]
Hi,

my last experience one year ago was that every project I wanted to run on my Arduino needed a terminal command and a connection cable between the Arduino and the PC. Is there any chance to evade this workflow in the future? Like we already know it from native Arduino projects.

**Comment by dtex** [comment]
Hi @abbrechen ,

This is a common question, and yes it is possible to run Johnny-Five "onboard" but not with an Arduino. Johnny-Five requires node.js and microcontrollers like those used in Arduinos just don't have the resources to run that. However, there are single-board computers (SBC's) that can run node.js and Johnny-Five and also have the built-in GPIO we need to interface with hardware. The two most popular SBC's for Johnny-Five are the Raspberry Pi, and the Tessel 2.

If you are fairly new to all this, the Tessel 2 is a lot easier to get up and running with, but the Raspberry Pi will give ou more power and flexibility. Check out [raspi-io](https://www.npmjs.com/package/raspi-io) to get started with the pi, or [tessel-io](https://www.npmjs.com/package/tessel-io) to get started with the T2.
