### ISSUE TITLE
Passing an array of targets to Animation constructor is not supported

### ISSUE THREAD

**Issue by dtex** [rwaldron/johnny-five#1671]
This code should work but throws: TypeError: this.target[Animation.normalize] is not a function

````js
const { Animation, Board, Led } = require("johnny-five");
const board = new Board();

board.on("ready", () => {
  const led1 = new Led(11);
  const led2 = new Led(12);

  const animation = new Animation([led1, led2]);

  animation.enqueue({
    easing: "linear",
    duration: 500,
    cuePoints: [0, 1],
    keyFrames: [ [0, 255], [0, 255] ],
    metronomic: true
  });

  board.wait(12000, () => {
    animation.stop();
  });
});
````
When normalize is called on an array we need to call normalize on each member of the array.

**Comment by aditya6752** [comment]
hey, can you please tell me that what is the bug in this?

**Comment by dtex** [comment]
I'm probably oversimplifying it, but [this bit of code](https://github.com/rwaldron/johnny-five/blob/master/lib/animation.js#L397-L398) should behave differently when the target is an array. Something like:

````js
// Run through the target's normalization
if (Array.isArray(this.target) {
  this.target.forEach((device, index) => {
    keyFrameSet[index] = this.target[index][Animation.normalize](keyFrameSet[index]);
  });
} else {
  keyFrameSet = this.target[Animation.normalize](keyFrameSet);
}
````

I'm sure it's more complicated than this. Will definitely need new tests.

**Comment by ScreamZ** [comment]
Same issue for SERVO, has to use Servos or Servo.Collection
