### ISSUE TITLE
Keyboard.write() alternative in Johnny-five? (Sending keystroke with single switch button)

### ISSUE THREAD

**Issue by w90** [rwaldron/johnny-five#1683]
Is there a way to send keystroke to my PC with J5 using a single Switch hardware element on my breadboard?
I know about http://johnny-five.io/api/keypad/, the thing is - I'd like to program a single switch button to send the keystroke.
Thanks for any help!

**Comment by dtex** [comment]
Well, there's this [module](https://www.npmjs.com/package/node-key-sender) but it requires a JRE. What app/device will be listening for the keystroke? Maybe there is a cleaner solution.

**Comment by w90** [comment]
I plan for arduino to gather keystrokes from multiple switch-buttons and then my react.js-app should catch them and handle all the sync/async logic. Thanks for a possible way to do this!

**Comment by w90** [comment]
I have found this npm package, works like a charm!
https://www.npmjs.com/package/robotjs

**Comment by dtex** [comment]
That's great. Good luck on your project.
