### ISSUE TITLE
GPS(neo6mv2) Esp8266

### ISSUE THREAD

**Issue by fcoiuri** [rwaldron/johnny-five#1685]
Hello, I'm trying to do the example of Gps with an Esp8266, but the function gps.on ("change") is never reached, I have already tried changing the port, the baud, but the function is never executed.
My code:

    
    const { Board, GPS } = require("johnny-five");
    var EtherPortClient = require("etherport-client").EtherPortClient;
    var board = Board({
        port: new EtherPortClient({    
               host: "192.168.0.112", // IP ESP8266
               port: 3030
       }),
        timeout: 10000,
        repl: true,
        debug: true    
    });
 
    board.on("ready", () => {

    console.log("READY!");
    var gps = new GPS({
        pins: {
            rx: 10, //10
            tx: 11, //11
        },
        // baud: 115200,
        // port: "COM7"
    });

    console.log("Ok")
        //gps.on("sentence", sentence => console.log(sentence));

    gps.on("change", position => {
        console.log("...")
        const { altitude, latitude, longitude } = position;
        console.log("GPS Position:");
        console.log("  latitude   : ", position.latitude);
        console.log("  longitude  : ", position.longitude);
        console.log("  altitude   : ", position.altitude);
        console.log("--------------------------------------");
    });

    // If speed, course change log it
    gps.on("navigation", velocity => {
        const { course, speed } = velocity;
        console.log("GPS Navigation:");
        console.log("  course  : ", course);
        console.log("  speed   : ", speed);
        console.log("--------------------------------------");
    });
    });

Console: 
![1](https://user-images.githubusercontent.com/23100447/83916504-ae7c7800-a74b-11ea-87be-fb3548534dfe.PNG)

My gps: neo-6m-0-001 gy-neo6mv2

**Comment by dtex** [comment]
What do you see if you add this:

````js
gps.on("message", msg => {
  console.log(msg);
});
````

**Comment by FranciscoIuri** [comment]
Nothing happens.

**Comment by dtex** [comment]
In that case, I suspect the serial setup, but since I haven't personally used serial with ESP8266 and EtherPortClient I want to make sure it really works. I think I have all the components and will try it out tonight after work.

**Comment by FranciscoIuri** [comment]
Ok, i will wait, thanks.

**Comment by dtex** [comment]
Okay, I set it up and am seeing the same results. I traced it down to firmata not emitting the serial messages when running on the ESP8266 so I think we need to open an issue on that repo.

**Comment by dtex** [comment]
Before I bother the firmata maintainer, I'm going to do a little more testing.

**Comment by FranciscoIuri** [comment]
Ok, I'm using StandardFirmataWiFi.

**Comment by FranciscoIuri** [comment]
I don't think it's a problem with Firmata, because I can execute this code:

    var EtherPortClient = require("etherport-client").EtherPortClient;
    var five = require("johnny-five");
    var board = new five.Board({
        port: new EtherPortClient({
            host: "192.168.0.112", // IP ESP8266
            port: 3030
        }),
        timeout: 10000,
        repl: true,
        debug: true
    });


    const LED_PIN = 2;

    board.on('ready', () => {
        board.pinMode(LED_PIN, five.Pin.OUTPUT);
        // the Led class was acting hinky, so just using Pin here
        const pin = five.Pin(LED_PIN);
        let value = 0;
        setInterval(() => {
            if (value) {
                pin.high();
                value = 0;
            } else {
                    pin.low();
                    value = 1;
               }
        
        }, 500);
    });

**Comment by dtex** [comment]
Yes, but this uses digital, not serial. Serial on ESP8266 is the combination I'm worried about.

**Comment by FranciscoIuri** [comment]
Any news?

**Comment by dtex** [comment]
Yes, there are some issues using Serial with wifi firmata. The firmata maintainer gave me some things to try, but I'm a little out of my element so don't hold your breath. It would be a lot easier (for me) if it were a Johnny-Five issue.

**Comment by dtex** [comment]
FYI https://github.com/firmata/ConfigurableFirmata/issues/97
