### ISSUE TITLE
Support for generic flame sensors

### ISSUE THREAD

**Issue by meerasndr** [rwaldron/johnny-five#1687]
Does Johnny-Five support generic flame sensors? The documentation and examples mention the Intel Edison + Grove sensor, but I don't get this in my country. Would something like KY-026 work? Thanks.

**Comment by dtex** [comment]
@meerasndr The KY-026's I found on the web have two outputs. One digital (if a flame is detected) and one analog (0-1023 depending on flame intensity). The Intel Edison + Grove sensor example will work for the digital output (or you could just use Switch) and then you can set up a second, generic sensor instance to read the analog value.

**Comment by meerasndr** [comment]
Thanks @dtex . I'll play around with this and post my findings here.

**Comment by meerasndr** [comment]
Yes please!
