### ISSUE TITLE
Add missing types for TypeScript

### ISSUE THREAD

**Issue by jas777** [rwaldron/johnny-five#1688]
I've copied the example code for MCP23017, installed `johnny-five` and `@types/johnny-five` but the types `Virtual`, `Expander` and `Leds` are missing. I'm pretty sure other types may be missing too, so if you could please add them it'd be amazing <3

**Comment by dtex** [comment]
Hi @jas777, Definitely Typed is a separate project and is maintained over at https://github.com/DefinitelyTyped/DefinitelyTyped 

I encourage you to head over there and make a pull request.
