### ISSUE TITLE
lcd.createChar() not documented?

### ISSUE THREAD

**Issue by Caleb-Irwin** [rwaldron/johnny-five#1689]
I noticed that this is not documented in the lcd api page and I don't know why. I could not find it in any of the documentation, but I typed it into the repl and there was a valid function. It takes a name (String) and an array of hex numbers. You can some of those arrays in the /lib/lcd-chars.js file. Am I looking in the wrong place or is this not documented at all?

**Comment by Caleb-Irwin** [comment]
Yes that's perfect

**Comment by dtex** [comment]
Cool. Next time the site gets published, the docs will be updated there too.

Thanks!

**Comment by Caleb-Irwin** [comment]
go [here](https://github.com/rwaldron/johnny-five/blob/master/lib/lcd-chars.js) to see what the the original characters are defined as.
