### ISSUE TITLE
lcd.cursor  is not updating correctly with condition loop

### ISSUE THREAD

**Issue by theoriginalkaiju** [rwaldron/johnny-five#1692]
I can't use auto scroll () or find documentation about it, so I decided to try to make my own "scroll" for messages longer than 32 characters (my LCD is 2x16), the first 2 if else work normally
I already tested the loop through console.log and the logic does not present any error but the characters continue to be displayed only on the first line (even when cursorIndicator turns 1)

        app.post('/', function(req, res) {
        lcd.clear()
        var msg = req.body.msg
        if(msg.length <= 16){
            
           lcd.cursor(0,0).print(msg);
        }
        if (msg.length >= 16 && msg.length <= 32){
            msg1 = msg.slice(0,16);
            msg2 = msg.slice(17.32);
            lcd.cursor(0, 0).print(msg1);
            lcd.cursor(1, 0).print(msg2);
        }
        var n = 0
        var cursorIndication = 0
        if (msg.length > 32){
            console.log("greater than 32")
            
            while (n < msg.length){
                lcd.cursor(cursorIndication, n).print(msg.slice(n,n+1))
                if(n == 16){
                    cursorIndication = 1
                }
                
                console.log(msg.slice(n,n+1))
               
                n = n + 1
                setTimeout(() => {  }, 1000);
            }
        }
        res.send(req.body.msg); 
    });

**Comment by fivdi** [comment]
The valid visible column positions on a 16x2 LCD display are 0 through 15, however

on the 17th iteration of the loop n === 16 and n is passed to `lcd.cursor` as the column position but there is no visible column 16
on the 18th iteration of the loop n === 17 and n is passed to `lcd.cursor` as the column position but there is no visible column 17
...
on the 33rd iteration of the loop n === 32 and n is passed to `lcd.cursor` as the column position but there is no visible column 32
on the 34rd iteration of the loop n === 33 and n is passed to `lcd.cursor` as the column position but there is no visible column 33
...

The following line of code in the loop most likely doesn't do what it is expected to do. It tells the JavaScript run-time to run an empty function that does nothing in one second. It doesn't delay program execution for one second which I think is the intention.
```
            setTimeout(() => {  }, 1000);
```
