### ISSUE TITLE
Can't Read Pin State

### ISSUE THREAD

**Issue by lachlancresswell** [rwaldron/johnny-five#1715]
**Board:** Arduino Uno
**Shield:** None 
**Hardware you are having an issue with:** [End Stop](https://www.makerstore.com.au/product/elec-3d-endstop/)
**Version of Johnny-Five:** johnny-five@2.0.0
**Node version:** 12.19.1
**What your expectations are:** Johnny-five implementation of basic digital read circuit to work identically to the Arduino IDE version
**What the actual outcome is:** 
Connecting a button between pins 11 and GND and running the below Arduino IDE code works as expected with the LED changing state depending on the button. Running the JS code implementation does not cause the LED to work or the console to output any logging. I have used the Pin class to also read the status and, while it will read the status and update once the button is pressed, the state is held and does not return once the button is let go (e.g changes from 1 to 0 when button is pressed but does not return to 0 on letting go). The same code in Arduino IDE works as expected.
Steps to reproduce (including code samples):

**Working Arduino IDE code:**
```
void setup() {
  Serial.begin(9600); //start serial connection
  digitalWrite(11, HIGH); //configure pin 2 as an input and enable the internal pull-up resistor
  pinMode(13, OUTPUT); // LED
}

void loop() {
  int sensorVal = digitalRead(11); // Read state
  Serial.println(sensorVal); // Log state
  digitalWrite(13, sensorVal); // Show state on LED
}
```

**JS code which is not working:**
```
const { Pin, Board } = require("johnny-five");
const board = new Board();

const HIGH = 1;
const LOW = 0;

board.on("ready", () => {
	board.digitalWrite(11, HIGH); // Enable pullup resistor
	board.pinMode(13, Pin.OUTPUT); // LED
	board.digitalRead(11, (state) => {
		console.log(state); // Log state
		board.digitalWrite(13, state); // Display state at LED
	});
});
```
The board is correctly discovered and the console outputs the following on start:
```
1606263027213 Available /dev/tty.usbserial-1420  
1606263027221 Connected /dev/tty.usbserial-1420  
1606263031091 Repl Initialized  
```

**Comment by dtex** [comment]
If you want to write it this way, you should just use firmata.js, but using Johnny-Five device classes would make it easier. It would also give you some bonus functionality like debounce on your button and more control over your LED.

````js
const { Board, Button, Led } = require("johnny-five");
const board = new Board();

board.on("ready", () => {
  const led = new Led(13);
  const button = new Button(11);

  button.on("press", () => { led.on();} );
  button.on("release", () => { led.off();} );
});
````

http://johnny-five.io/api/button/
http://johnny-five.io/api/led/
