### ISSUE TITLE
RFID

### ISSUE THREAD

**Issue by thesurferdude** [rwaldron/johnny-five#1725]
I would love to be able to control my electronics with RFID.
I have this kind of sensor but got it in a kit:
https://www.banggood.com/da/RC522-RFID-RF-IC-Card-Sensor-Module-Writer-Reader-IC-Card-Wireless-Module-p-1460338.html?rmmds=detail-left-hotproducts&cur_warehouse=CN

thanks, 
Frede

**Comment by dtex** [comment]
Frede,

What this needs is a motivated contributor.

That sensor uses SPI for communication which isn't supported by firmata. The first step would be to get SPI landed in firmata (or whatever IO you want to use). Once that exists an RFID class can be created for Johnny-Five that includes this particular sensor. There have been a couple of requests for RFID in the past so you are not alone. #1108 #804

I've added this to the Johnny-Five [Requested Features wiki page](https://github.com/rwaldron/johnny-five/wiki/Requested-Features#new-modules).

The addition of SPI would be a boon for other types of sensors as well.
