### ISSUE TITLE
LCD Turns on but nothing happens

### ISSUE THREAD

**Issue by vimark1** [rwaldron/johnny-five#1731]
I have a LCD board `1602A` https://funduino.de/DL/1602LCD.pdf

I have it connected to my Arduino uno in  the approach described in http://johnny-five.io/api/lcd/#i2c-pcf8574-generic

When I run all looks good.
![image](https://user-images.githubusercontent.com/44329742/123376422-8f62b980-d5de-11eb-8e3c-0eddcf437fae.png)

But the LCD will only stay on this state
![image](https://user-images.githubusercontent.com/44329742/123376830-3f382700-d5df-11eb-96ee-6965a520446d.png)

Code
```js

var five = require("johnny-five");
var board = new five.Board();

board.on("ready", function() {
  // I2C LCD, PCF8574
  const lcd1 = new five.LCD({ 
    // controller: "PCF8574"
    // controller: "PCF8574A"
    // controller: "PCF8574T"
    controller: "PCF8574AT"
  });

  lcd1.print('Hello');

  // lcd1.off();

});
```
What am I doing wrong?

**Comment by dtex** [comment]
Have you checked the contrast control potentiometer?

Can you show us the wiring? Specifically SDA and SCL pins at both ends (power looks fine)

**Comment by vimark1** [comment]
@dtex thank you for your reply.  I'm actually using this wiring. https://create.arduino.cc/projecthub/arduino_uno_guy/i2c-liquid-crystal-displays-5b806c
But even the arduino example doesn't work, so I'm thinking there's an issue with this lcd board.

**Comment by vimark1** [comment]
> Have you checked the contrast control potentiometer?

thank you. that looks better now, will try running something again
![image](https://user-images.githubusercontent.com/44329742/123492696-596d1600-d66e-11eb-96f5-803be4f5cde5.png)

**Comment by vimark1** [comment]
![image](https://user-images.githubusercontent.com/44329742/123492904-f4fe8680-d66e-11eb-9f2c-adb200ef6428.png)
the arduino example is working.. thank you very much, will close this issue

**Comment by iamisti** [comment]
would be good to know what was the issue, because now i'm having the same problem

**Comment by iamisti** [comment]
you are my only hope now @vimark1 
I've tried everything but I only get the backlight and no characters are showing.
