### ISSUE TITLE
Old serialport (< 10.x.x) usage

### ISSUE THREAD

**Issue by lucas-sg** [rwaldron/johnny-five#1780]
I believe that an old version of serialport is being used. The current serialport (10.3.0) doesn't make use of @serialport/bindings, instead it uses @serialport/bindings-cpp. I'd love to use the current serialport version as it's compatible with the latest Electron version and I'm not forced to use Electron v12 or below.

Is there any way I could help updating this package so that this can be solved?

**Comment by code-valor** [comment]
Same. I get error that saying "serialport.list is not a function". I'm getting cold from this package...

**Comment by MiguelRavagnani** [comment]
Still an issue.

I was able to make It work by downgrading serialport to 9.2.8

**Comment by iamisti** [comment]
wow this is still open?
