### ISSUE TITLE
Joystick event "axismove" used in examples

### ISSUE THREAD

**Issue by ChristophLabacher** [rwaldron/johnny-five#1810]
There are several example using a joystick event called `axismove`: https://github.com/rwaldron/johnny-five/search?q=axismove&type=code

According to the [documentation](https://johnny-five.io/api/joystick/#events) and the Joystick code, this event does not exist (anymore?)

Is this correct and should the examples be updated? Happy to submit a PR.

**Comment by dtex** [comment]
You are correct. It looks like the event was changed to `change` back in e526cf6a8acf669af3d392dae7ef08968068a827. A PR for this would be welcome.

**Comment by ChristophLabacher** [comment]
@dtex Thanks for the fast response! I submitted a PR: https://github.com/rwaldron/johnny-five/pull/1811
