### ISSUE TITLE
Docs for Switch (consolidate with Button?)

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#197]
Add docs for Switch (consolidate with Button?) to [wiki](https://github.com/rwldrn/johnny-five/wiki/)

**Comment by rwaldron** [comment]
http://johnny-five.io/api/switch/

**Comment by Resseguie** [comment]
@rwaldron that link 404's currently. Is there supposed to be `switch` docs somewhere?

**Comment by rwaldron** [comment]
Doh. I just typed it out assuming it was done and never actually looked. What an ass.

**Comment by rwaldron** [comment]
- https://github.com/rwaldron/johnny-five/wiki/Switch
- http://johnny-five.io/api/switch/
