### ISSUE TITLE
Sonar 4pin moudule

### ISSUE THREAD

**Issue by cetchells** [rwaldron/johnny-five#235]
I have a 4pin sonic module - hc-sr04. The pins are marked vcc,trig,echo,grd.
I get a signal on echo, but its constant 0.5 inches. I guess I need the trig wired up. Any ideas, or can we add support for this module?

**Comment by BrianKrohn** [comment]
I just followed the instructions on the Ping page to enable ping using the copy/paste of the code listed there and uploading.  The sensor returns "Object is undefined".

**Comment by dtex** [comment]
@BrianKrohn Can you paste your code and the full text from the error

**Comment by BrianKrohn** [comment]
I am using the nodejs code from the Usage section: https://github.com/rwaldron/johnny-five/wiki/Ping
I am using the Firmata modifications at the bottom of that page (from the section titled "Or...").
Everything runs, but the code outputs "Object is undefinedinches away".
I am using an HC-SR04 module wired as described on the page.

**Comment by rwaldron** [comment]
@BrianKrohn I just followed your steps and can't reproduce. The thing that's bugging me is that there is no way that `this.in` or `this.inches` would be `undefined`, because they are always defined. Even if the internal value is `null`, the value returned by those accessors would be `0`. Any other information you can provide would helpful.

**Comment by BrianKrohn** [comment]
Sorry, but that's it.  Being relatively new to this, I tried to stick to your instructions.  Could it be an issue with the Firmata code on that page?  I pasted it as-is into the Arduino IDE, and it uploaded without error.  After uploading I was able to run simple nodejs scripts to strobe an LED and read from a pot.

**Comment by rwaldron** [comment]
> Could it be an issue with the Firmata code on that page?

No, I just used the same code with no issues

...

Can you paste your _exact_ JS code that's running when this issue is encountered?

**Comment by BrianKrohn** [comment]
```javascript
var five = require("johnny-five");
var board = new five.Board({port:"COM4"});
 
board.on("ready", function() {
 
  var ping = new five.Ping(7);

  // ping.in
  //
  // Calculated distance to obstruction in inches
  //

  // ping.cm
  //
  // Calculated distance to obstruction in centimeters
  //

  ping.on("change", function(err, value) {
    console.log("Object is " + this.in + "inches away");
  });

});
```

**Comment by rwaldron** [comment]
Run this and paste the output: 

```js
var five = require("johnny-five");
var board = new five.Board({port:"COM4"});

board.on("ready", function() {

  var ping = new five.Ping(7);

  console.log(ping.inches);

  ping.on("change", function(err, value) {
    console.log("Object is " + this.in + "inches away");
  });

});
```

**Comment by BrianKrohn** [comment]
FYI, I won't have a chance to try this until tomorrow morning.

**Comment by rwaldron** [comment]
No worries, I'm patient. I just want to help you solve this :)

**Comment by BrianKrohn** [comment]
The output was:
1424388317856 Connected COM4
1424388317857 Repl Initialized
>> 0
Object is undefinedinches away
Object is undefinedinches away
Object is undefinedinches away

**Comment by BrianKrohn** [comment]
The output was:
```
1424388317856 Connected COM4
1424388317857 Repl Initialized
>> 0
Object is undefinedinches away
Object is undefinedinches away
Object is undefinedinches away
```

**Comment by rwaldron** [comment]
Ok, try this then: 

```js
var five = require("johnny-five");
var board = new five.Board({port:"COM4"});

board.on("ready", function() {
  var ping = new five.Ping(7);

  ping.on("change", function(err, value) {
    console.log("Object is " + this.inches + "inches away");
  });
});
```
