### ISSUE TITLE
new behavior in Firmata

### ISSUE THREAD

**Issue by soundanalogous** [rwaldron/johnny-five#261]
A change was made in the configurable branch of Firmata that may be of interest to Firmata client library developers. The change is that sending a command to enable a digital port, a digital message will immediately be returned containing the pin values for that port (previously there was no way to query the port value... you had to wait for a pin change to occur on a port). The same change was made when enabling an analog pin. Upon enable the current analog read value will be reported. This change has only been implemented in ConfigurableFirmata. Please test with johnny-five and let me know if you encounter any unexpected behavior. Once this proves to be stable with a few client libraries this new behavior will be implemented in StandardFirmata as well.

Here is the change that was made in the `configurable` branch:
https://github.com/firmata/arduino/pull/104/files

**Comment by rwaldron** [comment]
I have never encountered issues with Configurable Firmata
