### ISSUE TITLE
Microphone support

### ISSUE THREAD

**Issue by taktran** [rwaldron/johnny-five#264]
Hi,

I've gotten my hands on this microphone: https://www.sparkfun.com/products/9868, and wondering if johnny five supports it. I've gotten it working on arduino with the following code, that makes a LED light up based on the volume:

```
const int pinMic = A3; //analog input connected to mic AUD

const int pinLED0 = 5; //digital output connected to LED 0

//baseline level for my mic in a fairly quiet room
//determined by watching serial monitor on first run
const int valBaseline = 530;

void setup() {
    Serial.begin(115200);

    pinMode(pinLED0, OUTPUT);
}

void loop() {
    int valMic = analogRead(pinMic);

    Serial.println(valMic);

    if (valMic > valBaseline) { 
      digitalWrite(pinLED0, HIGH);
    } else {
      digitalWrite(pinLED0, LOW);
    }
}
```

The code kind of looks like a potentiometer, so I tried that setup in johnny five, but the LED just shows up as constantly on.

I have no idea if the microphone is really similar to a potentiometer or not - how do I find out? Does johnny five currently support microphones?

I'm interested to get this working if not. I can help add support if I am pointed to the right direction =)

**Comment by divanvisagie** [comment]
@rwaldron From what I gather here the support is fine , It just needs to be documented and some examples made.

**Comment by rwaldron** [comment]
@divanvisagie yep!

**Comment by rwaldron** [comment]
https://github.com/rwaldron/johnny-five/commit/5579d12c61842671bac9709a7b02b61d31dc9ba2

**Comment by taktran** [comment]
Thanks @rwaldron!
