### ISSUE TITLE
Motors on the Micro Magician

### ISSUE THREAD

**Issue by alexcroox** [rwaldron/johnny-five#274]
I want to control the DC motors on the Micro Magician but I'm not sure what pin numbers they are when I setup the motors in J5.

Here is the board diagram, I am using Motor A and B at the bottom:

![mm v2](http://www.robotgear.com.au/Cache/Files/ProductImageOriginals/1863_Dagu%20Micro%20Magician%20V2%20Robot%20Controller%20-%20annotated.jpg)

If I was to guess I'd say:

a - [8,6]
b - [7,5]

**Comment by dtex** [comment]
I got back round to this (sorry, forgot). The motors work fine with that configuration and I've added it to the SHIELD_CONFIGS object. I'm going to create a new eg file for the micro-magician that wires up all the devices we can support. I also need to find a fritzing diagram for the board. It'll need to be added to the Platform Support section of the website as well I suppose.

**Comment by dtex** [comment]
Accelerometer seems to work fine too.

**Comment by dtex** [comment]
Okay, everything on the Micro Magician works fine, except for IR of course. I was going to make a Fritzing diagram for the board but I'm just twisting in the wind. Fritzing is clearly not my thing. Who made all the board diagrams that weren't available somewhere online?

**Comment by Resseguie** [comment]
I think @rwaldron did most of those. I need to add that trick to my toolbox.

**Comment by rwaldron** [comment]
I make the svgs in iDraw and then import them into Fritzing—which is not straight forward at all.

**Comment by dtex** [comment]
Micro Magician works fine. Added a shield definition to motor.js and confirmed that servo, motor and accelerometer all work. Examples added for each. Note: We don't support IR yet.
