### ISSUE TITLE
Add arduino library to Firmata or Johnny-Five

### ISSUE THREAD

**Issue by scottkellie** [rwaldron/johnny-five#285]
Not sure if issues or just me!

I am currently trying to connect some I2C devices, DHT and onewire temp sensors etc to one of my projects. I can use Johnny-Five to read and set analog and digital pins and it works well. I don't seem to be able to find any docs on adding an Arduino library e,g, RCswitch to my program. 

I also cannot seem to find an example of sending an I2C setup message, sending a request and reading the response. I have a wireless bridge that uses I2C also. The support is in Firmata but I would like to stay within the usual Johnny Five instance and can't seem to find anything, is there anything that can point me in the right direction?

one of the sensors I am using is a popular one wire temp sensor the Dallas DS18B20
Not sure on support for this it uses the onewire library http://playground.arduino.cc/Learning/OneWire

**Comment by r3sk** [comment]
I am trying to set 2 ds18b20 sensors on the same pin like:
```javascript
var temperature1 = new five.Temperature({
        address: 0x44eea77ff,
        controller: "DS18B20",
        pin: 8,
    });
    
     var temperature2 = new five.Temperature({
        address: 0x44ef135ff,
        controller: "DS18B20",
        pin: 8,
    });

temperature1.once("data", function (err, data) {
        console.log(data.celsius + "°C");
    });
temperature2.once("data", function (err, data) {
        console.log(data.celsius + "°C");
    });
```

but i get this error:
```javascript
Component pin: 8, controller: DS18B20, address: 18504275455 is already in use 
/home/resk/dev/arduino/node_modules/johnny-five/lib/temperature.js:119

                this.emit("error", err);
                     ^
TypeError: undefined is not a function
    at /home/resk/dev/arduino/node_modules/johnny-five/lib/temperature.js:119:22
    at null._onTimeout (/home/resk/dev/arduino/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:1141:5)
    at Timer.listOnTimeout (timers.js:110:15)
```

am i doing something wrong?

**Comment by kbarre123** [comment]
Hey @r3sk , I'm getting the same errors as you. We're discussing a fix over on [Gitter](https://gitter.im/rwaldron/johnny-five?at=5516e4092987ee48769b4254) if you want to follow along and help test.

**Comment by JerksonS** [comment]
Hey everyone, i was beginning to use the temperature class in a project I'm working on and now that I'm ready to add a second 1-wire device on the bus I landed here :) 

I have followed the gitter conversation but saw no resolution to this question there so I figured I'd revive this old thread.Is there a supported way of addressing multiple 1-wire devices on a single pin using the temperature class yet, maybe by passing an array of addresses as a parameter in the constructor or by instantiating multiple temperature objects with different addresses on the same pin (which still caused an error for me when I tired like r3sk above)

Thanks for all your work on Johnny-Five

**Comment by westinpigott** [comment]
@JerksonS, I have not tested the version which is supposed to be integrated into johnny-five.  It is based on the class I wrote which has johnny-five as a dependency, although I don't believe it is non-blocking IO the way my class is.  You can see mine at https://github.com/westinpigott/one-wire-temps.  it works for multiple sensors.  I have tested it up to 5 as thats all I had available.
Not completely clean as a johnny-five module, but it works.

**Comment by JerksonS** [comment]
@westinpigott Thanks for the reply.

I was looking through the Johnny five source and saw the credit to your one-wire-temps in temperature.js.

I had actually started using your one-wire-temps before I learned that a temperature class was added into Johnny-five itself. Until now I have only been playing with one temp sensor but now want to expand to 5 and then I hit this roadblock. Perhaps I'll try out your way again while i wait for it to be 'corrected' or validated in johnny-five natively.

**Comment by rwaldron** [comment]
> Even though over here - https://github.com/BrianGenisio/johnny-five/blob/multi-DS18B20/eg/temperature-dual-ds18b20.js - it shows exactly the same method (two temperature objects sharing the same pin but with different addresses) This generates an error when the second temperature object is defined:

> "Component pin: 12, controller: DS18B20, address: 1190065684735 is already in use"

This is just a bug in the over-eager pin validation/protection code :\

**Comment by r3sk** [comment]
@kbarre123 last time i played if this sensors they were working, but the "Component pin: 8, controller: DS18B20, address: 18504275455 is already in use "  message continue appearing, but it didn't break the code anymore. I'll test my code again when get home.

**Comment by JerksonS** [comment]
@r3sk, @kbarre123 and @rwaldron, Sorry guys..it looks like I jumped the gun here. Even though I get an error message about the pin already being in use, it does actually work. I'm polling two DS18B20's (one waterproof and one bare sensor) on the same bus/pin successfully and reliably.

I simply saw the error message and decided not to go any further and write an .on "data" function for the second sensor assuming it was not initialized correctly when I saw the error. Here is the code that works:
```

temp1 = new five.Temperature({
  controller: "DS18B20",
  pin: "12",
  address: 0x6873a44, //waterproof
  freq:  0.1 * 60 * 1000
});

temp2 = new five.Temperature({
	controller: "DS18B20",
	pin: "12",
	address: 0x115159e93ff, // rj45 sensor
	freq:  0.1 * 60 * 1000
});

temp1.on("data", function(err, data) {
	log("Read water temp " + data.fahrenheit + " from 0x" + this.address.toString(16));
});
temp2.on("data", function(err, data) {
	log("Read air temp " + data.fahrenheit + " from 0x" + this.address.toString(16));
});
```

log() is a helper function that pre-pends a date to each string it is sent and then echoes both to console and a logfile
