### ISSUE TITLE
Using Arduino in Proteus simulation software?

### ISSUE THREAD

**Issue by rodrigopandini** [rwaldron/johnny-five#314]
Hi guys,

Someone tried to connect johnny-five to an Arduino component in the Proteus simulation software?
I'm getting "Device or Firmware Error"..

Description:
[Proteus](http://www.labcenter.com) is a software to design, build and simulate electronic circuits. 
Check this videos (portuguese) to understand better how to put the Arduino component in the software: https://www.youtube.com/watch?v=PW1wj03j4Eg
And check this video https://www.youtube.com/watch?feature=player_detailpage&v=B3zibJ2zdoI#t=480 to understand how to connect it to the serial port component, and also how to create a virtual serial port using [Virtual Serial Port Emulator](http://www.eterlogic.com/Products.VSPE.html).

So, I uploaded the StandardFirmata hexadecimal file to the Arduino component and I'm trying using johnny-five, instead Putty or pySerial, etc (second video).
But I'm getting: "Device or Firmware Error" when try to connect.
I have almost sure that this error comes from [node-serialport](https://github.com/voodootikigod/node-serialport), but I'm still not able to debug it.

Some help?

**Comment by eagle0001** [comment]
I’m building car tracking device using Arduino UNO.
simulatig the circuit on proteus results in error AVR not defined.
P.S i’ve given the right path to controller.

**Comment by AldanisVigo** [comment]
You can run proteus on mac using Wine. Works just fine.

**Comment by code-injection1** [comment]
mixed model AVR2.DLL failed to authorize - Missing or invalid Customer Key.. [ARD1]
 how to slove

**Comment by enigmaelectronica** [comment]
Where is located avr2.dll
