### ISSUE TITLE
Getting Started with Animatronic

### ISSUE THREAD

**Issue by JpEncausse** [rwaldron/johnny-five#321]
Hi,
Sorry for my dumb question

Trying to play with
http://www.animatronicshop.com/

I got the given message:
[90m1397515562660[39m [35mDevice(s)[39m [36m[90mCOM1,COM6[39m[39m

then
[90m1397515662672[39m [35mDevice or Firmware Error[39m [31mA timeout occurred while connecting to the Board. 
Please check that you've properly flashed the board with the correct firmware.[39m 

don't know what should I do the "ready" event is never called

When using Ardruino IDE i got some data so it seems "ok"

**Comment by icgreen** [comment]
Just came across the same issue. I had to do the same but with COM4.  Thanks for documenting what you did to solve it.

**Comment by mattributes** [comment]
Thanks @JpEncausse this was my problem as well.
