### ISSUE TITLE
Barometric Pressure Sensor Examples?

### ISSUE THREAD

**Issue by kaochris** [rwaldron/johnny-five#322]
Hey,

Does anyone have any examples interfacing with a barometric pressure sensor? More specifically the MPL3115A2?

**Comment by dtex** [comment]
Thanks to @BrianGenisio and @soundanalogous we have support for the [MPL3115A2](https://github.com/rwaldron/johnny-five/blob/master/docs/barometer-mpl3115a2.md). We just forgot to go back and close this issue.

**Comment by soundanalogous** [comment]
Does it actually work? The change was never made on the Firmata side.

**Comment by rwaldron** [comment]
Yeah, it works with that branch you have with these changes... And now I know why I hadn't pushed that controller, but I had forgotten that and one day noticed it was but rotting—so I pushed it out. Whoops.

**Comment by soundanalogous** [comment]
np I'll rebase and merge the Firmata change into master later tonight

**Comment by soundanalogous** [comment]
I've added i2c restart to Firmata. Pull the Firmata master branch and try StandardFirmata or StandardFirmataPlus with the MPL31152A and let me know if all is good.
