### ISSUE TITLE
ADXL335 accelerometer help

### ISSUE THREAD

**Issue by taha** [rwaldron/johnny-five#327]
I'm trying to use the ADXL335 accelerometer (I'm using Adafruit's breakout circuit https://www.adafruit.com/products/163) with J5's lib. However, I can't seem to get anywhere near accurate or real readings.

Here's my code. I've stripped out the board instantiating and other irrelevant bits.

```js
var accel = new five.Accelerometer({
	pins: ["A4", "A5", "A6"],
	freq: 100,
	threshold: 0.3,
	voltage: 3.3,
	sensitivity: 0.36
});

accel.on("acceleration", function(err, data) {
	var pitch = deg(this.pitch).toFixed(2),
		roll  = deg(this.roll).toFixed(2);

	console.log(_.map(data.rough, function(vals) {
		// Get latest queue entry
		return parseFloat(vals[0].toFixed(2));
	}));

	console.log(
		"pitch", pitch,
		"roll", roll
	);
});
```

When the accel is not moving and in initial position (http://c.wzy.la/image/0f3i2D0X3Y07), the initial sample data are similar to the following

```
[x, y, z]
pitch: xx.xx roll xx.xx

[ -1.73, -1.66, -0.89 ]
pitch 41.89 roll 41.09
[ -1.7, -1.69, -0.9 ]
pitch 41.83 roll 41.03
[ -1.7, -1.68, -0.91 ]
pitch 41.35 roll 41.35
[ -1.68, -1.68, -0.91 ]
pitch 41.38 roll 41.38
[ -1.67, -1.69, -0.9 ]
pitch 41.23 roll 41.50
[ -1.67, -1.68, -0.9 ]
pitch 41.26 roll 41.53
[ -1.67, -1.69, -0.9 ]
pitch 41.11 roll 41.65
[ -1.67, -1.68, -0.9 ]
pitch 41.38 roll 41.38
[ -1.67, -1.69, -0.9 ]
pitch 41.23 roll 41.50
[ -1.67, -1.68, -0.9 ]
pitch 41.23 roll 41.50
```

I've also tried testing with other sensitivity values, it doesn't make much difference to the final pitch/roll values. I've also tested with 5v, same result. I should also note when I move the accel to supposably -90 and 90 degrees, the read value ranges from 45 and 29 degrees. Same with the roll value.

**Comment by rwaldron** [comment]
Support landed!

**Comment by taha** [comment]
@rwaldron Awesome!
