### ISSUE TITLE
PulseSensor implementation or example?

### ISSUE THREAD

**Issue by nmelin** [rwaldron/johnny-five#328]
Hello, doing a bit of pre-emptive project research.

has support for this been implemented:
PulseSensor Heart-Rate BPM for Arduino
http://pulsesensor.myshopify.com/pages/code-and-guide

If not, do you think this would be implemented with a  'new five.Sensor()' function ?

**Comment by Senade** [comment]
Hey,

Could you guys have a look at a similar problem that I'm having?

https://github.com/rwaldron/johnny-five/issues/788
