### ISSUE TITLE
Trying to use XBee but having issues connecting

### ISSUE THREAD

**Issue by donaldaverill** [rwaldron/johnny-five#358]
Hi, I'm having issues connecting to an Arduino Uno using Xbees and johnny-five. When I plug in the Uno using a USB cable and run the led-strobe.js example, everything works great. But when I try to communicate with the XBees, the program hangs and eventually gets to the point where it times out and says:
```
Device or Firmware Error A timeout occurred while connecting to the Board. 
Please check that you've properly flashed the board with the correct firmware. 
```
I've confirmed that I can communicate with the XBees using [serialport](https://www.npmjs.org/package/serialport) like:
```
node app.js
```
where app.js is:
```js
var SerialPort = require("serialport").SerialPort
var serialPort = new SerialPort("/dev/tty.usbserial-AD026BEG", { 
  baudrate: 9600
}, false); 

serialPort.open(function () {
  console.log('open');
  serialPort.on('data', function(data) {
    console.log('data received: ' + data);
  });
  serialPort.write("ls\n", function(err, results) {
    console.log('err ' + err);
    console.log('results ' + results);
  });
});
```
and an Arduino sketch like:
```
int i = 0;
void setup()
{
  Serial.begin(9600);
}
void loop()
{
  Serial.println(i);
  i++;
  delay(500);
}
```
The console prints out every half second:
```
data received: (the value of i)
``` 
So, the configuration seems fine, I think. Any ideas? 

Note: I upload the StandardFirmata sketch to the Arduino before running led-strobe.js.

**Comment by rwaldron** [comment]
Thanks again for the guide!
