### ISSUE TITLE
problems with I2C & Firmata.

### ISSUE THREAD

**Issue by overflowz** [rwaldron/johnny-five#368]
Hi, I have two boards, Master device is Arduino Yun, and as slave device Arduino Mega. There are written StandardFirmata on both, but I can't find any documentation here how can I control slave device from master device with I2C protocol.

EDIT: seems
this.firmata.sendI2CWriteRequest( address, bytes );
this.firmata.sendI2CReadRequest( address, bytes, callback );

these two functions does not work, it says this.firmata is undefined.

Any info please?
Regards.

**Comment by mattstronaut** [comment]
I know this is closed, sorry again @rwaldron, but where could I find documentation on these magical this.io functions? Is it possibly to this.firmata.sendI2CWriteRequest( address, bytes ); on a specific board when using the boards class?

**Comment by overflowz** [comment]
Hey, "this.io" is actually firmata library, you can check things there if I'm not mistaken.

**Comment by mattstronaut** [comment]
Ahh, thank you very much!
