### ISSUE TITLE
How to use johnny-five in node-webkit

### ISSUE THREAD

**Issue by sat-ish** [rwaldron/johnny-five#395]
Hi,
I intend to create a GUI to control my arduino micro controller over html by using javascript.
Node Webkit is a  run time app which supports node.js and all its third party modules. As per my understanding johnny five is similar to all other third party modules in nodejs. However i am unable to invoke the johnny-five module through Node Webkit. Please tell me where i am going wrong.
How should i invoke johnny-five.If this is not possible, can you please suggest some other method to use johnny-five through html.

**Comment by ryantuck** [comment]
this is still an issue for OSX. If I find a way to make it work, I'll post here.
