### ISSUE TITLE
hc-sr04 usage

### ISSUE THREAD

**Issue by omgmog** [rwaldron/johnny-five#399]
Hello, I've been trying to get my `hc-sr04` sonar sensor to work with an Uno and johnny-five, but I'm having no luck.

I'm using the patched firmata to play nicely with `ping` (as detailed on [the Ping wiki page](https://github.com/rwaldron/johnny-five/wiki/Ping#setup), but I don't think the wiring diagram provided in the [docs example](https://github.com/rwaldron/johnny-five/blob/master/docs/hc-sr04.md) is correct.

![](https://github.com/rwaldron/johnny-five/raw/master/docs/breadboard/hc-sr04.png)

The `trig` and `echo` pins don't seem to be wired correctly on that diagram (though I'm not sure what correctly would be, presumably either linking them together, or running a line for each).

When I wire hook up my sonar sensor as in the diagram, and use the `ping` example provided, my console just logs the distance as `0 cm` and `0 inches`, regardless of the actual physical state of the sensor.

Has anybody else got this sonar sensor to work? Or can anybody else confirm the correct way to use it.

**Comment by superdcc** [comment]
hello~  you can try this!

https://github.com/rwaldron/johnny-five/wiki/Ping#setup

I think problem is Firmata 's version...
