### ISSUE TITLE
Servo table 

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#418]
To add to docs: a table showing all servos and links to product pages. Includes:
- necessary voltage and current draw
- default range in degrees
- type (obviously)
- configurability

What else?

**Comment by dtex** [comment]
Rethinking this. I wonder if rather than adding a table that would have to be perpetually maintained we should just do a better job of informing users how/where to find these stats for their servos, and why they are important.

**Comment by dtex** [comment]
I propose we just add a link on the API documentation page to this [Servo Motor Guide](https://learn.adafruit.com/adafruit-motor-selection-guide/rc-servos) over at Adafruit.
