### ISSUE TITLE
Pro Micro Arduino Bluetooth support?

### ISSUE THREAD

**Issue by avermeulen** [rwaldron/johnny-five#423]
Are there anything I need to know to be able to connect an Arduino Pro Micro to a Bluetooth Serial Port?

I was able to set the BAUD rate correctly on a HC-06 module from a Pro Micro Arduino, but I can't connect to the board using this module. If I take this bluetooth module and I add it to my UNO it works fineic . 

I did put Standard Firmata back onto the Pro Micro board after setting the board BUAD rate of the HC-06. But I get this error:

`1407526193657 Device or Firmware Error A timeout occurred while connecting to the Board. 
Please check that you've properly flashed the board with the correct firmware.`

 Anyone that connected a Pro Micro to bluetooth serial port successfully?

**Comment by acklenx** [comment]
soundanalogous That worked!!  And just in time for nodebots day!

I have a pile of micros/leonardos that would not work with bluetooth even though the same HC-05 (in my case) would work just fine on an UNO or a mini.  I read the arduino serial reference page ( https://www.arduino.cc/en/Reference/serial ) and thought i would change Serial to Serial1 somewhere... haha.  Anywho it was enough to lead me here and now I can control my arduino micro nodebots via bluetooth.  This has been bugging me for so long. I like the micros with the usb (that everyone has) over the minis that need something no one has (at home).  I made the changes in StandardFirmata ( which I saved as Serial1Firmata ).  This is how my setup method looks now: 


void setup()
{
  Serial1.begin(57600); // the arduino leonardo and pro micro use serial1 to communicate on pins 0 and 1 (serial RX and TX)
  while (!Serial1) {} // While the virtual serial port is not connected all messages will be lost, so wait till it's ready
  
  Firmata.setFirmwareVersion(FIRMATA_MAJOR_VERSION, FIRMATA_MINOR_VERSION);
  Firmata.attach(ANALOG_MESSAGE, analogWriteCallback);
  Firmata.attach(DIGITAL_MESSAGE, digitalWriteCallback);
  Firmata.attach(REPORT_ANALOG, reportAnalogCallback);
  Firmata.attach(REPORT_DIGITAL, reportDigitalCallback);
  Firmata.attach(SET_PIN_MODE, setPinModeCallback);
  Firmata.attach(START_SYSEX, sysexCallback);
  Firmata.attach(SYSTEM_RESET, systemResetCallback);

//  Firmata.begin(57600);  // rem'd for use with Arduino Pro Micro / Leonardo
  Firmata.begin(Serial1);  // Use Serial1 for leonardo and pro micro (as noted above)  Serial1 is initialized above at 57600 baud
  systemResetCallback();  // reset to default config
}
