### ISSUE TITLE
Piezo.js API Additions

### ISSUE THREAD

**Issue by McDonnellDean** [rwaldron/johnny-five#429]
All,

I would like to get your feedback on the following API additions I am putting forward for Piezo.js. In no particular order:

#### Default Octave On Notes
It seems, anecdotally at least, that most libraries play notes at the 4th octave by default. Currently our API requires that the octave is provided with the note, e.g. `c4, e0, f#2`. For ease of use I propose that we allow users to enter only the note value, from this we will default to the 4th octave. All notes in the 4th octave range seem to be distinguishable from one another which makes it an ideal choice for a default. The 3rd Octave is also good. We could push this one step further by adding an `defaultNoteOctave(value)` function although I don’t have an immediate opinion on this part yet.

#### Structuring And the Notes collection
We have a full collection of notes, octaves, and frequencies (in Hz) stored in Piezo.Notes. I propose that we add a bit of structure to the current object or a new PiezoNotes object. I haven’t yet formed an opinion on how this should look but if we could split each data point out into its own named field it would be nice.This would make logging, displaying, or working with this info easier than it is now.

#### Addition Of A Single Tone Play Function 
Currently single notes are play by frequency (Hz) via the `tone()` or `frequency` functions. I propose a `note` function which allows the user to play a sound by specifying note data. This makes it easier for non musical folk to play sounds by passing in the note name as opposed to frequency

#### Documentation Updates
I propose, after the work is done that the documentation is updated with the changes made as well as more information around our Piezo functionality. Basically flesh out the docs more.

![image](https://cloud.githubusercontent.com/assets/3625961/3898801/151f1178-2271-11e4-8839-2b31d6034a74.png)

Those are my proposals. It would be awesome if anyone else has any sort info, additions, or input to go along with the above!

I'd like to be the one to take a stab at this work if thats ok, get my Javascript Thang on!

EDIT: Update to `defaultNoteOctave`
EDIT: Removed proposal for static Piezo.Notes, as it already is static
EDIT: Added More around Docs
EDIT: Removed erroneous `playTone` text. The correct method is `tone`

**Comment by divanvisagie** [comment]
PR merged
