### ISSUE TITLE
IR Receiver Module?

### ISSUE THREAD

**Issue by BrianGenisio** [rwaldron/johnny-five#434]
Is anyone working on an IR Receiver module?  I see the IR proximity and distance sensors, but I don't see anything about IR Receivers.  As far as I can tell, they work completely differently (proximity sensors work with I2C where IR Receivers use pulse-distance modulation protocols).

If nobody is working on it, I am curious enough to start playing with it.  Any known resources out there?  There is the IRRemote Arduino library that I can likely get some guidance from.  Has anyone tried this in the past but hit a wall?  Any thoughts on how it should behave?  

I was thinking an event with data is probably the primary interface, but likely a mapping interface would be nice, so I can get commands mapped to a specific remote.

I may never get anywhere with it, I am really just curious right now.

Thoughts?

**Comment by robtarr** [comment]
Has anyone looked into a solution for this? I would be willing to help with whatever I can. I have an IR LED & receiver that I would love to hook up to a Johnny-Five project.

**Comment by sergionader** [comment]
Hello,

I need some help to put some pieces together. 
1) I can run https://github.com/shirriff/Arduino-IRremote with no problems in my Arduino Uno, so I can send raw data to remote control my TV. 
2) I can make my beaglebone black blink leds in my Arduino Uno using johnny-five (thank you!!!!)
3) What I need is a way to allow node to send those raw codes to arduino in order to let arduino send the IR signal to my TV. Using a web interface, user clicks on volume up button, for instance, and node sends the related raw code to arduino that sends it to the IRRemote library.

Is that possible? Basically I need node to send parameters to an Arduino sketch.

Any help will be appreciated.

Thanks in advance and have you all a nice week.

Sergio

**Comment by BrianGenisio** [comment]
The problem is that the IR receiver module sends pulse-length modulated digital signals.  These are the hardest kinds of digital signals for a Firmata-based system to work with because it requires blocking in order to accurately measure the pulses.  

It is possible to write a custom Firmata extension to do this, but I'm not aware of anyone who has done this yet.

Instead, we're looking at a hardware solution.  @ajfisher is working on a pulse-width to I2C adapter that he thinks can be produced around $3 each!  How's that going @ajfisher ?  Once that exists, it should be (crossing fingers) pretty easy to write J5 drivers for things like the IR Receiver, FM Receivers, Ping sensors, Digital Reflectance Arrays, and other modules which emit time-based digital signals.

**Comment by sergionader** [comment]
Thanks for your reply, Brian. 

I'm not sure if got properly what you said, once using Arduino I can send the IR "microseconds array" to the receptor. I don´t need to receive IR codes. 

My project is all based on Beagle Bone Black, but I could not find a library to send the IR codes. So, I'm trying to use the Arduino to do so, still using BBB as the "central command".

Thus, splitting the questions:
1) my real need is to send IR raw codes from BBB
2) As I could not get it done, I want to use BBB to make Arduino to do so.

Regards and have a nice week!

Sergio

**Comment by rwaldron** [comment]
You could use the Arduino as an I2C slave (with some custom firmware) and connect it to the Beagle Bone (I2C master). Then  use `board.i2cWrite` and `board.i2cRead` to to interact with the I2C slave

**Comment by sergionader** [comment]
Thanks, Rick.

In this case (board.I2cWrite) can I send a sketch name and parameters? If yes, is there any example? 

Regards!

**Comment by rwaldron** [comment]
> can I send a sketch name and parameters? 

I don't understand this question. The sketch would already be on the Arduino, it would look something like this: 

```ino
#include <IRremote.h>
#include <Wire.h>

// connect your IR thing to pin 11
IRrecv irrecv(11);

decode_results results;

int address = 4;
int value = 0;

void setup() {
  Wire.begin(address);
  Wire.onRequest(onRequest);

  irrecv.enableIRIn();
}

void loop() {
  if (irrecv.decode(&results)) {
    value = results.value;
    irrecv.resume();
  }
}

void onRequest() {
  Wire.write(value);
}
```

The Arduino's SDA and SCL are connected to the BeagleBone's SDA and SCL. 

In Johnny-Five code, running on the BeagleBone: 


```js
var five = require("johnny-five");
var Bone = require("beaglebone-io");
var board = new five.Board({
  io: new Bone()
});

board.on("ready", function() {
  this.io.i2cConfig();
  this.io.i2cRead(4, 1, function(data) {
    // This is the value from irrecv in the sketch above.
    console.log(data);
  });
});
```


Note: none of this is actually tested, I've done other i2c master<->slave projects that are similar and they all work very well.

**Comment by sergionader** [comment]
Looks like this is exactaly what I need. Will test and make the proper adjustment if needed.
As soon as I do it, will post the results. 
Thanks a lot!

**Comment by rwaldron** [comment]
I will try to do any actual test today as well, that way we can compare results. I'll try these:


Arduino <=> Arduino
Edison <=> Arduino

Will report back when I know more

**Comment by sergionader** [comment]
Hello, Rick.

The only way I found to make it to work was using node module serialport. 
I2C didnt't work, unfortunately. 

Have you got any better result?

Regards

**Comment by curlyz** [comment]
A littl bit late for the party but I have made a hugh effort in IR signal I2C interface, i promimsed a simplest i2c code for the main cpu.
A little bit how this work, this module is pro mini based with ability to receive, decode, send, and store both raw and protocol data. For raw data , i design a simple code and led interface to make it at ease for user, just press a button, or send learn command from master i2c device and it will store it . Everytime you need to send or recognise , just use a simple i2c command.
So only 3 i2c command needed for this module.
At first I was thinking about closed source this, but avr lock bits are so screw up so i guess this is my contribution to the community.
Anyway, if anyone have interest in this, email me. curly.saigonese@gmail.com
Note. With flash chip, this module can store more than 256 command, max raw length is 240 or 120bit message. I have tried this with my air conditioner, work like charm :))
And it will be open source only after someone helped me upgrade the code a little bit.

**Comment by dtex** [comment]
Hi @BrianGenisio,

I'm working on cleaning up the J5 issues list (it was getting kind of hairy). I've identified a subset of issues that are requests for new classes, devices or features and have added them to an index of [requested features](../wiki/Requested-Features). Hopefully it will be a place where motivated contributors can find cool things to work on.

This request is listed under the new "Receiver" class.
