### ISSUE TITLE
 the computer?

### ISSUE THREAD

**Issue by kukulako** [rwaldron/johnny-five#441]
I have doubt then I have to have the computer on all the time for the arduino johnny five works?

**Comment by VRuzhentsov** [comment]
@dtex So, theoretically I can setup Bluetooth/WiFi serial port connection, and send commands via wireless?

**Comment by dtex** [comment]
Yes, both Bluetooth and Wifi are options. The ESP8266 is a pretty cool wifi solution and there are many others.

**Comment by VRuzhentsov** [comment]
@dtex 
Searched a lot, but I am stuck
![image](https://user-images.githubusercontent.com/4579833/55958556-a02eeb00-5c71-11e9-9db7-e3360203851d.png)
I have NodeMCU v1 with ESP8266 board and UNO board.
And, how I can forward commands from J5 straight to UNO using this NodeMCU?
Maybe through UART or I2C

Currently have such code
And can to connect to the NodeMCU, but not sure, that it can see normally the UNO board
```js
const {Board: FirmataBoard} = require('firmata');
const {Board: J5Board, Led: {RGB:RGBLed}} = require("johnny-five");
console.log('init');

const {EtherPortClient} = require('etherport-client');

const nodeMCUBoard = new FirmataBoard(new EtherPortClient({
    host: '192.168.193.10',
    port: 3030
}));


nodeMCUBoard.once('ready', function () {
    console.log('NodeMCU ready!');
    console.log(
        nodeMCUBoard.firmware.name + "-" +
        nodeMCUBoard.firmware.version.major + "." +
        nodeMCUBoard.firmware.version.minor
    );
    nodeMCUBoard.isReady = true;

    const arduinoUno = new J5Board({
        io: nodeMCUBoard,
        timeout: 1e5,
        repl: false
    });

    arduinoUno.on('ready', function () {
        console.log('UNO ready!');

        const rgb = new RGBLed([5, 6, 3]);
        const randomColor = () => Math.random().toString(16).substr(-6);

        this.loop(100, function () {
            const countedColor = randomColor();
            console.log('countedColor', countedColor);
            rgb.color(countedColor);
        });
    });

});

```

**Comment by dtex** [comment]
I want to make sure I'm understanding the bigger picture. Why do you need the Uno and the ESP8266?   I would think the Uno adds an unnecessary layer of complexity.
