### ISSUE TITLE
pin.js example throwing errors 

### ISSUE THREAD

**Issue by ghost** [rwaldron/johnny-five#452]
1411798568618 Device(s) /dev/ttyACM0 
1411798568638 Board  
1411798568639 Connected /dev/ttyACM0 
1411798568639 Repl Initialized 

> > /home/samuel/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:600
> >     this.pins[pin].mode = mode;
> >                         ^
> > TypeError: Cannot set property 'mode' of undefined
> >     at Board.pinMode (/home/samuel/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:600:25)
> >     at Led.Object.defineProperties.mode.set (/home/samuel/node_modules/johnny-five/lib/led.js:91:19)
> >     at new Led (/home/samuel/node_modules/johnny-five/lib/led.js:106:15)
> >     at Board.<anonymous> (/home/samuel/WebstormProjects/arduino/hi.js:9:6)
> >     at Board.emit (events.js:95:17)
> >     at Board.broadcast (/home/samuel/node_modules/johnny-five/lib/board.js:398:8)
> >     at Board.<anonymous> (/home/samuel/node_modules/johnny-five/lib/board.js:152:18)
> >     at SerialPort.<anonymous> (/home/samuel/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:418:13)
> >     at SerialPort.emit (events.js:95:17)
> >     at SerialPort.callback (/home/samuel/node_modules/johnny-five/node_modules/serialport/serialport.js:75:16)

**Comment by saisrinivas0695** [comment]
i also got same problem  this.pins[pin].mode = mode;

**Comment by saisrinivas0695** [comment]
what to do
with firmata.js

**Comment by rwaldron** [comment]
Works for me: 

```js
$ node eg/pin.js
1499890003364 Available /dev/cu.usbmodem1411
1499890003371 Connected /dev/cu.usbmodem1411
1499890005052 Repl Initialized
>> { supportedModes: [ 0, 1, 2, 4, 11 ],
  mode: 2,
  value: 420,
  report: 1,
  analogChannel: 0,
  state: 0 }
Event emitted for: low on 13
Event emitted for: high on 13
```

> what to do with firmata.js

Nothing. You need to make sure your Arduino has StandardFirmata or StandardFirmataPlus uploaded to it (using the Arduino IDE). The steps are in the readme.md file: [Setup and Assemble Arduino](https://github.com/rwaldron/johnny-five#setup-and-assemble-arduino)
