### ISSUE TITLE
Update Led.Matrix docs

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#461]
@AnnaGerber, I did a few updates here, but would appreciate if you could give a more thorough look: https://github.com/rwaldron/johnny-five/wiki/Led.Matrix

**Comment by NiXXeD** [comment]
I noticed in these docs there is no mention of 8x8 RGB LED matrices. From looking around through the code and such, I also cannot seem to find support. 

Example hardware:
http://www.amazon.com/gp/product/B0068K01QE/ref=oh_aui_detailpage_o01_s01?ie=UTF8&psc=1
+ http://www.amazon.com/Rainbowduino-LED-Driver-Platform-Atmega328/dp/B0068JYK0I/ref=pd_bxgy_MI_text_y

My main use case I'm looking for is to control this pair from my arduino, with j5. So far, what I have working is that I wrote a small I2C slave firmware that supports x/y/r/g/b. Then, with firmata on my arduino, I'm able to use j5 to write directly to the slave, and that works.

I guess what I'm wondering is if there is intent to add support for this type of use case. If so, should I work on adding this more officially or should I just consider this a rare-ish use case and just kinda handle it on my own.

Thanks!

**Comment by rwaldron** [comment]
It can be added as a new controller; take a look at the existing controllers: https://github.com/rwaldron/johnny-five/blob/master/lib/ledcontrol.js#L327-L842

**Comment by rwaldron** [comment]
I just ordered one of these boards and a matrix to help test when you're ready.

**Comment by AnnaGerber** [comment]
Sounds great. I just got a Colorduino and RGB matrix in the mail on Friday, so I can help test too.

**Comment by rwaldron** [comment]
There have been major updates
