### ISSUE TITLE
installing on arduino yun hangs using npm install

### ISSUE THREAD

**Issue by born2net** [rwaldron/johnny-five#465]
I am trying to install johnny but it keeps hanging, I already removed the node -max flags so it has full memory capacity... anything else I can try?

Thanks,

Sean.

**Comment by framlin** [comment]
Servus,
I have expanded disk space and installed node on a yun as described on the arduino-site.
After that I did:
root@Arduino:~/src/j5tst# npm install nino-io
npm WARN package.json nino-io@0.2.0--dev-001 No README data
FATAL ERROR: Evacuation Allocation failed - process out of memory
Aborted

What is the reason for this error and how can I avoid it?

**Comment by fivdi** [comment]
It looks like `npm install nino-io` was called from the home directory. Try running `npm install nino-io` in the `/opt` directory as described [here](https://github.com/rwaldron/nino-io#lininoos).

**Comment by framlin** [comment]
@fivdi thanks,
meanwhile I have done the procedure described on the linino-wiki instead of that on arduino.cc to install node.
npm install nino-io johnny-five works now, but I run into the same error as frxnz
  pwm: 
   { ENA: true,
     DEF: 'P11',
     TYP: 'pwm',
     MAP: 'D11',
     BIT: '16',
     NUM: '3',
     TIM: { DEF: 'T3', SET: false, USE: [], SHARED: true },
     MAX: 32768000,
     RES: 500 } }
Failed to export ADC: (ENOENT ENOENT, open '/sys/bus/iio/devices/iio:device0/enable') 
Ready.

fs.js:513
  binding.write(fd, buffer, offset, length, position, wrapper);
          ^
TypeError: Bad argument
    at Object.fs.write (fs.js:513:11)
    at Pin.write (/root/src/j5tst/node_modules/nino-io/lib/nino-io.js:986:6)
    at Nino.digitalWrite (/root/src/j5tst/node_modules/nino-io/lib/nino-io.js:467:23)
    at null.<anonymous> (/root/src/j5tst/run.js:16:23)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by fivdi** [comment]
I have a Linino One, not a Yun. The file `/sys/bus/iio/devices/iio:device0/enable` exists on my system, but apparently not on your, correct?

Did you upgrade your Arduino Yun to LininoIO after upgrading to Linino OS?

I had similar issues of missing files on the Linino One after installing a fresh Linino OS but leaving out the LininoIO step. For example `/dev/i2c-0` was missing. Is `/dev/i2c-0` missing on your system?

**Comment by lamiastella** [comment]
Hi,
I have done the Arduino Yun Disk Expansion using the serial monitor and yet I can't install johnnyfive. Here are the list of related commands I entered. Any idea how to fix this?
root@Arduino:/overlay# npm install johnny-five
FATAL ERROR: Evacuation Allocation failed - process out of memory
Aborted
root@Arduino:/overlay# free
             total         used         free       shared      buffers
Mem:         61116        39396        21720            0         4848
-/+ buffers:              34548        26568
Swap:            0            0            0
root@Arduino:/overlay# df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                    3.3G    159.0M      3.0G   5% /
/dev/root                 7.5M      7.5M         0 100% /rom
tmpfs                    29.8M      2.8M     27.1M   9% /tmp
tmpfs                   512.0K         0    512.0K   0% /dev
/dev/sda2                 3.3G    159.0M      3.0G   5% /overlay
overlayfs:/overlay        3.3G    159.0M      3.0G   5% /
/dev/sda1                 4.0G     12.0K      4.0G   0% /mnt/sda1
root@Arduino:/overlay# 

Thanks,
Mona Jalal

**Comment by frxnz** [comment]
@lamiastella Installing J5 requires a lot of memory, which the Yun is severely lacking out of the box. One solution is to enable a swap partition, effectively giving the Linux distro more memory. I'm assuming you used [these instructions](http://www.arduino.cc/en/Tutorial/ExpandingYunDiskSpace) to expand the disk space. There's actually a [newer version of that sketch](https://github.com/Fede85/YunSketches/blob/master/YunDiskSpaceExpander/YunDiskSpaceExpander.ino) that adds a prompt for enable a swap partition. You can also do this via SSH, but its quite a bit more complicated.

Some people have also gotten around this issue by installing J5 on another computer and transferring the files to the Yun. This typically works, but there are some compiled libs that might cause issues.

That being said, I don't know of a single person successfully using Johnny-Five on a Yun. I do know of multiple people that have bricked their Yuns trying.
