### ISSUE TITLE
Reflectance Array Support and "Shields"

### ISSUE THREAD

**Issue by BrianGenisio** [rwaldron/johnny-five#479]
I'm thinking of adding support for Reflectance Arrays.  Specifically, I am looking at the [Pololu QTR devides](http://www.pololu.com/category/123/pololu-qtr-reflectance-sensors), but I think it should be generic.  I'll probably send a PR based on a port of the [Arduino Driver](https://github.com/pololu/qtr-sensors-arduino).

Since it acts more like a shield (takes up to 7 pins and is a composite device), I wonder if it makes sense to bring this into the `five.Shield()` abstraction in `lib/definitions/shields` like the AdaFruit shields we are talking about.

But these devices aren't really "Shields".  And "Shields" aren't always the right word.  BeagleBone uses "Capes", for example.  I wonder if `five.Shield()` should be `five.Expansion()` to support any type of attachable "shields" as well as composite devices like these Reflectance Arrays.

Or, a generic `five.ReflectanceArray()` is more prudent.  

Thoughts?

**Comment by rwaldron** [comment]
We did this! Hooray!
