### ISSUE TITLE
Error on "npm install johnny-five" with Windows 7

### ISSUE THREAD

**Issue by ThomasDeutsch** [rwaldron/johnny-five#48]
Hi everyone.
I tried to install johnny-five on my Windows system - anyone tried this??

**Comment by Alexaas** [comment]
Hi, I have problems installing it on Win 8.1 with VS Express 2015. I get a lot of build errors during installation. Any idea what this could be? 
Btw. what is ment by "make sure you have the C++ dependencies checked" ??

**Comment by fivdi** [comment]
>Hi, I have problems installing it on Win 8.1 with VS Express 2015. I get a lot of build errors during installation. Any idea what this could be?

@Alexaas what version on Node.js is being used? If it's Node.js 4.x, the build errors are likely to be related to serialport which is in the process of being upgraded to support Node.js 4. If this is the case, see https://github.com/voodootikigod/node-serialport/issues/578 for further details.

>Btw. what is ment by "make sure you have the C++ dependencies checked" ??

Not sure, but would guess that it meant that a checkbox needed to be checked during the VS2010 install process.

**Comment by AlexDmr** [comment]
Same situation with windows 10 and VS Express 2015, NodeJS 4.1.1.
Here are the erros :+1:   enumser.cpp
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(263): error
C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)' : function template has already been defined (..\src\serialport.cpp
) [C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
          C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(25
  6) : see declaration of '_NanEnsureLocal'
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(661): error
C3083: 'smalloc': the symbol to the left of a '::' must be a type (..\src\serialport.cpp) [C:\Enseignements\2015\miniSe
rverMM\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(661): error
C2039: 'FreeCallback' : is not a member of 'node' (..\src\serialport.cpp) [C:\Enseignements\2015\miniServerMM\node_modu
les\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(661): error
C2061: syntax error : identifier 'FreeCallback' (..\src\serialport.cpp) [C:\Enseignements\2015\miniServerMM\node_module
s\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(665): error
C2065: 'callback' : undeclared identifier (..\src\serialport.cpp) [C:\Enseignements\2015\miniServerMM\node_modules\john
ny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(665): error
C2065: 'hint' : undeclared identifier (..\src\serialport.cpp) [C:\Enseignements\2015\miniServerMM\node_modules\johnny-f
ive\node_modules\serialport\build\serialport.vcxproj]
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(672): error
C2665: 'node::Buffer::New' : none of the 4 overloads could convert all the argument types (..\src\serialport.cpp) [C:\E
nseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
          C:\Users\Alexandre\.node-gyp\4.1.1\include\node\node_buffer.h(43): could be 'v8::MaybeLocal<v8::Object> node:
  :Buffer::New(v8::Isolate *,char *,size_t)'
          C:\Users\Alexandre\.node-gyp\4.1.1\include\node\node_buffer.h(31): or       'v8::MaybeLocal<v8::Object> node:
  :Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
          while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(676): error
C2664: 'v8::Local<v8::Object>::Local(const v8::Local<v8::Object> &)' : cannot convert argument 1 from 'v8::MaybeLocal<v
8::Object>' to 'const v8::Local<v8::Object> &' (..\src\serialport.cpp) [C:\Enseignements\2015\miniServerMM\node_modules
\johnny-five\node_modules\serialport\build\serialport.vcxproj]
          Reason: cannot convert from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object>'
          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be cal
  led
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(683): error
C2039: 'Use' : is not a member of 'node::Buffer' (..\src\serialport.cpp) [C:\Enseignements\2015\miniServerMM\node_modul
es\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(683): error
C3861: 'Use': identifier not found (..\src\serialport.cpp) [C:\Enseignements\2015\miniServerMM\node_modules\johnny-five
\node_modules\serialport\build\serialport.vcxproj]
..\src\win\enumser.cpp(443): warning C4996: 'GetVersionExA': was declared deprecated [C:\Enseignements\2015\miniServerM
M\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
          C:\Program Files (x86)\Windows Kits\8.1\Include\um\sysinfoapi.h(433) : see declaration of 'GetVersionExA'
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(263): error
C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)' : function template has already been defined (..\src\serialport_win
.cpp) [C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
          C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(25
  6) : see declaration of '_NanEnsureLocal'
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(661): error
C3083: 'smalloc': the symbol to the left of a '::' must be a type (..\src\serialport_win.cpp) [C:\Enseignements\2015\mi
niServerMM\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(661): error
C2039: 'FreeCallback' : is not a member of 'node' (..\src\serialport_win.cpp) [C:\Enseignements\2015\miniServerMM\node_
modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(661): error
C2061: syntax error : identifier 'FreeCallback' (..\src\serialport_win.cpp) [C:\Enseignements\2015\miniServerMM\node_mo
dules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(665): error
C2065: 'callback' : undeclared identifier (..\src\serialport_win.cpp) [C:\Enseignements\2015\miniServerMM\node_modules\
johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(665): error
C2065: 'hint' : undeclared identifier (..\src\serialport_win.cpp) [C:\Enseignements\2015\miniServerMM\node_modules\john
ny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(672): error
C2665: 'node::Buffer::New' : none of the 4 overloads could convert all the argument types (..\src\serialport_win.cpp) [
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
          C:\Users\Alexandre\.node-gyp\4.1.1\include\node\node_buffer.h(43): could be 'v8::MaybeLocal<v8::Object> node:
  :Buffer::New(v8::Isolate *,char *,size_t)'
          C:\Users\Alexandre\.node-gyp\4.1.1\include\node\node_buffer.h(31): or       'v8::MaybeLocal<v8::Object> node:
  :Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
          while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(676): error
C2664: 'v8::Local<v8::Object>::Local(const v8::Local<v8::Object> &)' : cannot convert argument 1 from 'v8::MaybeLocal<v
8::Object>' to 'const v8::Local<v8::Object> &' (..\src\serialport_win.cpp) [C:\Enseignements\2015\miniServerMM\node_mod
ules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
          Reason: cannot convert from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object>'
          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be cal
  led
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(683): error
C2039: 'Use' : is not a member of 'node::Buffer' (..\src\serialport_win.cpp) [C:\Enseignements\2015\miniServerMM\node_m
odules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(683): error
C3861: 'Use': identifier not found (..\src\serialport_win.cpp) [C:\Enseignements\2015\miniServerMM\node_modules\johnny-
five\node_modules\serialport\build\serialport.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
70:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Enseignements\\2015\\miniServerMM\\node_modules\\joh
nny-five\\node_modules\\serialport\\build\\serialport\\v1.7.4\\Release\\node-v46-win32-x64\\serialport.node" "--module_n
ame=serialport" "--module_path=C:\\Enseignements\\2015\\miniServerMM\\node_modules\\johnny-five\\node_modules\\serialpor
t\\build\\serialport\\v1.7.4\\Release\\node-v46-win32-x64"
gyp ERR! cwd C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Enseignements\2015\
miniServerMM\node_modules\johnny-five\node_modules\serialport\build\serialport\v1.7.4\Release\node-v46-win32-x64\serialp
ort.node --module_name=serialport --module_path=C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules
\serialport\build\serialport\v1.7.4\Release\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\nod
e_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Enseignements\\2015\\miniServerMM\\node_modules\\jo
hnny-five\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport
node-pre-gyp ERR! node -v v4.1.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Enseignements\2015\miniServerMM\node_modules\johnn
y-five\node_modules\serialport\build\serialport\v1.7.4\Release\node-v46-win32-x64\serialport.node --module_name=serialpo
rt --module_path=C:\Enseignements\2015\miniServerMM\node_modules\johnny-five\node_modules\serialport\build\serialport\v1
.7.4\Release\node-v46-win32-x64' (1)
npm WARN optional dep failed, continuing serialport@1.7.4

**Comment by rwaldron** [comment]
@AlexDmr Node.js 4.x support is in progress.

**Comment by Alexaas** [comment]
@rwaldron Could you please give an update here once it should work with Node.js 4.x?

**Comment by dtex** [comment]
@rwaldron I propose creating an issue for node 4.x support that details the state of things that we can just point everyone to. Much like @jacobrosenthal did over on the serialport repo. I'm traveling all day, but will write one up tonight.

**Comment by playteka** [comment]
@rwaldron , @ThomasDeutsch , @voodootikigod , I think ask people to install visual studio just for installing johnny-five is too heavy. VS is around 10GB. Can you think about light solution like gcc(mingw) on windows?

**Comment by rwaldron** [comment]
That hasn't been necessary for almost two years—serialport auto builds pre-compiled binaries for every release

**Comment by dtex** [comment]
We need to update the [wiki](https://github.com/rwaldron/johnny-five/wiki/Getting-Started#windows)

**Comment by vitaliyazvinski** [comment]
@playteka @rwaldron 
No need to install whole VS, [windows build tools](https://github.com/felixrieseberg/windows-build-tools) is enough:
`npm --add-python-to-path install --global --production windows-build-tools`
It will install python and will add it into PATH. It was enough to start blink example.
BTW it works on node v6.11.2 **x64**
