### ISSUE TITLE
LCD: I2C device/controller profiles

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#486]
- [ ] Refactor LCD implementation into a device/controller profile based design
- [ ] Implement support for at least one I2C LCD device

Examples of device/controller profile designs: 

- https://github.com/rwaldron/johnny-five/blob/master/lib/motor.js
- https://github.com/rwaldron/johnny-five/blob/master/lib/compass.js

Notes: 

- Existing LCD tests must pass for refactor and new implementation
- Existing LCD code must still function without changes

Example Usage: 

```js
// Initialize an RGB LCD
var lcd = new five.LCD({
  controller: "JHD1313M1" // the model number
});

// Initialize an OLED LCD
var lcd = new five.LCD({
  controller: "SSD1308" // the model number
});

```

Suggested devices: 

- MCP23008
  - https://learn.adafruit.com/i2c-spi-lcd-backpack/connect-to-i2c
- JHD1313M1 
  - https://github.com/intel-iot-devkit/upm/blob/master/src/lcd/jhd1313m1.cxx
  - http://iotdk.intel.com/docs/master/upm/classupm_1_1_jhd1313m1.html
- LCM1602
  - http://iotdk.intel.com/docs/master/upm/classupm_1_1_lcm1602.html
  - https://github.com/intel-iot-devkit/upm/blob/master/src/lcd/lcm1602.cxx
- SSD1308
  - http://iotdk.intel.com/docs/master/upm/classupm_1_1_s_s_d1308.html
  - https://github.com/intel-iot-devkit/upm/blob/master/src/lcd/ssd1308.cxx

cc @deathbearbrown

**Comment by nofear87** [comment]
@rwaldron  you get it working?

**Comment by rwaldron** [comment]
@nofear87 yes, but I haven't landed the patch yet. Unfortunately I just left my house to drive to Boston—I won't be able to get back to this until tomorrow

**Comment by nofear87** [comment]
@rwaldron are there some updates for me :-)

**Comment by rwaldron** [comment]
@nofear87 yes: I've pushed all the work to this branch: https://github.com/rwaldron/johnny-five/tree/PCF8574

**Comment by nofear87** [comment]
Thank you very much! I will test it today!

**Comment by nofear87** [comment]
@rwaldron 
eg/lcd-all.js
eg/lcd-i2c-PCF8574.js
lib/lcd-chars.js
lib/lcd.js
test/lcd.js

I only have to overwrite these files, right? How can I find the pin setup I have to realize?

**Comment by rwaldron** [comment]
The only pins are V, G, SDA, SCL. The chip on the LCD backpack will say PCF8574 or PCF8574A, then follow the example in the commit

**Comment by rwaldron** [comment]
Overwrite? Just make a new branch in your local repo and pull PCF8574 branch onto it

**Comment by nofear87** [comment]
I haven't a repo...I use npm to organize git repos. Is there also the possibility to pull your branch?

**Comment by rwaldron** [comment]
Try changing this: 

```js
var lcd = new LCD({
  controller: "LCM1602",
  board: this.board
});
```

To this: 

```js
var lcd = new five.LCD({
  controller: "LCM1602"
});
```

The LCD class located at `five.LCD` (assuming you have `var five = require("johnny-five");`) and `board: this.board` is unnecessary.

**Comment by nofear87** [comment]
@rwaldron works like a charm...thank you very very much!

**Comment by rwaldron** [comment]
That's awesome. I will land the branch this week and it will be available via npm (we have some other stuff to address first :)

**Comment by gabrielpapke** [comment]
Hi @rwaldron, firstly, congratulations to Johnny-five project, is exciting.
I'm beginner yet, and i have some difficulties to use my LCD display with johnny-five framework, the model is i2c PCF8574T, and i tried to use your example for tests, but doesn't work.
Is there some reason to not work?
Thanks.

**Comment by rwaldron** [comment]
@gabrielpapke can you share your code?

To initialize that device: 

```js
var lcd = new five.LCD({
  controller: "PCF8574"
});
```

I will add an alias for `PCF8574T`

**Comment by rwaldron** [comment]
Added.

```js
var lcd = new five.LCD({
  controller: "PCF8574T"
});
```

**Comment by gabrielpapke** [comment]
When i initialize the device the display show only box like [this image](http://www.michaelkahane.com/blog/wp-content/uploads/2012/10/IMAG0352.jpg)
And [this](http://i2.wp.com/cdn3.bigcommerce.com/s-vt19phz/product_images/uploaded_images/tronixlabs-i2c-backpack-arduino-tutorial-5.jpg?resize=450%2C425) is my component.

This is my code:
```javascript
var five = require("johnny-five/lib/johnny-five.js");

var board = new five.Board();

board.on("ready", function() {
  var l = new five.LCD({
    controller: "PCF8574"
  });

  l.useChar("heart");
  l.cursor(0, 0).print("hello : heart:");
  l.blink();
  l.cursor(1, 0).print("Blinking? ");
});
```

Thanks for attention.

**Comment by rwaldron** [comment]
> ```js
var five = require("johnny-five/lib/johnny-five.js");
```

Are you running this code from the repo or from an npm install?

------

> And this is my component.

![](http://i2.wp.com/cdn3.bigcommerce.com/s-vt19phz/product_images/uploaded_images/tronixlabs-i2c-backpack-arduino-tutorial-5.jpg)


The good news is that I have that exact same LCD, so I was able to identify the actual chip model. Unfortunately, the example you've provided isn't using the correct controller, and my last fix overlooked the alternate default I2C slave address. I've just updated Johnny-Five's LCD class and confirmed on 4 separate LCD components. 

This code works correctly when using the LCD in the image above: 

```js
// From the repo eg/ dir: 
// var five = require("../");
// From an npm install: 
var five = require("johnny-five");
var board = new five.Board();

board.on("ready", function() {

  var lcd = new five.LCD({
    controller: "PCF8574AT"
  });

  lcd.useChar("heart");
  lcd.cursor(0, 0).print("hello :heart:");
  lcd.blink();
  lcd.cursor(1, 0).print("Blinking? ");
});
```

Note that the controller is **PCF8574AT**, that's the chip model as printed on the chip itself. This is very important, as it determines which default address to use. 

Here's a video of the above code with the same LCD: https://www.youtube.com/watch?v=thFte7gjoNI

**Comment by gabrielpapke** [comment]
I'm using the code from repo, i have updated the repo but still not working :(
I tried with controllers: **PCF8574T, PCF8574AT, PCF8574** again.
The same problem: when I initialize the device the display show only boxes.
Is it because the chip model is different from yours? **PCF8574T** without the "A" letter.

Thanks for attention.

**Comment by rwaldron** [comment]
> I tried with controllers: PCF8574T, PCF8574AT, PCF8574 again.
> The same problem: when I initialize the device the display show only boxes.
> Is it because the chip model is different from yours? PCF8574T without the "A" letter.

Whatever the chip number on your chip, use that.


Can you share a picture of your own wiring?

**Comment by gabrielpapke** [comment]
![img_4309](https://cloud.githubusercontent.com/assets/5304816/6477653/97337806-c204-11e4-9b34-e002ec21890d.JPG)
This is my wiring, is there something wrong?
(The reflex is a bit disturbing, sorry)

**Comment by rwaldron** [comment]
Sorry if this is a dumb question, but you've made sure that StandardFirmata is on the board, correct?

Can you take a picture of the back of the LCD, as close as possible but without blurring the writing on the chip and the pcb? I really appreciate your patience :)

Also, this picture is really great :) I _think_ I might've noticed something, but I can't be sure—can you take a look at these solder points: 

![](https://dl.dropboxusercontent.com/u/3531958/lcd-soldering-points.jpg)

(This may be nothing at all, but I know I'd look closer at them if I could)

**Comment by gabrielpapke** [comment]
Thanks for your patience too!
No problem, the StandardFirmata is on board, i'm using others components and they are working :)

I don't have so much experience with solder, the solder can not touch each other?
Sorry if this is a dumb question haha

Sorry about my english, I from Brazil and i speak portuguese.

Take a look at the pictures:
![img_4317](https://cloud.githubusercontent.com/assets/5304816/6498381/3377582a-c2ca-11e4-95cb-716f933802ae.JPG)
![img_4313](https://cloud.githubusercontent.com/assets/5304816/6498413/7dc1901c-c2ca-11e4-8be8-1b9866e1e77a.JPG)

Thanks!

**Comment by rwaldron** [comment]
> I don't have so much experience with solder, the solder can not touch each other?

Correct—each solder joint must be "isolated" such that it only affects the circuit nodes that it's connecting. If any of those are touching on the LCD, then it could (at least) not work correctly or (at worst) permanently damage the LCD.

Do you have access to a multimeter? If you do, set it to "continuity" mode, look for this icon: 

![](http://lizarum.com/assignments/physical_computing/images/multimeter/conticon3.jpg)

Then touch and hold the two probes together, you will hear a beep when they are touching—this is just a self check. Now touch and hold the probes to any two solder joints at a time—there should be no "long beep" (some multimeters have a short tone for low ohm continuity and a continuous tone for continuity). 

> Sorry if this is a dumb question haha

Don't be sorry—this is how we learn together :)

**Comment by gabrielpapke** [comment]
A don't have access to a multimeter now, but I already test the LCD with C++ code directly with Arduino, and it works.
The problem can be still in the LCD? If the problem can be on the LCD, I will provide a multimeter.

Thanks for the tips. :)

**Comment by rwaldron** [comment]
If it works with the C code, then it's not the LCD. That also means that I don't know what's wrong and I'm completely out of ideas :( I have about 10 LCDs here, 3 of which are variations of yours, 1 that is identical and all of them work for me, so I'm at a loss.

**Comment by asit569** [comment]
@gabrielpapke adjust the potentiometer backside the lcd in controller

**Comment by pomek** [comment]
Hey,

@rwaldron, I have the same issue like @rwaldron… And also, I've tested with C++ code - everything works fine. Unfortunately, with Johny-Five it does not work correctly. 

But, what I have noticed… I think, the program (code below) was not loaded to Arduino, because my previous program (some operations with expander _PCF8574_ still working - LED are lighting). Perhaps it is some tip for you.

```js
var five = require("johnny-five");
var board = new five.Board();

board.on("ready", function() {
  var random = Math.random().toString(36).replace(/[^a-z]+/g, "").substr(0, 4).toUpperCase();

  var l = new five.LCD({
    controller: "PCF8574T"
  });

  l.useChar("heart");
  l.cursor(0, 0).print("hello :heart:");
  l.blink();
  l.cursor(1, 0).print("Blinking? ");
  l.cursor(0, 10).print(random);
});
```

**Comment by aimerib** [comment]
@rwaldron Just wanted to say that thanks to your help troubleshooting gabrielpapke's problem I decided to take a closer look at my own lcd and noticed two leads slightly touching making my ic2 code never work, yet I could bypass the ic2 chip altogether and connect the lcd to the arduino directly and it would work! This saved me from hours of frustration, so thank you!
