### ISSUE TITLE
Servo not working with johnny-five and raspi-io

### ISSUE THREAD

**Issue by davidrs** [rwaldron/johnny-five#499]
If I try to initialize a pin as a servo in johnny-five with raspi-io I get an error:
`Error: Pin "7" does not support mode "undefined"`

stack trace points to:
raspi: 133
lib/servo.js: 87
lib/servo.js: 141

Raspberry pi B+ running johnny five and raspi-io
It is working if I set an LED to strobe, so I think everything is setup properly in my env.

P.S Thank you so much for this awesome lib!

Cross posted on raspi-io repo because I'm not sure where the issue is:
https://github.com/bryan-m-hughes/raspi-io/issues/1

**Comment by dtex** [comment]
This landed in rasp-io about a year ago so I'm closing the issue.

@davidrs If you're still having issues feel free to reopen.
