### ISSUE TITLE
beaglebone-io & i2c head scratcher

### ISSUE THREAD

**Issue by MrYsLab** [rwaldron/johnny-five#524]
I have implemented i2c support for the beaglebone-io plugin using the i2c npm module. I have tested the code with eg/led-matrix-demo.js and it works identically on both Arduino and the BBB. I have also tested a TMP-102 temperature module with a quick and dirty lib module/demo (not yet ready for publishing). Again, both Arduino and BBB work identically and correctly.

I am having problems however when i run eg/compass.js. It works fine on my Arduino, but when I run it on the BBB I get one good sample and then it just reports back "data undefined" ad infinitum. I am using a 2 amp external power supply with the BBB so I don't think this is a power issue.

Here is my console output:

debian@beaglebone:~$ sudo node compass.js
1417880024942 Device(s) BeagleBone-IO 
1417880024975 Connected BeagleBone-IO 
1417880024979 Repl Initialized

heading 339
bearing { name: 'North-NorthWest',
abbr: 'NNW',
low: 331.88,
mid: 337.5,
high: 343.12,
heading: 339 }
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
at process.EventEmitter.addListener (events.js:160:15)
at process.on.process.addListener (node.js:769:26)
at new i2c (/home/debian/node_modules/beaglebone-io/node_modules/i2c/lib/i2c.coffee:34:15)
at BeagleBone.sendI2CReadRequest (/home/debian/node_modules/beaglebone-io/lib/beaglebone.js:367:14)
at Compass. (/home/debian/node_modules/johnny-five/lib/compass.js:91:13)
at wrapper as _onTimeout
at Timer.listOnTimeout as ontimeout
data undefined

Any ideas what I might look at or try?

**Comment by MrYsLab** [comment]
@fivdi @rwaldron Thanks for the heads up. So, I see the changes in the Firmata code where the new methods were added. Looking at compass.js in j5/lib the original calls are still there, so does that mean that we need to support both the old calls and new calls? Not a big deal, but before I go ripping code out, I just want to know the path forward.

**Comment by fivdi** [comment]
Yes, the old and new calls will need to be supported.

**Comment by MrYsLab** [comment]
Ok, I will take a look. I assume your library will not change as a result. Correct?

**Comment by fivdi** [comment]
I'd say that's correct.

**Comment by MrYsLab** [comment]
Ok, I will open up a new issue and start working on it in the next few days. I have an adxl345 so I can test out some of the calls using the new interface.

**Comment by rwaldron** [comment]
The old style API will be going away eventually. I should do the updates in Johnny-Five ASAP

**Comment by MrYsLab** [comment]
@rwaldron A heads up when that is complete would be great. Until then, I will leave the "old" stuff in.

**Comment by rwaldron** [comment]
Will do!
