### ISSUE TITLE
ESC

### ISSUE THREAD

**Issue by carldanley** [rwaldron/johnny-five#530]
I'm trying to use this ESC: https://traxxas.com/products/parts/otherparts/xl5waterproof. I have jumper wires that run from the ground and input on the ESC to the arduino. The arduino is being powered by my macbook (over USB) and the ESC is being powered properly with the RC car's battery.

I'm running this code:
```
const five = require('johnny-five');
const board = new five.Board();

board.on('ready', function() {

  // ENGINE
  const motorServo = new five.Servo({
    pin: 10
  });

  this.repl.inject({
    s: motorServo
  });
  
});
```

From the repl, I can run `s.to(90)` to stop the motor. I can increase the speed from 90 to 160 where 160 is the maximum speed (35mph) for the RC car.

The RC car is supposed to be able to reverse and I've found that no matter what values I use, I cannot switch from forward to reverse and back. I've gotten both directions to work independently but I do not know what I did to get them to work.

Any suggestions or ideas as to what I need to be doing for this to work properly?

**Comment by landshark22** [comment]
Did anyone ever solve this problem? We are having a few issues communicating with our ESC including getting reverse to work properly.

**Comment by rwaldron** [comment]
No, not yet. @carldanley was going to ship his bot to me so I could work on it... not sure if that's still the plan. I just bought an ESC that has reverse capabilities—that will be here on Tuesday, which is the soonest I can work on this. I appreciate your patience :)

**Comment by rwaldron** [comment]
I just found this on another site...

> More or less all ESCs have a similar calibration procedure:
> - Power up the ESC while the having maximum forward throttle applied
> - You’ll hear a tone and some beeps and after a while (usually 2 seconds) you’ll hear a confirmation tone and the led will blink a few times with a different color: this indicates that the ESC has measured the wavelenght of max throttle.
> - At this point apply zero throttle (in a fwd/reverse ESC this means full throttle reverse), wait again few seconds for the tones and led to blink: full reverse measured.
> - Then move to central (only for fwd/reverse ESCs) and wait again for the tone and blinks.


Have you tried calibrating like this?

**Comment by carldanley** [comment]
@rwaldron Thanks for the reminder! Email me your address so I can send my RC car your way.

**Comment by rwaldron** [comment]
@carldanley let's hold off on that. I have a bidirectional ESC on it's way, so it might be able to solve this without needing your entire RC car :D

**Comment by rwaldron** [comment]
Just an update: my speed controller arrived, so I can start working on this on my end.

**Comment by carldanley** [comment]
Awesome, let me know if you need anything. I can also test code on my end as well.

**Comment by landshark22** [comment]
Update from us as well. We played with it a bit more after I posted this the other day and we were able to figure out we do have reverse. I have not yet tried the calibration procedure above. 

I don't have my notes in front of me, but as far as I remember this is what we came up with for the HobbyKing ESC mentioned previously.

50 was the start/reset point. 
45-54 Motor would not spin

Forward:
55-85 was the adjustable speed range moving forward. 
85-100 no noticeable increase in speed for us.

Reverse:
46-30 If I remember correctly, this was the adjustable range in reverse, I'll double check my notes when I get home, but I do remember the range was minimal as compared to forward. 
29-0 Motor would not spin (again I will check these values)

Some interesting notes:

if you set a forward value say 60 and set the next value at 35 the motor would stop almost like popping a circuit breaker. at this point no value forward or reverse would spin the motor. We would then need to send the value of 50 to "reset" the ESC and then we were able to enter af FWD or REV value. Of course most people would not be controlling a motor like this, just thought it was an interesting point to note.

**Comment by rwaldron** [comment]
Your notes here are really helpful (thank you), they confirm the understanding I've come to have for 3 stage (Forward, Brake, Reverse) brushed motor speed controllers. Specifically: the forward window is greater, with a larger range and speed capability, than the reverse range. 

> if you set a forward value say 60 and set the next value at 35 the motor would stop almost like popping a circuit breaker. at this point no value forward or reverse would spin the motor.

This unit likely has an internal BEC that's sensing a jump and automattically shutting down. These are commonly built in to protect all components that are connected to the controller.


I've just ordered two more speed controllers to keep testing, they should be here tomorrow.

**Comment by carldanley** [comment]
@landshark22 do you have some sample code (maybe a gist) of the portion that controls the ESC? I want to test your calculations from my end as well.

**Comment by rwaldron** [comment]
@carldanley this is useful, if you have a speed controller programmer:  http://www.axialracing.com/blog_posts/787000000 

I made it into an Arduino C program as well: 

```ino
#include <Servo.h>

#define MAX 2000
#define MIN 1000
#define NEUTRAL 1500
#define MOTOR_PIN 11


Servo esc;

int aV = 0;
int sV = 0;
int lV = 0;
int step = 0;

void setSpeed(int speed) {
  esc.writeMicroseconds(speed);
}

void setup() {
  Serial.begin(9600);

  esc.attach(MOTOR_PIN);
}

void loop() {
  // To reset the process, type a character into the serial monitor and press <enter>
  while (Serial.available()) {
    step = 0;
    aV = 0;
    Serial.read();
    Serial.println("Reset");
  }

  int v = analogRead(A0);

  if (v != aV) {
    aV = v;
    lV = sV;
    sV = map(v, 0, 1023, MIN, MAX);

    if (sV == MAX && step == 0) {
      Serial.println("Hold speed at MAX and turn on Speed Controller");
      setSpeed(sV);
      step = 1;
    }

    if (sV == MIN && step == 1) {
      Serial.println("Hold speed at MIN");
      setSpeed(sV);
      step = 2;
    }

    if (sV == NEUTRAL && step == 2) {
      Serial.println("Hold speed at NEUTRAL");
      setSpeed(sV);
      step = 3;

      delay(2000);
      step = 0;
    }

    if (step == 0) {
      setSpeed(sV);
    }
  }
}
```

(Hook up a rotary potentiometer to A0)

**Comment by landshark22** [comment]
>This unit likely has an internal BEC that's sensing a jump and automattically shutting down. These are commonly built in to protect all components that are connected to the controller.

@rwaldron I figured it was something like that. 


@carldanley, this is what we've been using and I'll preface this by saying I don't know if it's right, I just now it's been working, I am starting from 0 in coding my daughter is just as green as I am so we struggled for a while to get this to work: 

```
var five = require("johnny-five");
var board = new five.Board();

board.on("ready", function() {

  var esc = new five.ESC(9);
  range: [ 0, 100 ];
  
  this.repl.inject({
    esc: esc
  });
});
```

and we use the following command to adjust speed

```
esc.speed (60)
```

**Comment by rwaldron** [comment]
Whoa, this is awesome—there is a line of code that does literally nothing, but it's **totally** valid syntax! Check it out: 


```js
range: [ 0, 100 ];
```

This is effectively a no-op, because `range:` is parsed as _LabelledStatement_, whose _Statement_ is just an _Expression_ (_ArrayInitializer_).


Ok, enough nerding out... You don't actually need to set that range for ESC—`[0, 100]` is the default :)


```js
var five = require("johnny-five");
var board = new five.Board();

board.on("ready", function() {

  var esc = new five.ESC(9);

  this.repl.inject({
    esc: esc
  });
});
```

**Comment by landshark22** [comment]
Cool, that's great. We'll try that out. When things started moving we stopped messing with the code :) 

A little more info that may or maynot be helpful but worth adding I suppose. 

We have the motor/ESC connected to an Arduino Mega, the Mega is connected via USB to a Raspberry Pi 2 running Raspian. We are connected to the Ras Pi 2 via the ethernet connection and sending commands and editing the .js files using Orion also installed on the Pi. So far seems like everything is playing together nicely. 

Our ultimate goal is to get this working with a game controller of some sort over the network along with a browser interface. Our project is an Underwater ROV.

**Comment by rwaldron** [comment]
All information is useful :)

This sounds like an awesome project! I'll report back later today

**Comment by rwaldron** [comment]
Great news: I was able to figure out bidirectional control today. Additionally, I spent time with ESC, updating it to the controller model and adding support for PCA9685 (that's in review right now)

**Comment by rwaldron** [comment]
@carldanley I don't think "sport mode" will ever be supportable in any reasonable sense. "Sport Mode – Fwd / Brake / Rev", from what I've learned, this requires a "double tap" of the throttle—1 to brake and then it can be reversed. This isn't meant to be programmed by any code on any platform, this is for use with transmitter + receiver. "Training Mode" which splits the range into 50% forward and 50% reverse is supportable programmatically.

**Comment by carldanley** [comment]
That is excellent news. For knowledge purposes, are you mentioning that sport mode is only available when a transmitter/receiver is used? Is that some feature that the transmitter makes available to us? Sorry for the confusion.

Also, for the bidirectional support, did you need to modify anything in j5 for this to work OR did you adjust values until it worked like @landshark22 has been mentioning?

**Comment by rwaldron** [comment]
No, it's available, it's just something you did with your figure, and not with code. Johnny-Five needed some changes, I'll be pushing those soon

**Comment by rwaldron** [comment]
Here's a bit more detail...

----

The "Forward, Brake, Reverse" setting on all of the speed controllers that I've looked at in the last couple of days requires a "flick of the trigger finger" because it assumes you're using something like one of these: 

![](http://i00.i.aliimg.com/img/pb/803/732/221/1248771656649_hz_myalibaba_web14_16803.jpg)

![](http://www.rchelicopter.com/wp-content/uploads/2008/08/mode_2.jpg)

So you'd be pushing the throttle **Forward**; when you want to reverse you need to "flick" the throttle toward **Reverse** once and let it snap back to neutral, which is **Brake**. Once the throttle has snapped back to neutral, you can pull the throttle stick/trigger to **Reverse** the motor. 

----

The "Forward, Reverse" setting assumes the same controllers above, BUT this can also easily be programmed for, as there is no "double tap into reverse" necessary. There is a neutral pulse (the center of the max and min pulse); **Forward** is neutral -> max (stopped -> full speed) and **Reverse** is neutral -> min (stopped -> full speed).

**Comment by Resseguie** [comment]
Just a clarifying remark for those not familiar with these transmitters. The concept of "pushing the throttle forward" applies to the second type that Rick shows. It's physically reversed in the trigger style transmitter where you "pull the trigger" to drive forward and "push the trigger away from you" to brake/reverse. Wanted to make sure we didn't get confused with physical direction of the throttle mechanism and the direction the vehicle drives.

**Comment by Resseguie** [comment]
(this stuff is hard to describe in just text!)

**Comment by rwaldron** [comment]
Oh man, while I wrote that I was describing the physical act—as I actually did it in real life—with the the second style controller. Thanks for the additional clarification, because THAT would've been confusing :D

**Comment by carldanley** [comment]
This makes total sense now; thanks for taking the time to explain it @rwaldron!

@Resseguie - you're absolutely right; just one of those things that's difficult to read through.

**Comment by landshark22** [comment]
Ok, great news

bur here's couple of a really stupid newb questions. 

1. How do I check the currently installed version of johnny-five (installed on a Ras Pi 2 running Raspian)

tried:

```
johnny-five -v
```
and received a "command not found" error

2. How do I upgrade to the latest? 

I attempted this: 
```
sudo apt-get update 
```
and then:
```
sudo apt-get upgrade johnny-five
```
lots happened just not sure if we got the latest. 

Not only are we new to coding also new to Linux.

**Comment by rwaldron** [comment]
> bur here's couple of a really stupid newb questions.

:P no such thing. 


> johnny-five -v

There is no Johnny-Five binary, if your project has a package.json, then presumably that file has the version installed listed?

> sudo apt-get upgrade johnny-five

Johnny-Five isn't a package that's available this way. 

----

The patch for this ESC issue isn't released yet, I'm waiting to try a few more ESCs. Once it is, then you'll be able to update on the Pi with: 

```
npm install johnny-five
```


Hopefully this helped?

**Comment by landshark22** [comment]
It did thanks.

**Comment by rwaldron** [comment]
Great!
