### ISSUE TITLE
question: Pin reuse

### ISSUE THREAD

**Issue by boneskull** [rwaldron/johnny-five#548]
If I do this:

```js
var rgb = new Led.RGB(9, 10 11);
```

Then use the `rgb` object as in the [rainbow example](https://github.com/rwaldron/johnny-five/blob/master/eg/led-rainbow.js), everything works great.

However, if I do this:

```js
var rgb = new Led.RGB(9, 10, 11);
var red = new Pin(9), green = new Pin(10), blue = new Pin(11);
```

Then, the exact same "rainbow" code does nothing; the LED never turns on. 

If I had to hazard a guess, instantiating the `Pin`s after the `Led.RGB` instance causes the `Pin`s to be put in the incorrect mode--but, of course, not sure, so that's why I'm asking (my other guess would be that this is a `firmata` problem).

Any workarounds for this?  I'm just experimenting here.

* * *

Also, doing this:

```js
var rgb = new Led.RGB(9, 10, 11);
var red = new Pin({addr: 9, type: 'analog'});
```

causes the following exception:

```
    this.pins[this.analogPins[pin]].report = value;
                                           ^
>> TypeError: Cannot set property 'report' of undefined
    at Board.reportAnalogPin (/Volumes/samara/projects/boneskull/sparkfun/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:1214:44)
    at Board.analogRead (/Volumes/samara/projects/boneskull/sparkfun/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:567:8)
    at new Pin (/Volumes/samara/projects/boneskull/sparkfun/node_modules/johnny-five/lib/pin.js:122:25)
```

This looks like "user error", but it should probably be more friendly.

**Comment by rwaldron** [comment]
Fixed in https://github.com/rwaldron/johnny-five/commit/870e6894268f959a13e9aa6123c0ea94826c0a85
