### ISSUE TITLE
Sensor emits null argument too much

### ISSUE THREAD

**Issue by boneskull** [rwaldron/johnny-five#553]
For most/all events emitted in `Sensor`, the first argument is the variable `err`, which seems to always be `null`.  Remove it?

**Comment by divanvisagie** [comment]
@rwaldron As action was taken and 2 new issues raised from this thread, I assume this issue can be closed.

**Comment by rwaldron** [comment]
Yeah, that's fine. I'm maintaining the patch until we commit to 0.9.0

**Comment by dtex** [comment]
Stale Bot, no!
