### ISSUE TITLE
Standard Event object

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#569]
### Proposal: All events will emit a standard Event object.

See: #561

``` js
function Event(opts) {
  this.timestamp = Date.now();
  this.type = opts.type || "data";
  this.data = opts.data || null;
  this.target = opts.target;
}
```

``` js
// Example
this.emit("data", new Event({ data: adc }));
```

**This is a breaking change**

**Comment by rwaldron** [comment]
It occurs to me that we can limit how much this breaks by making this a standard _second_ argument.

**Comment by dtex** [comment]
What would the first argument be if not the faux error?

**Comment by rwaldron** [comment]
Whatever was previously the second argument :\

**Comment by scottgonzalez** [comment]
If you're changing the signatures with #561 anyway, I'd say you should just go all the way and do the standardization to a single argument.

**Comment by dtex** [comment]
Someone recently agreed to look at this issue so I am commenting to keep it fresh.

**Comment by dtex** [comment]
Not ready to close this one Stale Bot.

**Comment by HipsterBrown** [comment]
@ajfisher was showing me his audit of all the callbacks and event objects in the codebase. I wonder how we could share that somewhere.
