### ISSUE TITLE
Add PCA9685 controller support to Led wiki docs 

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#593]
https://github.com/rwaldron/johnny-five/wiki/Led

cc @frxnz

**Comment by frxnz** [comment]
I'm all over it

**Comment by frxnz** [comment]
This should be good to go.

- [x] Added `controller` and `address` to options
- [x] Added I2C Led to usage examples
- [x] Changed API examples to use pin 11 on PWM methods
- [x] Added link to `Led.RGB` PCA9685 example
