### ISSUE TITLE
Compass Docs breadboard diagram

### ISSUE THREAD

**Issue by deathbearbrown** [rwaldron/johnny-five#599]
Compass docs need a breadboard diagram:

- [x] [Breadboard diagram for API docs](https://github.com/rwaldron/johnny-five/wiki/Compass)
- [x] [Breadboard diagram for eg docs](https://github.com/rwaldron/johnny-five/blob/master/docs/nodeconf-compass.md)
- [x] sample code has been tested using the diagram

**Comment by rwaldron** [comment]
Working on this right now

**Comment by deathbearbrown** [comment]
@rwaldron you the best :dog: :sparkles:
