### ISSUE TITLE
LCD docs breadboard doesn't match the code

### ISSUE THREAD

**Issue by deathbearbrown** [rwaldron/johnny-five#602]
<https://github.com/rwaldron/johnny-five/blob/master/docs/lcd.md>

Check out the pins. Whoever makes the new board, please use "curvy wires and legs" (this is an option you can set in fritzing preferences.

**Comment by rwaldron** [comment]
I made some updates here, but there is still work to do

**Comment by Resseguie** [comment]
Looks like this has since been fixed.
Pins in example codes: 9ad3e0fe7469a3322cbcd6b972317d20fffaec19
Curvy wires: 8642174f50457cf069d7faebbcd0ab517cc7b475
