### ISSUE TITLE
IR Remote from node

### ISSUE THREAD

**Issue by sergionader** [rwaldron/johnny-five#613]
Hello, 

I need some help to put some pieces together. 
1) I can run https://github.com/shirriff/Arduino-IRremote with no problems in my Arduino Uno, so I can send raw data to remote control my TV. 
2) I can make my beaglebone black blink leds in my Arduino Uno using johnny-five (thank you!!!!)
3) What I need is a way to allow node to send those raw codes to arduino in order to let arduino send the IR signal to my TV. Using a web interface, user clicks on volume up button, for instance, and node sends the related raw code to arduino that sends it to the IRRemote library.  

Is that possible? Basically I need node to send parameters to an Arduino sketch. 

Any help will be appreciated. 

Thanks in advance and have you all a nice weekend. 

Sergio

**Comment by rwaldron** [comment]
Thanks for the report! Let's move the discussion over [here](https://github.com/rwaldron/johnny-five/issues/434)
