### ISSUE TITLE
ES-6 Exception Upon Starting j5 application

### ISSUE THREAD

**Issue by MrYsLab** [rwaldron/johnny-five#630]
The exception and details are documented here: https://github.com/bryan-m-hughes/raspi-io/issues/15

**Comment by rwaldron** [comment]
@MrYsLab I'm not sure what to do about this—if es6-shim isn't loading, it's not because of Johnny-Five :(

**Comment by MrYsLab** [comment]
Thanks Rick, I am going go close this, since @bryan-m-hughes is re-investigating. If need be I will reopen it.

**Comment by rwaldron** [comment]
Sounds good :)

I'll also pay attention to the original thread
