### ISSUE TITLE
extract JSCS config into .jscsrc

### ISSUE THREAD

**Issue by boneskull** [rwaldron/johnny-five#632]
JetBrains IDEs, and probably other text editors, support inline JSCS linting.  However, as long as the JSCS config is in the Gruntfile, they don't know what rules to use.

Cut the JSCS config from `Gruntfile.js` and paste it into a new `.jscsrc`.

**Comment by rwaldron** [comment]
Go for it!

**Comment by boneskull** [comment]
see PR #633
