### ISSUE TITLE
Button, Servo (and others?): isInverted or invert?

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#643]
Problem: 

- `Button` has a constructor options property called `invert`
- `Servo` has a constructor options property called `isInverted`

At this point I think we need to just make it so that _either_ will work on both, then drop one of them for 1.0

**Comment by dtex** [comment]
I'll patch servo to recognize both.

I like ```invert``` because ```isInverted``` is relative to what?

**Comment by rwaldron** [comment]
Yeah, agreed. I think in 1.0 we'll kill "isInverted" in favor of `invert`
