### ISSUE TITLE
Error in image button.png

### ISSUE THREAD

**Issue by bennysce** [rwaldron/johnny-five#645]
Hi, noticed on the lasercat workshop that the button image referred to at https://github.com/rwaldron/johnny-five/blob/master/docs/button.md is incorrect. I don't think that red wire is correctly placed on the board for it to work. The red wire has to be set in the same column as the leg for the button.

See johnny-five/docs/breadboard/button.png.

**Comment by aramperez** [comment]
I'm not that familiar with johnny-five yet, but if the code states "button = new five.Button(8);", shouldn't the yellow wire go to pin 8 on the Arduino instead of pin 2?

**Comment by rwaldron** [comment]
> I don't think that red wire is correctly placed on the board for it to work. 

You are correct :)

> I'm not that familiar with johnny-five yet, but if the code states "button = new five.Button(8);", shouldn't the yellow wire go to pin 8 on the Arduino instead of pin 2?

Also correct :)


Thanks for the bug reports—I'll have a fix for this asap.

**Comment by Resseguie** [comment]
@rwaldron FYI, you might just b e able to use the FZZ I did for your presentation a while back but move to pin 8.

https://www.dropbox.com/s/j8jkks2ojx4q8cz/button8.png?dl=0
https://www.dropbox.com/s/ckuk04d460rciqb/button8.fzz?dl=0

**Comment by Resseguie** [comment]
Never mind, you beat me to the update.
