### ISSUE TITLE
Does "QC1602A v2.0" LCD supported in J5? 

### ISSUE THREAD

**Issue by kisPocok** [rwaldron/johnny-five#658]
Hi,

I recently bought one (2 row, 16 col version) and I can't handle it with johnny-five. Could you help me?

Thanks,
D.

**Comment by rwaldron** [comment]
The units that I'm seeing are parallel wiring—is that how yours is?

**Comment by dtex** [comment]
HI @kisPocok I'm going to close this since we haven't heard back, but I've added the QC1602A to our [Requested Features](../wiki/Requested-Features) page so it won't get forgotten.
