### ISSUE TITLE
Ping module not working + Memory leak error

### ISSUE THREAD

**Issue by ecdeveloper** [rwaldron/johnny-five#674]
Here is a very simple code:

```
var five = require("johnny-five");
var board = new five.Board();
board.on("ready", function() {
	var ping = new five.Ping(7);
	ping.on("change", function() {
		console.log("Object is " + this.in + " inches away");
	});
});
```

For some reason nothing is outputted to the stdout. The more so, after 10-15 seconds it throws an error: 
```
(node) warning: possible EventEmitter memory leak detected. 101 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:160:15)
    at once (events.js:185:8)
    at Board.pulseIn (/Users/evghenic/dev/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:1265:8)
    at Ping.<anonymous> (/Users/evghenic/dev/node_modules/johnny-five/lib/ping.js:45:13)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

If I remove the Ping related code - the error doesn't occur. 

I followed the Ping setup guide. Uploaded the custom Firmata sketch. 

I also tested the device/circuit with an Arduino application - it works fine. 

Any ideas what may be wrong?

**Comment by rwaldron** [comment]
Can you send a picture of your circuit wiring?

**Comment by ecdeveloper** [comment]
Red is 5V on Arduino, and + on the board
Blue is GND and -

![ping circuit]
(http://oi62.tinypic.com/mu8yo6.jpg)

**Comment by cybertiti** [comment]
Hi, I had the same issue before changing to the firmata modified sketch.
With the good firmata version, everything is working.

**Comment by ecdeveloper** [comment]
@cybertiti which method for changing Firmata have you used? I actually used both (cloning the jgautier/arduino-1.git repo, and also copy/pasting the Firmata code into the Arduino IDE).

**Comment by rwaldron** [comment]
@ecdeveloper thanks for the clear image :heart:. I will assemble your circuit today and try to reproduce :)

**Comment by ecdeveloper** [comment]
@rwaldron Thanks! Looking forward to see your results :)

**Comment by rwaldron** [comment]
@ecdeveloper (unrelated to report) I notice that the board has "JY-MCU" printed on it—does this board have built-in Bluetooth? (I've never seen a board with that printed on it)

**Comment by ecdeveloper** [comment]
Wow. Just noticed that too :D I don't really know, when I ordered it I was sure it's a regular UNO without any extra built-in features.

**Comment by rwaldron** [comment]
Interesting—would you mind taking a few pictures from different angles and of the back side? If not, that's ok :)

**Comment by ecdeveloper** [comment]
@rwaldron https://www.dropbox.com/s/88t1066vahuztxt/arduino%20uno.zip?dl=0

**Comment by rwaldron** [comment]
You're the best :)

**Comment by ecdeveloper** [comment]
:smile:

**Comment by cybertiti** [comment]
@ecdeveloper I used the cloning git version, but you need to check is the firmata directory used by IDE is the right one by searching pulse_in in your sketch. The first time i did it, i uploaded the standard firmata because IDE was loading from the wrong directory.

**Comment by ecdeveloper** [comment]
@cybertiti Hm, probably you're right. I remember when I tried cloning the repo, I didn't find any "pulse_in" matches in sketch. Will double check tonight, thanks.

**Comment by rwaldron** [comment]
I just used the "copy/paste" method and cannot reproduce the issue. Here is the circuit I assembled: 

![](https://dl.dropboxusercontent.com/u/3531958/nodebots/ping-674-1.jpg)

![](https://dl.dropboxusercontent.com/u/3531958/nodebots/ping-674-3.jpg)

And here's a video demo of the circuit controlled by the program in `eg/ping.js`: 

https://www.youtube.com/watch?v=puDJJWomqzc


-----

The error you're seeing is usually the result of a wiring issue that causes the board to stop responding. A response is necessary to clear the event created by Firmata.js's `pulseIn` method ( `once("pulse-in-" + pin, ...)` ). 

Can you try connecting directly from the breadboard to the Ground and 5V as shown in my circuit?

**Comment by ecdeveloper** [comment]
@rwaldron Thanks!!! Connecting it directly solved the problem! :)

**Comment by soundanalogous** [comment]
pulse_in (in Arduino / c) has a while loop that is blocking until the pulse has finished. This will create significant delays if you are trying to read other sensors and/or control actuators at the same time. Data will still buffer through the UART as best it can but you risk loss of data by using pulse_in. This is why I have never included the routine in StandardFirmata. Once someone creates an interrupt driven pulse_in routine that works across the majority of Arduino boards, I will add an implementation... likely to ConfigurableFirmata and StandardFirmata as well if the implementation it has a low memory footprint and does not interfere with existing timers.

**Comment by ecdeveloper** [comment]
@rwaldron I will try to connect it back how it has been connected before, will let you know either it works or not. 

@soundanalogous It seems related to this issue - https://github.com/rwaldron/johnny-five/issues/675

**Comment by ecdeveloper** [comment]
@rwaldron Now it works with my previous circuit. Magically :D

**Comment by marvindebruin** [comment]
Ive tried connecting it directly and indirectly and both give the memory leak error. Maybe closing this issue was a bit premature?

 warning: possible EventEmitter memory leak detected. 101 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:160:15)
    at EventEmitter.once (events.js:185:8)
    at Board.pulseIn (/Volumes/Work HDD/Repositories/arduino/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:1265:8)
    at Ping.<anonymous> (/Volumes/Work HDD/Repositories/arduino/node_modules/johnny-five/lib/ping.js:45:13)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by ecdeveloper** [comment]
@marvindebruin In my case the problem was because of insufficient power. I was using usb power, and I had multiple things connected to my board.

**Comment by rwaldron** [comment]
>  Maybe closing this issue was a bit premature?

No, because the issue isn't software related :(

**Comment by marvindebruin** [comment]
Ill add an external power supply to the mix and get back at it tomorrow. Hope this solves it.

@rwaldron I get it now :)

**Comment by rwaldron** [comment]
Cool, let us all know how it goes :)

**Comment by marvindebruin** [comment]
So I added an external power source (5v adapter hooked up to a second arduino) and turned it on. Still no success. Ive measured the Voltage and it gives 5V to the sensor. so that works. Ive tried the sensor in this conf with the basic ping script and that works.
![img_3124](https://cloud.githubusercontent.com/assets/5748147/7178166/fc9f00f8-e42c-11e4-870d-c936baf5dfcf.JPG)
![img_3125](https://cloud.githubusercontent.com/assets/5748147/7178173/07801bd8-e42d-11e4-9d49-1f4af7b1c990.JPG)

**Comment by rwaldron** [comment]
> So I added an external power source (5v adapter hooked up to a second arduino) 

Did you share a ground line across the two Arduinos? This really should not be necessary at all. Please try with wiring exactly as shown here: https://github.com/rwaldron/johnny-five/issues/674#issuecomment-86586234

**Comment by rwaldron** [comment]
![](https://raw.githubusercontent.com/rwaldron/johnny-five/master/docs/breadboard/hc-sr04.png)

**Comment by marvindebruin** [comment]
Hey Rwaldron, this made no difference. Could it be Im using a different firmata / where can I get the proper one if not from the examples. Ill try that first just to rule it out.

**Comment by rwaldron** [comment]
> Could it be I'm using a different firmata

Yes, it very well could be. Are you using the special Ping-specific Firmata that's provided in the docs? https://github.com/rwaldron/johnny-five/wiki/Ping#setup

**Comment by bbence84** [comment]
I have a slightly different issue / question, sorry for hijacking the thread. :) What I am trying to do is to check periodically the sensor from a node red flow. The sensor returns the correct value just fine in a vanilla node.js app, but I cannot get it to work in node red (http://nodered.org/docs/hardware/arduino.html). It returns zero. How do I connect the onchange callback in a node red flow? I tried the following which did not work:
var ping = new five.Ping(7);
msg.payload = ping.cm;

johnny five and the board is supposed to be already initialized according to the example I linked. But that is just about blinking a red, there's no callback required there... Thanks!

**Comment by rwaldron** [comment]
Try this: 

```js
var ping = new five.Ping(7);

ping.on("change", function() {
  msg.payload = this.cm;
});
```

**Comment by bbence84** [comment]
Thanks, but this does not seem to work.
I think the reason is that node-red isn't supposed to work in this callback fashion, Or does it? How would you use the johnny five pushbutton object in node-red?

**Comment by rwaldron** [comment]
Sounds like a bug in node-red, because all of Johnny-Five's sensor/input component classes are emitters.
