### ISSUE TITLE
Usb keyboard simulator

### ISSUE THREAD

**Issue by henricavalcante** [rwaldron/johnny-five#677]
We can simulate a keyboard using an usb shield, firmata and johnny-five?

**Comment by rwaldron** [comment]
I'm not sure, I've never tried. Can you provide any links to existing Arduino C examples?

**Comment by henricavalcante** [comment]
I'll try tonight and show my experiments here.

**Comment by Resseguie** [comment]
@henricavalcante that's essentially what the MakeyMakey does, right? Could you look at their source for inspiration? The arduino code is under the firmware folder here:
https://github.com/sparkfun/makeymakey

**Comment by Resseguie** [comment]
Looks like it just uses the Arduino Keyboard library:
http://arduino.cc/en/Reference/MouseKeyboard

**Comment by henricavalcante** [comment]
I found this file https://github.com/practicalarduino/VirtualUsbKeyboard/blob/master/VirtualUsbKeyboard.pde that uses this project http://code.rancidbacon.com/ProjectLogArduinoUSB, can I use something like this with johnny five?

**Comment by rwaldron** [comment]
Out of scope
