### ISSUE TITLE
It is possible to run johnny-five on MeteorJS framework

### ISSUE THREAD

**Issue by toome123** [rwaldron/johnny-five#680]
Does anyone know if  can use johnny-five with MeteorJS framework.. Main problem is that node modules is asynchronous , while meteor is synchronized..I know is have some way  to run npm modules on meteor , but i dont know how , and whether there is any specificity for johnny five. 
i search across internet , but I'm still not resolved. Thanks

**Comment by vavikk** [comment]
I installed npm package for meteor (meteorhacks:npm). Works fine, so far.

**Comment by rwaldron** [comment]
@vavikk Thanks for confirming!

**Comment by toome123** [comment]
Thanks, I will try it out :)
