### ISSUE TITLE
Persistent store

### ISSUE THREAD

**Issue by Nutelac** [rwaldron/johnny-five#686]
It's possible to save data that will persist even after device shutdown? For example to Arduino EEPROM memory?

**Comment by fivdi** [comment]
I don't think so, but the file system on the computer running the Johnny-Five Node/io.js application could be used to save data.

**Comment by Nutelac** [comment]
I plan to run Johnny-Five on Arduino Yún Linux (I guess it does not matter). However, than you for response. I didn't realize that I could use simple JSON file.
