### ISSUE TITLE
Motion: Refactor motion class and consolidate sensors

### ISSUE THREAD

**Issue by frxnz** [rwaldron/johnny-five#687]
Similar to #631, IR motion sensors (and motion sensors of any other type) could be consolidated into one `Motion` class.

* [Passive Infrared](https://github.com/rwaldron/johnny-five/blob/master/lib/pir.js): Senses an object entering or leaving range
* [GP2Y0D805Z0F](https://github.com/rwaldron/johnny-five/blob/master/lib/ir.js#L22): Senses an object entering or leaving range

```js
new five.Motion({
  device: "GP2Y0D805Z0F"
});

new five.Motion({
  device: "PIR",
  pin: 7
});

// Object enters sensor range
sensor.on("motionstart", callback);

// Object leaves sensor range
sensor.on("motionend", callback);

```

**Comment by frxnz** [comment]
Just to reinforce the case for this being `Motion` instead of `IR.Motion`, there are [devices like this](https://www.sparkfun.com/products/12875) that use ultrasonic sensors instead of infrared sensors.

**Comment by rwaldron** [comment]
> Just to reinforce the case for this being Motion instead of IR.Motion

Good call :)

> device: "GP2Y0D805Z0F"

`controller: "GP2Y0D805Z0F"`

**Comment by frxnz** [comment]
> `controller: "GP2Y0D805Z0F"`

Looking for clarification on this in #688

**Comment by Resseguie** [comment]
@frxnz this can close now, right?

**Comment by frxnz** [comment]
@Resseguie Nope, `Proximity` closed #631. `Motion` is next on my list.

**Comment by Resseguie** [comment]
Got it!

**Comment by rwaldron** [comment]
This is done!
