### ISSUE TITLE
Not sure if my LCD is supported

### ISSUE THREAD

**Issue by himedlooff** [rwaldron/johnny-five#691]
Is it possible to use the following LCD screen?
![image](https://cloud.githubusercontent.com/assets/1093373/6994883/67da5488-daf7-11e4-805b-8feb665f665d.png)
http://www.dfrobot.com/wiki/index.php?title=LCD4884_Shield_Fro_Arduino_(SKU:DFR0092)

I'm not sure where to find the controller name and it also doesn't seem to specify how many rows and columns it supports (I think it may be 14x6). Maybe it's a different kind of LCD? I'm new to this so I might be missing something obvious.

**Comment by rwaldron** [comment]
That's correct, this LCD uses SPI which is not yet supported by the Firmata protocol that Johnny-Five uses for board communication.

**Comment by himedlooff** [comment]
Thanks!
