### ISSUE TITLE
OneWire temperature sensors (DS18B20) can't have multiple devices per pin

### ISSUE THREAD

**Issue by BrianGenisio** [rwaldron/johnny-five#692]
The OneWire spec allows multiple devices per pin, but the `Temperature` class doesn't handle multiple temperature sensors properly.
- [x] Bust out the DS18B20 controller into a sharable driver, like the IMU
- [x] Re-work the controller to register with the driver
- [x] Make sure the un-addressed sensor still works
- [x] Throw an error if there is more than one un-addressed sensor
- [x] Unit tests
- [ ] More real-world testing

**Comment by dtex** [comment]
Fixed by #694
