### ISSUE TITLE
breadboards.json: Update breadboards.json format to use an array of objects

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#700]
From: https://github.com/rwaldron/johnny-five/pull/699#issuecomment-90308662

> I could change the simple breadboards.json format to use an object instead of an array, then you could assign a title to each diagram and have a header that visually separates them if multiples are given. 

Slight modification: Update breadboards.json format to use an **array** of **objects**

Example: 

```
{
  "led.js" : [
    { breadboard: "led-13", title: "", description: "" }, 
    { breadboard: "led-resistor", title: "", description: "" }, 
    { breadboard: "led-13-galileo", title: "", description: "" }, 
    { breadboard: "led-13-edison-arduinoboard", title: "", description: "" }, 
    { breadboard: "led-13-mega", title: "", description: "" }
  ]
}
```

- **breadboard** is required
- **title** is optional
- **description** is optional

**Comment by Resseguie** [comment]
+1

**Comment by rwaldron** [comment]
Thanks for jumping on this :)

**Comment by Resseguie** [comment]
I was already contemplating doing exactly that. Also helps solve some of the markdown formatting I wasn't happy with.
