### ISSUE TITLE
Readme is messed up on npm

### ISSUE THREAD

**Issue by dtex** [rwaldron/johnny-five#711]
![screen shot 2015-04-09 at 12 33 28 am](https://cloud.githubusercontent.com/assets/854911/7061006/e51b2d94-de50-11e4-8bcd-b419b682bf6d.png)

**Comment by rwaldron** [comment]
Filed: https://github.com/npm/newww/issues/850

We'll close this issue when that is resolved

**Comment by rwaldron** [comment]
It's been months and this is still happening :/

**Comment by dtex** [comment]
The readme is no longer messed up. Did you do something to fix it or did the awesome people at npm fix it for us?

**Comment by rwaldron** [comment]
Looks fixed now :)
