### ISSUE TITLE
Support PancakeBot?

### ISSUE THREAD

**Issue by cowboy** [rwaldron/johnny-five#712]
Because I want to `pancakes.forEach(printPancake);`

https://www.kickstarter.com/projects/1853707494/pancakebot-the-worlds-first-pancake-printer

**Comment by rwaldron** [comment]
I :heart: that you shared this, but complete 3D printers are out of scope for Johnny-Five. It's possible to program your own 3D printer using the following Johnny-Five Component classes: 

- `Stepper`
- `Button`
- `Sensor`


;)

**Comment by tkellen** [comment]
build your own pancake factory!

**Comment by tkellen** [comment]
```js
let tyler = pancakes.reduce((me, pancake) => {
  me.push(pancake);
  return me;
}, new Tyler());
```

**Comment by Wilto** [comment]
![](http://wil.to/_/prince-disapproves.gif)
