### ISSUE TITLE
Missing image in Led documentation.

### ISSUE THREAD

**Issue by scottgonzalez** [rwaldron/johnny-five#717]
2927dbb5054a973177fd4307da7e587d718d4673 removed `docs/breadboard/led.png` which is used on https://github.com/rwaldron/johnny-five/wiki/Led. I'm not sure if this was supposed to be replaced with a different image or if that image should have remained.

**Comment by Resseguie** [comment]
Thank you. It's now led-13.png (because we're sharing it between multiple examples. Wiki updated.
