### ISSUE TITLE
Remove references to degrees in Animation()

### ISSUE THREAD

**Issue by dtex** [rwaldron/johnny-five#729]
Animation() was written with Servo() in mind but now that we are looking at supporting other types of hardware we need remove device specific language from the Animation() class.

This will require mapping the degrees param in existing servo animations to a to a device neutral label (i.e. value). This can be done in the Servo.normalize method.

**Comment by rwaldron** [comment]
https://github.com/rwaldron/johnny-five/commit/d12f8fba241c6d1e074cffa7e030762f9e12f400
