### ISSUE TITLE
Add Led.RGB.intensity()

### ISSUE THREAD

**Issue by Resseguie** [rwaldron/johnny-five#737]
Similar to current `Led.brightness()` but has range 0-100 (percent).

Should consider deprecating `.brightness()` completely and add `.intensity(0-100)` to Led as well.

Reasoning: "brightness" can be misinterpreted. "intensity" is standard term in lighting industry.

**Comment by rwaldron** [comment]
Thanks for filing this. I will finish up my patch and push a branch for review tomorrow

**Comment by Resseguie** [comment]
Related to #370

**Comment by scottgonzalez** [comment]
> Thanks for filing this. I will finish up my patch and push a branch for review tomorrow

@rwaldron Are you still going to do this?

What's the plan for changing brightness? Does it take the current color into account or is it always an equal mix of red, green, and blue?

**Comment by rwaldron** [comment]
> @rwaldron Are you still going to do this?

If you want to do this, go for it.

> What's the plan for changing brightness? Does it take the current color into account or is it always an equal mix of red, green, and blue?

If I understand you correctly, it takes the color into account. So if it's currently red, `intensity(0-100)` scales red from off to full red, but always some shade of red.
