### ISSUE TITLE
custom logging

### ISSUE THREAD

**Issue by boneskull** [rwaldron/johnny-five#745]
afaik, if you don't want J5 dumping its logs to console, your recourse is to monkeypatch:

```js
    var boardProto = j5.Board.prototype;

    // redirect logs to server logs
    _.each(_.keys(boardProto.log.types), function (type) {
      boardProto[type] = function () {
        var args = _.toArray(arguments).join(' ');
        // this is a Hapi server
        server.log.apply(server, [type].concat(args));
      };
    });
```

Any ideas on how to make this easier?

**Comment by rwaldron** [comment]
Doesn't `debug: false, repl: false` shut it up?

**Comment by rwaldron** [comment]
(if not, then we got bugz)

**Comment by boneskull** [comment]
Don't worry; that works. But I don't want do suppress the logging--I want to redirect it.

**Comment by rwaldron** [comment]
Ah, I see. I completely misunderstood. That was before I ate lunch. 

Let's figure out a way to allow this

**Comment by boneskull** [comment]
probably some cmd-line flag that allows you to specify an adapter module

**Comment by scottgonzalez** [comment]
Perhaps the simplest solution would be to just emit log events from `Board.prototype.log`?

I did a search for uses of `console` and it looks like there are lots of warning/deprecation notices that go directly through `console.log()`/`console.warn()`. If you want to handle these as well, you could create a log module and have everything use that.

**Comment by rwaldron** [comment]
Yeah, those need to be cleaned up :/

**Comment by rwaldron** [comment]
https://github.com/rwaldron/johnny-five/commit/5381dc2b39166488a87e26b87875133a1c4b4cbe
