### ISSUE TITLE
Incorrect example diagram for LED - PCA9685

### ISSUE THREAD

**Issue by scottgonzalez** [rwaldron/johnny-five#772]
The diagram on http://johnny-five.io/examples/led-PCA9685/ shows the LED connected to PWM and V+ instead of PWM and GND.

**Comment by rwaldron** [comment]
The fzz is in the repo, can you fix it?

**Comment by scottgonzalez** [comment]
Bah. I actually did that and pushed a branch, but then got distracted and never sent the PR :-/

#773
