### ISSUE TITLE
Update grunt example task to modify programs.json

### ISSUE THREAD

**Issue by Resseguie** [rwaldron/johnny-five#784]
Make `grunt example` interactive to not only build boilerplate example, but also interactively add an entry to `programs.json` (optional).

Needs to also consider case where example already exists and user wants to use `gunt example` to just add the `programs.json` entry.

**Comment by rwaldron** [comment]
Any updates?

**Comment by rwaldron** [comment]
@deathbearbrown this might be interesting to tackle
