### ISSUE TITLE
Do Arduino Yun need LininoIO and Ideino to upload Johnny-five files?

### ISSUE THREAD

**Issue by aabm00** [rwaldron/johnny-five#792]
Hello
I'm new programming with Arduino. I got an Arduino Yun, and I want to use it to read from sensors and send the data via wifi to a node server using johnny-five. I started to configure the board but I have some doubts that I would appreciate some help.
This is the process that I have followed to install johnny-five following the instruction in [nino-io] (https://github.com/rwaldron/nino-io):
* Expand the Yun following the instructions in this link [Expand the Yun disk space] (http://www.arduino.cc/en/Tutorial/ExpandingYunDiskSpace)
* Upgraded the linux from OpenWRT-Yun to LininoOS following this link [Upgrade Arduino Yun from Openwrt-Yun to LininoOS] (http://wiki.linino.org/doku.php?id=wiki:upgradeimage#upgrade_your_arduino_yun_with_sysupgrade).
* Install **node.js** following this link [install Node.js on the board] (http://wiki.linino.org/doku.php?id=wiki:nodejscript)
* Install **nino-io** and **Johnny-five** using SSH to connect the Yun and changing to the /opt directory and then **npm install nino-io johnny-five**.
At this point I wanted to execute the **blink** code directly on board:
````
var five = require("johnny-five");
var Nino = require("nino-io");
var board = new five.Board({
  io: new Nino({
    layout: "Arduino Yun"
  })
});

board.on("ready", function() {
  console.log("Ready");

  var led = new five.Led(13);

  led.blink(500);
});
````
And the doubts are:
1. How I upload this code to the board? The **Arduino IDE** doesn’t work.
2. Do I need to install [Ideino IDE & Linino-Lib] (http://wiki.linino.org/doku.php?id=wiki:nodejs_lininoio) to upload to code? 
3. If I need **Ideino IDE**, it needs [lininoIO] (http://wiki.linino.org/doku.php?id=wiki:upgradetolininoio) to work, then, Do I need to install [lininoIO] (http://wiki.linino.org/doku.php?id=wiki:upgradetolininoio)?
4. The installation of [lininoIO] (http://wiki.linino.org/doku.php?id=wiki:upgradetolininoio) isn’t trivial and there are the risk to break the board and that [will VOID the WARRANTY of the Yún] (http://www.arduino.cc/en/Tutorial/YunUBootReflash). Is it necessary to install [lininoIO] (http://wiki.linino.org/doku.php?id=wiki:upgradetolininoio) and update the U-boot,   firmware, kernel, rootfs and MCU firmware to LininoIO version?
5. Is there an easy way to do it?

Thanks

**Comment by rwaldron** [comment]
Let's keep this over [here](https://github.com/rwaldron/nino-io/issues/4) :)
