### ISSUE TITLE
Microphone

### ISSUE THREAD

**Issue by rudemex** [rwaldron/johnny-five#802]
There are some example of how to implement this shield ?

**Comment by fivdi** [comment]
A microphone with an analog output? If so, see [here](https://github.com/rwaldron/johnny-five/issues/264).

**Comment by rwaldron** [comment]
@rudemex secondarily to @fivdi's advice: what shield?

**Comment by rudemex** [comment]
i have this shield http://articulo.mercadolibre.com.ar/MLA-552413873-modulo-sensor-de-sonido-microfono-regulable-arduino-_JM

**Comment by rwaldron** [comment]
Ok, great, then exactly what @fivdi suggested should work just fine :)

**Comment by rudemex** [comment]
great, There is a library of voice recognition ? I used the program bitvoicer but with Arduino code.

thanks

**Comment by fivdi** [comment]
The [YL-56 microphone](http://www.wayengineer.com/sound-sensor-module-p-1051.html#.VWEIDqHyM_s) has a digital output.

**Comment by rwaldron** [comment]
No, there is no voice recognition—you'd have to pass the value readings from the sensor to whatever processing library is available. You might try porting μSpeech https://github.com/arjo129/uSpeech

**Comment by rudemex** [comment]
yes, i need recognition words, used this librery. 

Example
http://www.instructables.com/id/Speech-Recognition-with-BitVoicer-and-Arduino/

**Comment by rwaldron** [comment]
https://github.com/rwaldron/johnny-five/commit/5579d12c61842671bac9709a7b02b61d31dc9ba2

**Comment by rudemex** [comment]
thanks @rwaldron, @fivdi

**Comment by rwaldron** [comment]
@rudemex no problem :)

**Comment by rwaldron** [comment]
Also: http://johnny-five.io/examples/microphone/

**Comment by rudemex** [comment]
as we say in Argentina...

Gracias Idolos! jajajaja

**Comment by fivdi** [comment]
If the microphone being uses is the [YL-56](http://www.wayengineer.com/sound-sensor-module-p-1051.html#.VWEUQaHyM_t), which appears to be the case, a [digital-sensor](http://johnny-five.io/api/sensor/#digital-sensor) can also be used.

**Comment by rwaldron** [comment]
@fivdi good eye on that one—I wonder if there is a fritzing for that component? I'm mobile so searching isn't in the cards for me

**Comment by fivdi** [comment]
I can't find a fritzing for that specific component.

**Comment by rudemex** [comment]
@fivdi This component has the same connection, working very good.

L -------------------------------> R
OUT(A0) - GND - VCC(3.3v)

**Comment by fivdi** [comment]
So you have it working :) That's good news.
And the output from the microphone is analog, not digital?

**Comment by rudemex** [comment]
i dont now jajajaja its working :P

https://instagram.com/p/3E95s1u41z/?taken-by=rudemex

**Comment by rwaldron** [comment]
Wow, that's awesome! Will share the code for this?

**Comment by rudemex** [comment]
yes, of course. I have to migrate code to js. but the orginal code is this. http://www.instructables.com/id/Speech-Recognition-with-BitVoicer-and-Arduino/

a software (http://www.bitsophia.com/BitVoicer.aspx only S.O. WIN) is needed to set the words to recognize and execute the functions.

I hope to migrate , you can do pretty amazing things

**Comment by scottgonzalez** [comment]
Since the examples are live on the site, is there anything left to do before closing this issue?

**Comment by rwaldron** [comment]
I don't think so, seems closable
