### ISSUE TITLE
LED RGB fade to color

### ISSUE THREAD

**Issue by rudemex** [rwaldron/johnny-five#806]
I have a led strip 5050, as to fade from color to color ?

if I set each LED I can make the transition , but it is not led strip.

Thanks

**Comment by rwaldron** [comment]
cc @ajfisher & @frxnz who know lot's of things about LED strips

**Comment by ajfisher** [comment]
@rudemex Do you have a circuit diagram and some code to show what is happening at the moment?

**Comment by rwaldron** [comment]
I'm going to close this, but we can reopen whenever either of you would like to continue working on it :)
