### ISSUE TITLE
Add NodeBoats motor driver to 3-pin example

### ISSUE THREAD

**Issue by Resseguie** [rwaldron/johnny-five#808]
It would be nice to have an additional breadboard for the specific Sparkfun motor driver that is used by nodeboats so we can point attendees to a single page for help getting started.

**Comment by rwaldron** [comment]
@resseguie can you write this up?

**Comment by Resseguie** [comment]
Sorry, I had forgotten about this. I'm pretty sure I still have one of those drivers laying around. I'll look into it.

**Comment by dtex** [comment]
@resseguie This was the H-bridge IC on a breadboard right? We have it here: 

http://johnny-five.io/examples/motor-hbridge/
