### ISSUE TITLE
Feature idea: RGB LED color correction

### ISSUE THREAD

**Issue by mize** [rwaldron/johnny-five#811]
Caveat: I'm extremely new to hardware.

Tinkering with an RGB LED, I noticed I got mixed colors that were different from what I expected based on hex values passed via the color method. So I read some background info on color variations:
- [Understand RGB LED mixing ratios to realize optimal color in signs and displays](http://www.ledsmagazine.com/articles/print/volume-10/issue-6/features/understand-rgb-led-mixing-ratios-to-realize-optimal-color-in-signs-and-displays-magazine.html)
- [FastLED Color Correction](https://github.com/FastLED/FastLED/wiki/FastLED-Color-Correction)

Looks like the FastLED lib has some constant [white point values](https://github.com/FastLED/FastLED/blob/master/color.h) that they allow the user to designate via setCorrection or setTemperature methods, and the resulting value [transforms any further colors passed in](https://github.com/FastLED/FastLED/blob/master/controller.h#L123-L151).

Could be cool to add this feature to J5, in Led.RGB constructor options and as an instance method for flexibility during runtime. I think it would be handy to use a standard set of values, as well as letting J5 user designate a custom white point as a hex string.

I'm willing to give it a go. Would other folks find this useful? I'll also look around to see whether this is a solved problem via some other JS lib.

**Comment by rwaldron** [comment]
Any updates?

**Comment by dtex** [comment]
Hi @mize 

I'm going to close this since we haven't heard back, but it still sounds like a good addition. To make sure it doesn't get forgotten I've added it to the Johnny-Five [Requested Features](../wiki/Requested-Features) page.
