### ISSUE TITLE
PCF8574 does not work as input

### ISSUE THREAD

**Issue by rodrigoadachi** [rwaldron/johnny-five#831]
``` js
board.on("ready", function() {
  var virtual = new five.Board.Virtual(
    new five.Expander({ controller: "PCF8574",  address: 0x20 })
  );
  var button = new five.Button({
    board: virtual,
    pin: 7, 
  });
  button.on("press", function() {
    console.log('button on');
  });
});
```

Did tests with outputs and everything works ok, however when declare inputs with outputs and inputs do not work only.

**Comment by rwaldron** [comment]
Thanks for the report, I will take a look at this today

**Comment by rwaldron** [comment]
Can you post a picture of your exact wiring? Thanks!

**Comment by rwaldron** [comment]
@rodrigoadachi can you try this with the johnny-five @ master?

**Comment by rodrigoadachi** [comment]
![pcf8574_bb](https://cloud.githubusercontent.com/assets/6013579/8237640/38722062-15c7-11e5-9eb1-c23ef19ced98.png)

**Comment by rodrigoadachi** [comment]
Como assim johnny-five @ master?

**Comment by rodrigoadachi** [comment]
var   , five = require("johnny-five");

  var board = new five.Board({ port: "/dev/ttyUSB0" });

  board.on("ready", function() {
    var virtual = new five.Board.Virtual(
      new five.Expander({
        controller: "PCF8575",
        address: 0x20
      })
    );

    var led = new five.Led({
      board: virtual,
      pin: 0, 
    });

    var button = new five.Button({
      board: virtual,
      pin: 7, 
    });

  button.on("press", function() {
    console.log('pulsador1 on');
    led.on();
  });

  button.on("release", function() {
    console.log('pulsador1 off');
    led.off();
  });

});

**Comment by rwaldron** [comment]
I just pushed the latest changes to npm: johnny-five@0.8.80

I confirmed the bug you experienced, but will also try your code above

**Comment by rwaldron** [comment]
The code you have above uses `PCF8575`, but this was filed about `PCF8574` and that's the chip in the diagram—these are not interchangeable. Which one should I test with?

**Comment by rodrigoadachi** [comment]
Ohh, sorry, 'cause I tried using the IC PCF8575 PCF8574, but the fact is the PCF8574.

**Comment by rwaldron** [comment]
Ok, thanks. I'm still seeing the issue with your code example (updated to use `PCF8574`) so I'll continue working on this.

**Comment by rodrigoadachi** [comment]
Okay, I thank you for your attention.

**Comment by rwaldron** [comment]
Please try your code with johnny-five@0.8.81

**Comment by rodrigoadachi** [comment]
It did not work, I tested with this code, and only expanderP0 goes to 1, where it should be 0, but if I comment on the entries, exits work.

var board = new five.Board({ port: "/dev/ttyUSB0" });
  
  board.on("ready", function() {

    var virtual = new five.Board.Virtual(
      new five.Expander({
        controller: "PCF8574",
        address: 0x20
      })
    );

    var expanderP0     	= new five.Led({ board: virtual, pin: 0 });
    var expanderP1     	= new five.Led({ board: virtual, pin: 1 });
    var expanderP2      = new five.Led({ board: virtual, pin: 2 });
    var expanderP3      = new five.Led({ board: virtual, pin: 3 });

    var expanderP4   	= new five.Button({ board: virtual, pin: 4 });
    var expanderP5  	= new five.Button({ board: virtual, pin: 5 });
    var expanderP6   	= new five.Button({ board: virtual, pin: 6 });
    var expanderP7   	= new five.Button({ board: virtual, pin: 7 });

    expanderP0.off();
    expanderP1.off();
    expanderP2.on();
    expanderP3.on();

    expanderP4.on("press", function() {
      console.log('expanderP4:');
  	});
    expanderP5.on("press", function() {
      console.log('expanderP5:');
  	});
    expanderP6.on("press", function() {
      console.log('expanderP6:');
  	});
    expanderP7.on("press", function() {
      console.log('expanderP7:');
  	});

});

**Comment by rwaldron** [comment]
When I run your code, the result is: 

- expanderP0 is off
- expanderP1 is off
- expanderP2 is on
- expanderP3 is on

Can you take a photo of your hardware?

**Comment by rodrigoadachi** [comment]
I'll try

**Comment by rwaldron** [comment]
Thanks, it will be very helpful

**Comment by rodrigoadachi** [comment]
I can not access it, installed above the ceiling, it controls my enlightenment, is running with a stand-alone application. But I try to take a picture tomorrow.

**Comment by rwaldron** [comment]
I'm confused—what is installed in the ceiling?

**Comment by rodrigoadachi** [comment]
Sorry for the translation, My card is installed above the ceiling, it is connected in a cubieboard remotely access.

**Comment by rwaldron** [comment]
No worries, I'm patient, I just want to make sure that I understand you :)

**Comment by rodrigoadachi** [comment]
OK thank you.

**Comment by rwaldron** [comment]
Any update?

**Comment by rodrigoadachi** [comment]
This is the famous board.

I did some testing today and nothing worked, not even the out.
Only when commenting on the statements of the entries that the outputs return to work

![akcg_ttkvkc6tqbywlqehi4v0ivz4p-lftaw5osa7zl5](https://cloud.githubusercontent.com/assets/6013579/8279586/290ee988-18ac-11e5-9870-660579387f3a.jpg)

board.on("ready", function() {
    var virtual = new five.Board.Virtual(
      new five.Expander({
        controller: "PCF8574",
        address: 0x20
      })
    );
   // out
    var expanderP0     	= new five.Led({ board: virtual, pin: 0 });
    var expanderP1     	= new five.Led({ board: virtual, pin: 1 });
    var expanderP2      = new five.Led({ board: virtual, pin: 2 });
    var expanderP3      = new five.Led({ board: virtual, pin: 3 });
    var led 			= new five.Led.RGB({ pins: { red: 6, green: 5, blue: 9 } });
    // in
    var expanderP4   	= new five.Button({ board: virtual, isPullup: true, pin: 4 });
    var expanderP5  	= new five.Button({ board: virtual, isPullup: true, pin: 5 });
    var expanderP6   	= new five.Button({ board: virtual, isPullup: true, pin: 6 });
    var expanderP7   	= new five.Button({ board: virtual, isPullup: true, pin: 7 });
   // set out
   expanderP0.off();
   expanderP1.off();
   expanderP2.off();
   expanderP3.off();
   led.off();
   // get in   
   expanderP4.on("press", function() {
     console.log('expanderP4:');
   });
   expanderP5.on("press", function() {
      		console.log('expanderP5:');
    	});
	expanderP6.on("press", function() {
      		console.log('expanderP6:');
    	});
	expanderP7.on("press", function() {
      		console.log('expanderP7:');
    	});
});

**Comment by rodrigoadachi** [comment]
This is the motherboard kkk

![aj-iafxqwp_i62tcxirp4wbp-thnhajt67eocuffrqqm](https://cloud.githubusercontent.com/assets/6013579/8279713/22eda458-18ad-11e5-9889-fdce8e3da4fb.jpg)

**Comment by rwaldron** [comment]
> Only when commenting on the statements of the entries that the outputs return to work

Can you paste the exact code you're referring to?

In the first photo, there looks like 6 ground and signal pairs (3 each on either side), is that correct? Where are the buttons connected?

> ```js
var expanderP4 = new five.Button({ board: virtual, isPullup: true, pin: 4 });
var expanderP5 = new five.Button({ board: virtual, isPullup: true, pin: 5 });
var expanderP6 = new five.Button({ board: virtual, isPullup: true, pin: 6 });
var expanderP7 = new five.Button({ board: virtual, isPullup: true, pin: 7 });
```

Why are you using the `isPullup` flag? 

> This is the motherboard

Unfortunately, this is too blurry for me to learn anything from it :(

- Is that an arduino nano? 
- What is the device that's connecting the processor to the host machine?
- Can you list the hardware there?

**Comment by rodrigoadachi** [comment]
Only works when the OUTPUTS comment on the statements of INPUTS.
this:

//var expanderP4   	= new five.Button({ board: expanderX21, pin: 4 });
//var expanderP5  	= new five.Button({ board: expanderX21, pin: 5 });
//var expanderP6   	= new five.Button({ board: expanderX21, pin: 6 });
//var expanderP7   	= new five.Button({ board: expanderX21, pin: 7 });

Use optos 4N35 at the entrances, because of this the inputs are pull-up

is board below has a Pro Micro Arduino connected to the computer via RS232
![mainboard](https://cloud.githubusercontent.com/assets/6013579/8306588/78a19dfe-198f-11e5-99f0-a7a16893108d.jpg)

And this, possesses one PCF8574, 4 relays and 4 solids in optos 4N35 pull-up
![i2c](https://cloud.githubusercontent.com/assets/6013579/8306614/b4e3a302-198f-11e5-9732-824fe31568cd.jpg)

The assembly is ugly, but it works only using Arduino kkk

Ah, sorry for the delay in responding

**Comment by rwaldron** [comment]
This is soooo helpful—thank you! I will work on this more as soon as I can :)

**Comment by rwaldron** [comment]
> but it works only using Arduino kkk

This is valuable. I will make sure to use exactly the same board you have above :)

**Comment by rodrigoadachi** [comment]
ok, thank you, kkkkk

**Comment by rodrigoadachi** [comment]
Hello, any news?

**Comment by rwaldron** [comment]
I have been unable to reproduce the issues that you've described above. Let's ping @dtex @Resseguie @BrianGenisio @frxnz @ajfisher perhaps one of them can attempt as well

**Comment by rodrigoadachi** [comment]
I added another PCF8574, address 0x21, one 0x20 pcf to exits and other pcf 0x21 for entries, and so does

**Comment by ryrych** [comment]
@rwaldron This issue has been closed, but I'm wondering if it is possible to connect buttons via an expander. Is there any diagram that shows how to make buttons work as input when connected via PCF8574?
Here's the JS (excerpt)

```js
 board.on('ready', () => {
      connected = true;
      virtual = new five.Board.Virtual(new five.Expander({ controller: 'PCF8574', address: 0x20 }));

      button = new five.Button({
        board: virtual,
        pin: 0,
        holdtime: 1000,
        isPulldown: true,
      });

      button.on('up', function () {
        console.log('hello');
      });
      resolve({ board: board });
    });
```

I'm using ESP8266 WIFI. Temporarily I disconnected the button on the right.

![signal-2023-09-04-173208](https://github.com/rwaldron/johnny-five/assets/278637/5582a1fd-3098-4052-aa1b-e1de58730d6f)

**Comment by ryrych** [comment]
@rwaldron what I'm going to achieve is to connect two buttons in Nodemcu ESP8266. If this is possible somehow differently, please let me know. I'm not attached to expander solution.
