### ISSUE TITLE
Add website link in repo description

### ISSUE THREAD

**Issue by Resseguie** [rwaldron/johnny-five#840]
Many projects have a link to an official website in the short description at the top of the repo. I suggest having it read:

JavaScript Robotics and IoT programming framework, based on the Arduino Firmata Protocol. Developed at Bocoup. http://johnny-five.io/ 

I think only the repo owner (i.e. @rwaldron) gets the edit link at the top to make that change.

**Comment by rwaldron** [comment]
I guess I did this?
