### ISSUE TITLE
Use new Travis-CI container based infrastructure

### ISSUE THREAD

**Issue by dtex** [rwaldron/johnny-five#863]
See this blog post:

http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

I think this should be straightforward for us. Any reason not to?

**Comment by rwaldron** [comment]
Maybe? tessel hit issues with installing USB drivers

**Comment by dtex** [comment]
I'll try it out

**Comment by rwaldron** [comment]
Sounds good

**Comment by dtex** [comment]
Close by #864
