### ISSUE TITLE
Request - Button hold, continually trigger action

### ISSUE THREAD

**Issue by kevincannon** [rwaldron/johnny-five#873]
I've a small feature request. In the Button object, there's a hold trigger. However, it only triggers after 500ms, and never again. Often press & hold is something where you need to repeatedly do the action like a keyboard. It woud be nice to have a repeat option built in. 

http://johnny-five.io/api/button/

Something like this:
```
rightButton   = new five.Button({
pin:3,
isPullup: true,
holdtime: 200,
holdrepeat: true
});

button.on("hold", function() {
    console.log("hold");
});
```
Then you would get this as an output
```
hold
hold
hold
```

It would be neat if it was built in!

**Comment by rwaldron** [comment]
I like it and I think this might even be preferable as the default behavior? I won't be able to release b/c we're "frozen" until after Nodebots Day (this Saturday)—is that ok?

**Comment by Resseguie** [comment]
I like it too.

**Comment by kevincannon** [comment]
No rush at all, i've made a workaround for my needs for now, but built in would be even better :)

**Comment by rwaldron** [comment]
@kevincannon thanks for patience!

**Comment by dtex** [comment]
Should this be a different event? Currently the hold event represents a state change. Also, we may want different behavior on that initial state change then we would want on the repeated firings of the event.

**Comment by dtex** [comment]
Never mind, I didn't really think that through. Hold is not a state change.

**Comment by rwaldron** [comment]
>  Also, we may want different behavior on that initial state change then we would want on the repeated firings of the event.

`button.once("hold", ...)`?

**Comment by Resseguie** [comment]
I like that @rwaldron

**Comment by kevincannon** [comment]
Wow guys - just checked that out, that's amazing. Thanks so much! :)

**Comment by rwaldron** [comment]
Thank _you_ for filing.
