### ISSUE TITLE
When the lower value of the range is greater than the upper scale does not work

### ISSUE THREAD

**Issue by frankely** [rwaldron/johnny-five#878]
When I try to use the scale with the lower value greater than the upper scale does not work, this.value is returning 0

```
rotary.scale(180,0).on("change",function(){
    console.log(this.value);
});
```

**Comment by Resseguie** [comment]
What are you expecting it to do in that case?

**Comment by frankelydiaz** [comment]
Rick Waldron just told me that it should work in the opposite way if I invert the range.

**Comment by rwaldron** [comment]
Confirm, I figured it would just invert the scaling operation

**Comment by HaraldNordgren** [comment]
@frankely @rwaldron Created a PR: https://github.com/rwaldron/johnny-five/pull/1507

**Comment by dtex** [comment]
Closed. 

Thank you @HaraldNordgren
