### ISSUE TITLE
I2C Capability

### ISSUE THREAD

**Issue by cooltrooper** [rwaldron/johnny-five#88]
Add the ability for I2C communication. Probably would only allow low level communication as devices vary significantly in the commands and addresses required for use.

**Comment by LenaicTerrier** [comment]
On [https://github.com/jgautier/firmata#i2c](the firmata page) it's indicated that `sendI2CWriteRequest` and `sendI2CReadRequest` functions are both deprecated. Is it also the case for **johnny-five** ?

**Comment by rwaldron** [comment]
Yes, all classes will be migrating to the new API in time
