### ISSUE TITLE
Is there any way to have serial communication on Raspbian using Docker? 

### ISSUE THREAD

**Issue by juliocesar-io** [rwaldron/johnny-five#882]
It is possible to have serial communication with an Arduino on Raspberry pi 2 B+ (raspbian:wheezy) using  Docker ?

Docker can access to attached devices using a volume

```
docker run --privileged -v /dev/bus/usb:/dev/bus/usb <image>
```

Or for an specific device

```
docker run --device=/dev/ttyACM0 <image>
```

And it works 

```
Bus 001 Device 005: ID 2341:0042 Arduino SA Mega 2560 R3 (CDC ACM)
```

But when I run my app It just remains looking for a connected device.

> Board Looking for connected device 

Any thoughts ?

node -v
v0.10.36

johnny-five
0.8.85

**Comment by Resseguie** [comment]
I'll note that I'm potentially interested in the general Docker question as well, not just Raspbian.

**Comment by rwaldron** [comment]
@nebrius @beriberikix @jfrazelle

**Comment by rwaldron** [comment]
Did you try writing it out, like: 


```js
var five = require("johnny-five");
var board = new five.Board({ port: "/dev/ttyACM0" });

board.on("ready", function() {
   // ...
});
```

**Comment by beriberikix** [comment]
It should definitely be possible. Do you know if the image has serial drivers installed? Seems like something one would strip out for the regular webapp use case.

**Comment by juliocesar-io** [comment]
I set the port explicitly.

```js
var board = new five.Board({ port: "/dev/ttyACM0" });
``` 

And It just works like a charm.

Thanks for your help!!
