### ISSUE TITLE
non-exist component (PCB layout)

### ISSUE THREAD

**Issue by lookaz** [rwaldron/johnny-five#888]
now i want to design a PCB layout with proteus and there's a component which not exist in proteus how can i create it with its specific dimensions because dimensions'll be important for the PCB layout design
thanks

**Comment by dtex** [comment]
@lookaz I'm sorry nobody responded to this right away but frankly I don't think anyone here knows much about Proteus. I'm sure you've already solved this but just in case here's a link to the Labcenter forums:

http://support.labcenter.co.uk/forums/

I imagine there are lots of people there who know about Proteus. 

If you think there is something we can help with feel free to re-open this issue.
