### ISSUE TITLE
Led Matrix detect if led is on or off

### ISSUE THREAD

**Issue by rudemex** [rwaldron/johnny-five#904]
hi

Happy programmer day!!!!

how to detect if a LED on ot off?

**Comment by rwaldron** [comment]
There currently isn't a way to check if an LED in a Matrix is on or off. Matrix components are always initialized to "off", so any changes to that state are done in user code—which means that user code can always know which LEDs it's turned on or off.

**Comment by rudemex** [comment]
ok, thanks!

**Comment by rwaldron** [comment]
@rudemex I'm going to close this—if you want to reopen in the future, please feel free to do so :)
