### ISSUE TITLE
Install johnny-five on Windows 8

### ISSUE THREAD

**Issue by Alexaas** [rwaldron/johnny-five#921]
Hi, 
I tried to install johnny-five on a Windows 8.1 machine. I have installed:

Visual Studio Express 2015, 
Python27
nodejs 4.1.2

The installation aborts because of build errors. See below.

Any idea what could be wrong?

Thanks,
Alex

> serialport@1.7.4 install C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport
> node-pre-gyp install --fallback-to-build

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  serialport.cpp
  serialport_win.cpp
  enumser.cpp
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(263): error C2995: "v8::Local<T> _NanEnsureLocal(v8::Local<T>)": Funktionsvorlage wurde bereits definiert. (Quelldatei wird kompiliert ..\src\serialport.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
  C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(256): note: Siehe Deklaration von "_NanEnsureLocal" (Quelldatei wird kompiliert ..\src\serialport.cpp)
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(661): error C3083: "smalloc": Das Symbol links neben "::" muss ein Typ sein. (Quelldatei wird kompiliert ..\src\serialport.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(661): error C2039: "FreeCallback": Ist kein Element von "node" (Quelldatei wird kompiliert ..\src\serialport.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
  C:\Users\d037602\.node-gyp\4.1.2\include\node\node_object_wrap.h(8): note: Siehe Deklaration von "node" (Quelldatei wird kompiliert ..\src\serialport.cpp)
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(661): error C2061: Syntaxfehler: Bezeichner "FreeCallback" (Quelldatei wird kompiliert ..\src\serialport.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(665): error C2065: "callback": nichtdeklarierter Bezeichner (Quelldatei wird kompiliert ..\src\serialport.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(665): error C2065: "hint": nichtdeklarierter Bezeichner (Quelldatei wird kompiliert ..\src\serialport.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(672): error C2665: "node::Buffer::New": Durch keine der 4 šberladungen konnten alle Argumenttypen konvertiert werden. (Quelldatei wird kompiliert ..\src\serialport.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
  C:\Users\d037602\.node-gyp\4.1.2\include\node\node_buffer.h(43): note: kann "v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)" sein (Quelldatei wird kompiliert ..\src\serialport.cpp)
  C:\Users\d037602\.node-gyp\4.1.2\include\node\node_buffer.h(31): note: oder "v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)" (Quelldatei wird kompiliert ..\src\serialport.cpp)
  C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(672): note: bei Anpassung der Argumentliste "(v8::Isolate *, const char *, uint32_t)" (Quelldatei wird kompiliert ..\src\serialport.cpp)
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(676): error C2440: "return": "v8::MaybeLocal<v8::Object>" kann nicht in "v8::Local<v8::Object>" konvertiert werden (Quelldatei wird kompiliert ..\src\serialport.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
  C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(676): note: Quelltyp konnte von keinem Konstruktor angenommen werden, oder die šberladungsaufl”sung des Konstruktors ist mehrdeutig (Quelldatei wird kompiliert ..\src\serialport.cpp)
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(683): error C2039: "Use": Ist kein Element von "node::Buffer" (Quelldatei wird kompiliert ..\src\serialport.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
  C:\Users\d037602\.node-gyp\4.1.2\include\node\node_buffer.h(8): note: Siehe Deklaration von "node::Buffer" (Quelldatei wird kompiliert ..\src\serialport.cpp)
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(683): error C3861: "Use": Bezeichner wurde nicht gefunden. (Quelldatei wird kompiliert ..\src\serialport.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\win\enumser.cpp(443): warning C4996: 'GetVersionExA': wurde als veraltet deklariert [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\sysinfoapi.h(433): note: Siehe Deklaration von "GetVersionExA"
c:\program files\nodejs\node_modules\johnny-five\node_modules\serialport\src\win\stdstring.h(2123): warning C4311: "reinterpret_cast": Zeigerverkrzung von "const void *" zu "unsigned long" (Quelldatei wird kompiliert ..\src\win\enumser.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
  c:\program files\nodejs\node_modules\johnny-five\node_modules\serialport\src\win\stdstring.h(2117): note: Bei der Kompilierung der Klassen-template der "bool CStdStr<wchar_t>::TryLoad(const void *)"-Memberfunktion (Quelldatei wird kompiliert ..\src\win\enumser.cpp)
  c:\program files\nodejs\node_modules\johnny-five\node_modules\serialport\src\win\stdstring.h(2171): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-template "bool CStdStr<wchar_t>::TryLoad(const void *)". (Quelldatei wird kompiliert ..\src\win\enumser.cpp)
  c:\program files\nodejs\node_modules\johnny-five\node_modules\serialport\src\win\stdstring.h(3982): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Klassen-template "CStdStr<wchar_t>". (Quelldatei wird kompiliert ..\src\win\enumser.cpp)
c:\program files\nodejs\node_modules\johnny-five\node_modules\serialport\src\win\stdstring.h(2123): warning C4302: "reinterpret_cast": Verkrzung von "const void *" in "unsigned long" (Quelldatei wird kompiliert ..\src\win\enumser.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
c:\program files\nodejs\node_modules\johnny-five\node_modules\serialport\src\win\stdstring.h(2126): warning C4311: "reinterpret_cast": Zeigerverkrzung von "const void *" zu "unsigned long" (Quelldatei wird kompiliert ..\src\win\enumser.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
c:\program files\nodejs\node_modules\johnny-five\node_modules\serialport\src\win\stdstring.h(2126): warning C4302: "reinterpret_cast": Verkrzung von "const void *" in "unsigned long" (Quelldatei wird kompiliert ..\src\win\enumser.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(263): error C2995: "v8::Local<T> _NanEnsureLocal(v8::Local<T>)": Funktionsvorlage wurde bereits definiert. (Quelldatei wird kompiliert ..\src\serialport_win.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
  C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(256): note: Siehe Deklaration von "_NanEnsureLocal" (Quelldatei wird kompiliert ..\src\serialport_win.cpp)
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(661): error C3083: "smalloc": Das Symbol links neben "::" muss ein Typ sein. (Quelldatei wird kompiliert ..\src\serialport_win.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(661): error C2039: "FreeCallback": Ist kein Element von "node" (Quelldatei wird kompiliert ..\src\serialport_win.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
  C:\Users\d037602\.node-gyp\4.1.2\include\node\node_object_wrap.h(8): note: Siehe Deklaration von "node" (Quelldatei wird kompiliert ..\src\serialport_win.cpp)
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(661): error C2061: Syntaxfehler: Bezeichner "FreeCallback" (Quelldatei wird kompiliert ..\src\serialport_win.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(665): error C2065: "callback": nichtdeklarierter Bezeichner (Quelldatei wird kompiliert ..\src\serialport_win.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(665): error C2065: "hint": nichtdeklarierter Bezeichner (Quelldatei wird kompiliert ..\src\serialport_win.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(672): error C2665: "node::Buffer::New": Durch keine der 4 šberladungen konnten alle Argumenttypen konvertiert werden. (Quelldatei wird kompiliert ..\src\serialport_win.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
  C:\Users\d037602\.node-gyp\4.1.2\include\node\node_buffer.h(43): note: kann "v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)" sein (Quelldatei wird kompiliert ..\src\serialport_win.cpp)
  C:\Users\d037602\.node-gyp\4.1.2\include\node\node_buffer.h(31): note: oder "v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)" (Quelldatei wird kompiliert ..\src\serialport_win.cpp)
  C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(672): note: bei Anpassung der Argumentliste "(v8::Isolate *, const char *, uint32_t)" (Quelldatei wird kompiliert ..\src\serialport_win.cpp)
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(676): error C2440: "return": "v8::MaybeLocal<v8::Object>" kann nicht in "v8::Local<v8::Object>" konvertiert werden (Quelldatei wird kompiliert ..\src\serialport_win.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
  C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(676): note: Quelltyp konnte von keinem Konstruktor angenommen werden, oder die šberladungsaufl”sung des Konstruktors ist mehrdeutig (Quelldatei wird kompiliert ..\src\serialport_win.cpp)
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(683): error C2039: "Use": Ist kein Element von "node::Buffer" (Quelldatei wird kompiliert ..\src\serialport_win.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
  C:\Users\d037602\.node-gyp\4.1.2\include\node\node_buffer.h(8): note: Siehe Deklaration von "node::Buffer" (Quelldatei wird kompiliert ..\src\serialport_win.cpp)
C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\node_modules\nan\nan.h(683): error C3861: "Use": Bezeichner wurde nicht gefunden. (Quelldatei wird kompiliert ..\src\serialport_win.cpp) [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(152): warning C4311: "Typumwandlung": Zeigerverkrzung von "HANDLE" zu "int" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(152): warning C4302: "Typumwandlung": Verkrzung von "HANDLE" in "int" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(177): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(179): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(183): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(185): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(189): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(191): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(196): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(208): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(308): warning C4311: "Typumwandlung": Zeigerverkrzung von "HANDLE" zu "int" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(308): warning C4302: "Typumwandlung": Verkrzung von "HANDLE" in "int" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(318): warning C4311: "Typumwandlung": Zeigerverkrzung von "HANDLE" zu "int" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(318): warning C4302: "Typumwandlung": Verkrzung von "HANDLE" in "int" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(328): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(353): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(366): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(401): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(403): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(502): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
..\src\serialport_win.cpp(511): warning C4312: "Typumwandlung": Konvertierung von "int" in gr”áeren Typ "HANDLE" [C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport.vcxproj]
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport\v1.7.4\Release\node-v46-win32-x64\serialport.node --module_name=serialport --module_path=C:\Program Files\nodejs\node_modules\johnny-five\node_modules\serialport\build\serialport\v1.7.4\Release\node-v46-win32-x64' (1)
johnny-five@0.8.100 node_modules\johnny-five
â”œâ”€â”€ ease-component@1.0.0
â”œâ”€â”€ descriptor@0.1.0
â”œâ”€â”€ color-convert@0.5.3
â”œâ”€â”€ temporal@0.4.1
â”œâ”€â”€ nanotimer@0.3.10
â”œâ”€â”€ es6-shim@0.33.6
â”œâ”€â”€ chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)
â”œâ”€â”€ array-includes@3.0.1 (define-properties@1.1.1, es-abstract@1.3.2)
â”œâ”€â”€ lodash@3.10.1
â””â”€â”€ firmata@0.5.5 (object-assign@1.0.0, browser-serialport@2.0.3, es6-map@0.1.1)

**Comment by fivdi** [comment]
This is happening because serialport, which Johnny-Five depends on, hasn't yet been upgraded to support Node.js 4.x. See https://github.com/voodootikigod/node-serialport/issues/578 for further details. Everything should work with Node.js v0.12.x.
