### ISSUE TITLE
Can We connect from host to arduino by wifi or bluetooth?

### ISSUE THREAD

**Issue by jackyphuong** [rwaldron/johnny-five#922]
Hello, while developing or run js code, we need to connect to arduino by usb connection. Could we replace it by wifi or bluetooth? I intend to use esp8266 but dont find any document to implement it.

**Comment by rwaldron** [comment]
cc @monteslu @ajfisher

**Comment by ajfisher** [comment]
@jackyphuong are you simply trying to talk to you arduino over wifi / bluetooth or are you trying to flash it that way?

If it's simply replace the cable for talking to it (once firmata is already on the board) then there's two paths for you:

Bluetooth: 

Depends on your module as to whether you're using HC-05 or HC06 (and they are different)

HC-05: https://github.com/rwaldron/johnny-five/wiki/Getting-Started-with-Johnny-Five-and-HC-05-Bluetooth-Serial-Port-Module
HC-06: https://github.com/rwaldron/johnny-five/wiki/Getting-Started-with-Johnny-Five-and-JY-MCU-Bluetooth-Serial-Port-Module

Current method of getting wifi going using ESP8266 using UDP-Serial Bridge
https://gist.github.com/ajfisher/5fe60fe7d8c49b3223f0

**Comment by jackyphuong** [comment]
Thanks @ajfisher, it really only replace cable. I followed link use bluetooth HC-06, it works well

**Comment by ajfisher** [comment]
Excellent - good to hear!
