### ISSUE TITLE
Neopixel/RGB LED strips

### ISSUE THREAD

**Issue by alexcroox** [rwaldron/johnny-five#925]
Does Johnny-five support Adafruit Neopixels (WS2812 and WS2811 LED/drivers) or similar RGB LED strips?

**Comment by frxnz** [comment]
You can use Neopixels with Johnny-Five using [node-pixel](https://github.com/ajfisher/node-pixel). Node-pixel supports WS2812, and I *believe* WS2811 strips will work as well.

**Comment by rwaldron** [comment]
Thanks @frxnz

**Comment by alexcroox** [comment]
Ah perfect thank you. And for the [non addressable strips](https://www.sparkfun.com/products/12023) what would you recommend?

**Comment by alexcroox** [comment]
https://learn.adafruit.com/rgb-led-strips/usage are the non addressable wiring diagram. 

I'm guessing I could use J5 LED RGB? https://github.com/rwaldron/johnny-five/blob/master/docs/led-rgb.md

**Comment by frxnz** [comment]
Yep. Most non-addressable strips should just work with the `Led`/`Led.RGB` classes.

**Comment by alexcroox** [comment]
Appreciate it thank you!
