### ISSUE TITLE
Adafruit Audio FX Sound Board Support

### ISSUE THREAD

**Issue by topkoa** [rwaldron/johnny-five#936]
Hey I've ordered a couple of these for my testing and would like to use it in an up-coming project...

Looking for some advice on connecting it to an Arduino/J5, specifically should I control it via the Serial/UART or via GPIO pins? (It can handle both, so I'm looking for the (easiest) most accepted solution when controlling it via JS/J5)

Thanks!

https://learn.adafruit.com/adafruit-audio-fx-sound-board/triggering-audio
https://learn.adafruit.com/adafruit-audio-fx-sound-board/serial-audio-control

**Comment by rwaldron** [comment]
> Looking for some advice on connecting it to an Arduino/J5, specifically should I control it via the Serial/UART or via GPIO pins

Support is inbound! https://github.com/jgautier/firmata/pull/97

**Comment by topkoa** [comment]
Awesome!

Looking forward to seeing it land!

**Comment by rwaldron** [comment]
I'll keep this open until we can come back to it :)

**Comment by topkoa** [comment]
Hey I see support landed over with firmata! 

I'm looking forward to checking it out.  I have a question, however-- can the ".serialConfig" (et al) be utilized within the confines of the J5 API? Or is that support still on it's way?

**Comment by dtex** [comment]
@topkoa All the firmata serial commands are exposed on the board.io object (which by default is an instance of firmata) so:

````
var five = require("johnny-five");
var board = new five.Board();

board.on("ready", function() {
  this.io.serialConfig({ portId: 8, baud: 9600, rxPin: 10, txPin: 11 });
  this.io.serialRead(8, function(data) {
    console.log(data);
  });
});
````

The constants for portID's are defined in firmata. I just used "8" which is SW_SERIAL0.

**Comment by dtex** [comment]
Hi @topkoa  

Johnny-Five contributors and maintainers are loathe to close issues where someone has a need. We don't want anyone to ever feel that we don't care, but we just haven't gotten to this feature yet. Rather than leave it languishing as an open issue we have created a [Requested Features](../wiki/Requested-Features) page and added this devices request under the new class "Sound Generator/Synthesizer" listed there.
