### ISSUE TITLE
Reading temperature and pressure stops after few seconds

### ISSUE THREAD

**Issue by mjuanfe** [rwaldron/johnny-five#948]
I'm trying this example:

```
    var five = require("johnny-five");
    var board = new five.Board();

    board.on("ready", function() {
      var multi = new five.Multi({
        controller: "BMP180"
      });

      multi.on("change", function() {
        console.log("temperature");
        console.log("  celsius      : ", this.temperature.celsius);
        console.log("  fahrenheit   : ", this.temperature.fahrenheit);
        console.log("  kelvin       : ", this.temperature.kelvin);
        console.log("--------------------------------------");

        console.log("barometer");
        console.log("  pressure     : ", this.barometer.pressure);
        console.log("--------------------------------------");
      });
    });
```

After run it works but after few seconds stops giving the information, why this happen? I'm doing something wrong? 

After few seconds windows prompt is again on my route:

```
        --------------------------------------
        temperature
          celsius      :  21.6
          fahrenheit   :  70.88
          kelvin       :  294.75
        --------------------------------------
        barometer
          pressure     :  102.0220
        --------------------------------------
        temperature
          celsius      :  21.6
          fahrenheit   :  70.88
          kelvin       :  294.75
        --------------------------------------
        barometer
          pressure     :  102.0180
        --------------------------------------

        C:\nodes\arduino>
```

I think this guy has the same problem: http://stackoverflow.com/questions/33247480/arduino-uno-and-johnny-five-stops-after-few-seconds

**Comment by fivdi** [comment]
If Node.js v4 or higher is being then the issue is highly likely to be related to serialport which has issues with Node.js 4 on Windows. See https://github.com/voodootikigod/node-serialport/issues/578.

**Comment by mjuanfe** [comment]
Thanks for the fast response, tomorrow I'll try with a different version of node and I'll tell you how was.

**Comment by fivdi** [comment]
AFAIK everything should be fine with Node.js v0.12.x on Windows.

**Comment by mjuanfe** [comment]
I installed  nvm for windows and tried the 0.12.2 version, still not working :(

**Comment by fivdi** [comment]
Hmm, sorry to hear that. I'm afraid I don't have a windows machine and can't really provide any further information. Is exactly the same thing happening?

**Comment by mjuanfe** [comment]
Yes, the same result, I think I'll try to install a VM with Ubuntu, anyway bothers me not solve it! grrr...

**Comment by rwaldron** [comment]
Any updates?

**Comment by dtex** [comment]
Hi @mjuanfe Since we haven't heard back I'm going to close this. Please feel free to re-open this any time if it is still an issue for you.

**Comment by mjuanfe** [comment]
Hi @dtex , thanks for update this old issue, I think it's solved.
