### ISSUE TITLE
breakout MockFirmata into its own package

### ISSUE THREAD

**Issue by boneskull** [rwaldron/johnny-five#949]
this would be helpful for testing libs which leverage j5, though not absolutely a big deal.

workaround: `require('johnny-five/test/util/mock-firmata')`

it may free j5 up to add `test/` to `.npmignore`, if that's something you're interested in.  in my packages, I tend to add anything to `.npmignore` which need the `devDependencies` to run.  the tests may be useful as reference material, however.

**Comment by dtex** [comment]
It could/should also be used in the nodebots workshopper.

**Comment by boneskull** [comment]
dupe of #735

**Comment by rwaldron** [comment]
https://github.com/rwaldron/mock-firmata
