### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by mandeeps708** [rwaldron/johnny-five#951]
https://github.com/rwaldron/johnny-five#infrared-reflectance
Section heading braces.
Maybe the opening parenthesis is missing.

**Comment by dtex** [comment]
Hi @mandeeps708 That was fixed by #935 and next time the readme is generated it will be gone. Thanks for reporting.

**Comment by mandeeps708** [comment]
Sorry, I didn't know if it was there.

**Comment by dtex** [comment]
No apologies necessary, we'll take all the help we can get :-)
