### ISSUE TITLE
Temperature => Thermometer?

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#953]
Let's consider this...

**Comment by BrianGenisio** [comment]
Yep.

**Comment by rwaldron** [comment]
FTR, I am obviously +1

We would not eliminate `Temperature`, we'd just rename to `Thermometer` and provide an alias for compatibility. Then all examples would be updated to use new API name

**Comment by rwaldron** [comment]
- [x] Renaming files, updating file names
- [x] Alias: Temperature -> Thermometer
- [x] Update wiki
- [x] Update examples

https://github.com/rwaldron/johnny-five/commit/1cd5eeb01c143dc4a70f35630d7cec65b2b9c6a5

**Comment by rwaldron** [comment]
Also, schedule here: https://github.com/rwaldron/johnny-five/wiki/Temperature
