### ISSUE TITLE
Update wiki API docs pages: Reformat "Shape" sections

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#958]
Here's an example of the new format: 

```
| Property Name | Description | Read Only |
|---------------| ----------- | ----------|
| `accelerometer` | An instance of `Accelerometer` class. | Yes |
| `altimeter` | An instance of `Altimeter` class. | Yes |
| `barometer` | An instance of `Barometer` class. | Yes |
| `gyro` | An instance of `Gyro` class. | Yes |
| `hygrometer` | An instance of `Hygrometer` class. | Yes |
| `thermometer` | An instance of `Thermometer` class. | Yes |
```

**Comment by scottgonzalez** [comment]
Do you want a checklist to ease collaboration?

* [ ] Accelerometer
* [ ] Altimeter
* [ ] Animation
* [ ] Barometer
* [ ] Board
* [ ] Boards
* [ ] Button
* [ ] Compass
* [ ] ESC
* [ ] Expander
* [ ] Gyro
* [ ] Hygrometer
* [ ] IMU
* [ ] IR.Reflectance
* [ ] Joystick
* [ ] LCD
* [ ] Led
* [ ] Led.Digits
* [ ] Led.Matrix
* [ ] Led.RGB
* [ ] Motion
* [ ] Motor
* [ ] Multi
* [ ] Piezo
* [ ] Pin
* [ ] Ping
* [ ] Proximity
* [ ] Relay
* [ ] Sensor
* [ ] Servo
* [ ] ShiftRegister
* [ ] Sonar
* [ ] Stepper
* [ ] Switch
* [ ] Temperature
* [ ] Thermometer

**Comment by rwaldron** [comment]
Thanks!

**Comment by rwaldron** [comment]
Th
