### ISSUE TITLE
reading status of a button

### ISSUE THREAD

**Issue by spokke** [rwaldron/johnny-five#978]
hi all,
i've set a security button (open or close) and all is working fine .. there is a way to read status of switch button  ? 
thank you

**Comment by scottgonzalez** [comment]
Assuming you're using the `Switch` component, you can just check the `isClosed` property. See http://johnny-five.io/api/switch/#shape.

**Comment by spokke** [comment]
thank you Scott ... i will try

**Comment by spokke** [comment]
working fine ... thank you

**Comment by rwaldron** [comment]
@spokke can this issue be closed?

**Comment by spokke** [comment]
Yes thank you

Inviato da iPhone
