### ISSUE TITLE
Servo.home()

### ISSUE THREAD

**Issue by dtex** [rwaldron/johnny-five#986]
I'm considering adding this. It would return the servo to its startAt position.

Yes, it's just sugar for:
````
servo.to(servo.startAt);
````

but it becomes really valuable in the context of a Servos collection:
````
servos.home(); // returns all servos in the array to their unique startAt positions
````

So whaddya think :+1: or :-1:?

**Comment by fivdi** [comment]
It may be sugar but requires a lot less thinking. I like it.

**Comment by UlisesGascon** [comment]
Great idea! I like it :+1:

**Comment by rwaldron** [comment]
:+1: 

As @fivdi said: 

> It may be sugar but requires a lot less thinking. I like it.

**Comment by ajfisher** [comment]
:+1: The amount of times I would use this!

**Comment by dtex** [comment]
In PR #990

**Comment by dtex** [comment]
Landed
