### ISSUE TITLE
Q: Artwork license - ok, to redistribute?

### ISSUE THREAD

**Issue by mwittig** [rwaldron/johnny-five#989]
Quick question: I would like to use the J5 SVG artwork as part of my project. Does the project's licence also cover the artwork? Here is the credit I am planning to add to the project README and another Readme file in the assets direcrectory:
```
--------------------
The 'johnny-five-icon' files have been created with [Inkscape](https://inkscape.org) using artwork
by [Mike Sgier](http://msgierillustration.com/) published as part of the Johnny Five project.

Copyright (c) 2012, 2013, 2014 Rick Waldron <waldron.rick@gmail.com>
Copyright (c) 2014, 2015 The Johnny-Five Authors

MIT-License: https://github.com/rwaldron/johnny-five/blob/master/LICENSE-MIT
--------------------
```

**Comment by rwaldron** [comment]
@mwittig yes, that is sufficient credit :) Also, thanks for being so considerate!


I will let you close the issue—thanks!
