### ISSUE TITLE
Does johnny five support fubarino?

### ISSUE THREAD

**Issue by frankely** [rwaldron/johnny-five#991]
I just got a few fubarinos and I was wondering if johnny five is compatible with them.

http://fubarino.org/

**Comment by dtex** [comment]
Duplicate of my response on Gitter:

It looks likes it just needs to be added to the board definitions in StandardFirmata. Here is [an example](https://github.com/firmata/arduino/blob/3b748e87bf7a69dd59b5eca207c3624e54766d09/Boards.h#L245-L265) of where that was done for the Arduino Zero Pro. I’d run it by @soundanalogous first

**Comment by dtex** [comment]
Scratch that:  https://github.com/firmata/arduino/pull/210
